### ISSUE TITLE
`Multi hit` issue with few characters

### ISSUE THREAD

**Issue by souvikpodder** [Akebi-Group/Akebi-GC#10]
This was in previous repo. 
When multi hit is on few characters charged attack doesn't do any damage.
I found below characters have the problem. there may be others also.

~~- Ayaka, Zhongli, Xiangling **charged attack**~~ (fixed August 7, 2022)

~~- Xiao's E doesn't do any damage when multi hit is on.~~ (fixed August 6, 2022)

**Comment by G1DE30N** [comment]
I don't agree about Ayaka and Xiangling, because everything works fine for me on her.

**Comment by monado1110** [comment]
hutao too

**Comment by G1DE30N** [comment]
When charged attack doesn't work on Ayaka 
![image](https://user-images.githubusercontent.com/104440397/169602128-9fe07b90-59a5-4df7-9c8e-c74c89a9d082.png)

**Comment by KnawKx** [comment]
i am using Xiangling and everything is normal
