### ISSUE TITLE
Convert XYZ teleport to Json

### ISSUE THREAD

**Issue by Legend-Recalls** [Akebi-Group/Akebi-GC#101]
I remember being able to convert
[vector]
x=1323.06
y=201.31
z=279.57
the following formatted files into json files. There was a python program by @Shichiha  shared on the prev repo . it wd be kind of you to reshare it please

**Comment by Screenatyouruse** [comment]
```python
# Jenshin XYZ Format
# example:
    # [vector]
    # x=-4582.554199
    # y=202.659744
    # z=-4241.833496
# To my json Format
# example:
    # {"name":"Amakumo Fruit","position":[-4582.554199,202.659744,-4241.833496]}
import os
import json
import tkinter as tk
from tkinter import filedialog
# You can use any other library but tkinter is recommended
root = tk.Tk()
root.withdraw()
path = filedialog.askdirectory()
files = os.listdir(path)
# If you don't want to use tkinter, you can hardcode the path like this:
# path = "/Users/jenshin/Desktop/JenshinToCallow"
# and just remove the imports and code from tkinter
inp=input("Do you wish to delete the old files? (y/n)")
inp2=input("Do you wish to name the files after the folder? (y/n)")
for root, dirs, files in os.walk(path):
    for file in files: 
        if file.endswith(".txt"):
            name = file.split(".")[0]
            with open(os.path.join(root, file), "r") as f:
                positions = []
                for line in f:
                    if line.startswith("x"):
                        x = line.split("=")[1].strip()
                    if line.startswith("y"):
                        y = line.split("=")[1].strip()
                    if line.startswith("z"):
                        z = line.split("=")[1].strip()
                        positions.append([x, y, z])
                json_string = '{"name":"' + name + '","position":' +  "[" + x + "," + y + "," + z + "]}"
                print(json_string)
                if inp2==y:
                    # get parent folder name
                    parent_dir = os.path.basename(os.path.abspath(os.path.join(root, os.pardir)))
                    # get file name
                    file_name = os.path.basename(os.path.abspath(os.path.join(root, file)))
                    with open(os.path.join(root, parent_dir + "_" + file_name + ".json"), "w") as f:
                        f.write(json_string)
                else:
                    with open(os.path.join(root, name + ".json"), "w") as f:
                        f.write(json_string)
                if inp == "y":
                    os.remove(os.path.join(root, file))
```
Is this what you want? I contacted @Shichiha and she gave me this.

**Comment by Legend-Recalls** [comment]
> ```python
> # Jenshin XYZ Format
> # example:
>     # [vector]
>     # x=-4582.554199
>     # y=202.659744
>     # z=-4241.833496
> # To my json Format
> # example:
>     # {"name":"Amakumo Fruit","position":[-4582.554199,202.659744,-4241.833496]}
> import os
> import json
> import tkinter as tk
> from tkinter import filedialog
> # You can use any other library but tkinter is recommended
> root = tk.Tk()
> root.withdraw()
> path = filedialog.askdirectory()
> files = os.listdir(path)
> # If you don't want to use tkinter, you can hardcode the path like this:
> # path = "/Users/jenshin/Desktop/JenshinToCallow"
> # and just remove the imports and code from tkinter
> inp=input("Do you wish to delete the old files? (y/n)")
> inp2=input("Do you wish to name the files after the folder? (y/n)")
> for root, dirs, files in os.walk(path):
>     for file in files: 
>         if file.endswith(".txt"):
>             name = file.split(".")[0]
>             with open(os.path.join(root, file), "r") as f:
>                 positions = []
>                 for line in f:
>                     if line.startswith("x"):
>                         x = line.split("=")[1].strip()
>                     if line.startswith("y"):
>                         y = line.split("=")[1].strip()
>                     if line.startswith("z"):
>                         z = line.split("=")[1].strip()
>                         positions.append([x, y, z])
>                 json_string = '{"name":"' + name + '","position":' +  "[" + x + "," + y + "," + z + "]}"
>                 print(json_string)
>                 if inp2==y:
>                     # get parent folder name
>                     parent_dir = os.path.basename(os.path.abspath(os.path.join(root, os.pardir)))
>                     # get file name
>                     file_name = os.path.basename(os.path.abspath(os.path.join(root, file)))
>                     with open(os.path.join(root, parent_dir + "_" + file_name + ".json"), "w") as f:
>                         f.write(json_string)
>                 else:
>                     with open(os.path.join(root, name + ".json"), "w") as f:
>                         f.write(json_string)
>                 if inp == "y":
>                     os.remove(os.path.join(root, file))
> ```
> 
> Is this what you want? I contacted @Shichiha and she gave me this.


It indeed is! thankyou so much and also ty I didnt know shichiha is a lady 😓lmao

**Comment by Legend-Recalls** [comment]
oops misclick

**Comment by Shichiha** [comment]
you can remove the 
```
inp=input("Do you wish to delete the old files? (y/n)")
inp2=input("Do you wish to name the files after the folder? (y/n)")
``` 

parts ig

**Comment by Legend-Recalls** [comment]
nah finna recreate that

**Comment by Shichiha** [comment]
Note that I *might* be changing the teleport format soon... (emphasis on the might)

**Comment by Legend-Recalls** [comment]
> Note that I _might_ be changing the teleport format soon... (emphasis on the might)

💀amen
