### ISSUE TITLE
crash after enabling interactive map

### ISSUE THREAD

**Issue by menou1** [Akebi-Group/Akebi-GC#102]
after enabling interactive map the game crashes, i also had turned on all the chests to show up on the map except remarkable chests

now every time i open the game it crashes while loading ( when the game should open and display the map so interactive map turns on as well ) literally gets stuck at the geo element while loading and the game goes on unresponding

no error in the console or anything

fixed the crash by setting m_InteractiveMap toggle to false but that still doesn't fix the main issue of the interactive map crashing

my main reason of the crash is because of the completed points? not sure but maybe if there's a corrupt completed point or something it just crashes

**Comment by CallowBlack** [comment]
send your config

**Comment by menou1** [comment]
> Send your config. If you don't want to send it here, you can pm me in discord Callow#1429.

https://pastebin.com/raw/nak5XJxw

just changed the uid to "UID" so i'm not leaking my uid

**Comment by CallowBlack** [comment]
Hmm, I have some troubles with reproducing: 
![image](https://user-images.githubusercontent.com/37184274/173244024-25cbb7c5-115b-42db-8102-05d51391e75a.png)

**Comment by menou1** [comment]
actually tried with a new one and just turning it on makes me crash i have no idea why

https://streamable.com/j2viys

**Comment by menou1** [comment]
reinstalled genshin and still crashes

**Comment by RyujinZX** [comment]
> переустановил геншин и все равно вылетает

Try trivial things, delete config, run Injector as administrator

> Author

Try trivial things, delete config, run Injector as administrator

**Comment by menou1** [comment]
actually had to wait a little bit more and it worked
