### ISSUE TITLE
[build] anyone else getting this after latest commit?

### ISSUE THREAD

**Issue by Lunairayz** [Akebi-Group/Akebi-GC#103]
commit c7d6228 to be spefic

![image](https://user-images.githubusercontent.com/45308130/173245112-7910c5cc-9486-46f4-87a4-90c7ce93dcbd.png)

**Comment by RyujinZX** [comment]
Hi, clone the current Akebi repository via GitHub Desktop, and compile :)

**Comment by Lunairayz** [comment]
> Hi, clone the current Akebi repository via GitHub Desktop, and compile :)

hm
![image](https://user-images.githubusercontent.com/45308130/173290896-9916f84b-0b5c-4e0d-8ffc-2f3219f662e5.png)

**Comment by CR4Player** [comment]
> > Hi, clone the current Akebi repository via GitHub Desktop, and compile :)
> 
> hm ![image](https://user-images.githubusercontent.com/45308130/173290896-9916f84b-0b5c-4e0d-8ffc-2f3219f662e5.png)
<img width="212" alt="屏幕截图 2022-06-13 144108" src="https://user-images.githubusercontent.com/12210261/173294533-4969e04f-c817-4820-a2b8-47648a6c4ff4.png">
try switching to release x64 and re-compile

**Comment by Lunairayz** [comment]
> > > Hi, clone the current Akebi repository via GitHub Desktop, and compile :)
> > 
> > 
> > hm
> 
> <img alt="屏幕截图 2022-06-13 144108" width="212" src="https://user-images.githubusercontent.com/12210261/173294533-4969e04f-c817-4820-a2b8-47648a6c4ff4.png">
> 
> try switching to release x64 and re-compile

well that worked
wonder what's the issue with debug
![image](https://user-images.githubusercontent.com/45308130/173295336-91f26c04-12be-49c1-8429-6c6f10944a24.png)
