### ISSUE TITLE
when i start the cheat this appear

### ISSUE THREAD

**Issue by tayhm0817** [Akebi-Group/Akebi-GC#109]
![image](https://user-images.githubusercontent.com/104625131/173504454-6d955447-c045-42bb-ab63-3b00ffcd4a1a.png)

**Comment by tayhm0817** [comment]
anyone know why this is happening?

**Comment by tedzify** [comment]
Use the `injector.exe` to launch the game. It should be at the same folder with `CLibrary.dll`.
