### ISSUE TITLE
Copy dll failed: The system cannot find the file specified

### ISSUE THREAD

**Issue by Frosteex** [Akebi-Group/Akebi-GC#114]
I have a problem with cheat Akebi-GC.
After I uploaded it by command https://github.com/Akebi-Group/Akebi-GC.git I opened akebi-gc.sln. If I understood correctly I should use debug function on screen lower.
![pic_2](https://user-images.githubusercontent.com/107541832/173781808-27e26a86-33db-4cd5-98c5-97e96607d796.jpg)
![pic](https://user-images.githubusercontent.com/107541832/173781854-0b9cb71f-c673-4884-87cd-6e9f09aa3535.jpg)
At least I got message "Copy dll failed: The system cannot find the file specified.". I tried search file CLibrary.dll on my PC. But it`s missing Thank you for a help.

**Comment by Screenatyouruse** [comment]
It seems you havent compiled the clibrary.dll yet. Try right clicking "akebi-gc" and click Build Solution, then run without debugger.

**Comment by Frosteex** [comment]
You are right! I did as you said. After Build Solutin I`ve got some errors:
![image](https://user-images.githubusercontent.com/107541832/173786924-4b888d69-63bd-4ce4-935f-d5d1dd36bc0d.png)
Are they critical?

**Comment by tedzify** [comment]
Build `Release`. Not `Debug`.
![Screenshot_94](https://user-images.githubusercontent.com/99535026/173796897-9f22e116-5ec5-4d22-9aaf-dd199444cb46.png)

**Comment by Frosteex** [comment]
Thank you. Done with Release.
![image](https://user-images.githubusercontent.com/107541832/173799917-b3ff07f4-1913-4027-b8b0-567538df46dd.png)
Active features is aviable in the game. But doesn`t active :(
![image](https://user-images.githubusercontent.com/107541832/173800220-1f820f35-6136-4a82-9669-89ef11a54ef3.png)

**Comment by tedzify** [comment]
Have you activated anything? Press the default menu key `F1` or the key you've set it at.

**Comment by CallowBlack** [comment]
Please, read the `ReadMe`, 
```
It is reccomended to use [Visual Studio 2022.](https://visualstudio.microsoft.com/) 
As well as setting up cheat-library as startup project. The following is a recommended procedure, but others may be used.
```
You should select `cheat-library` as startup project.

**Comment by Frosteex** [comment]
> Have you activated anything? Press the default menu key `F1` or the key you've set it at.

You are right. I just should use F1 key. Now everything fine and thanks to everybody for a help!
