### ISSUE TITLE
hotkeys that are attached to the side mouse buttons do not work

### ISSUE THREAD

**Issue by lolkop** [Akebi-Group/Akebi-GC#117]
I don't know about you, but it doesn't work for me. maybe the problem is in the mouse?

**Comment by m0nkrel** [comment]
which commit do you use?

**Comment by lolkop** [comment]
last?:\

> which commit/version do you use?

**Comment by m0nkrel** [comment]
> 

write a version / commit

**Comment by lolkop** [comment]
> > 
> 
> write a version / commit

v0.7.5 (game ver. 2.7)

**Comment by m0nkrel** [comment]
> > > 
> > 
> > write a version / commit
> 
> v0.7.5 (game ver. 2.7)

Okay. XButton1/2(mouse 4/5) fixed in d0a07b03442954caa69705282fb699bbd64c6dda commit. So you need to wait when another version will be released or compile it by yourself.
