### ISSUE TITLE
`crash` Interactive map

### ISSUE THREAD

**Issue by vyachnd** [Akebi-Group/Akebi-GC#121]
When the **interactive map** is enabled, the entrance to locations where there is **no map** *(dawn winery, dungeons, etc.)*, the game may crash.

**InMap settings:**
- Fix item positions
- Detect new items
- Detect only showed
- Detect gathered items
- Filters on everything **except** monsters/bosses

*Other settings are not used or have not been changed*

A **warning** about an exception associated with an **interactive map** is displayed in the console.

```cpp
// Exclusion warnings when switching to a location
[Warning] [InteractiveMap.cpp:1346] Exception 0xe06d7363.

// Exception warnings when the game is already crashing ( only when the game crashes )
[Warning] [cheat.cpp:154] Exception 0xe06d7363.
[Warning] [cheat.cpp:154] Exception 0xc0000005.
```

**Comment by RyujinZX** [comment]
What other features were included?

**Comment by RyujinZX** [comment]
> > What other features were included?
> 
> I can't say for sure, but here is my [cfg](https://github.com/Akebi-Group/Akebi-GC/files/8918775/cfg.zip) _( without the **shared** field )_
> 
> _Question outside issue: How does skip cutscene work? There were several cut scenes, but they were not skipped._

It only passes game films, I have no opportunity to check them all because there are so many of them.

**Comment by RyujinZX** [comment]
The game film is a scene that does not work TimeScale - (dialog speed)

**Comment by RyujinZX** [comment]
Ты похоже говоришь на Русском, все такие вопросы можешь задать мне в нашем дискорде

**Comment by Taiga74164** [comment]
crash should be fixed with https://github.com/Akebi-Group/Akebi-GC/commit/f0ae3753f97dcc989be34bf2826d5921e5f511dd
