### ISSUE TITLE
Fixed This please

### ISSUE THREAD

**Issue by Badsha71** [Akebi-Group/Akebi-GC#126]
https://github.com/Akebi-Group/Akebi-GC/issues/122#issue-1274056855

**Comment by Taiga74164** [comment]
why did you open another issue :skull:

**Comment by Badsha71** [comment]
Everyone get there answer but my issued isn't noticed by admin or owner,so create it

**Comment by Shichiha** [comment]
Creating a second issue won't make it get solved faster...

**Comment by Taiga74164** [comment]
no issues have been marked with tags for the past 2 days

**Comment by Badsha71** [comment]
Oh ok
