### ISSUE TITLE
how to Build solution akebi-gc.sln

### ISSUE THREAD

**Issue by AnZhuoMan** [Akebi-Group/Akebi-GC#128]
how to Build solution akebi-gc.sln

**Comment by Fanixtar** [comment]
Read issue

- Clone repository with `git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git`
- Open `Akebi-GC/akebi-gc.sln`
- Build solution `akebi-gc.sln`

**Comment by AnZhuoMan** [comment]
The last step is not clear

**Comment by Fanixtar** [comment]
Eye issue

![image](https://user-images.githubusercontent.com/96950043/174427010-1736e3e7-38d9-413c-bf68-42d7cf8526d8.png)

**Comment by ydq5532** [comment]
maybe you should find it VS tutorials

**Comment by AnZhuoMan** [comment]
Is it okay to press the green arrow

**Comment by Fanixtar** [comment]
okay

**Comment by AnZhuoMan** [comment]
thank

**Comment by AnZhuoMan** [comment]
.. Where am the files I built

**Comment by Fanixtar** [comment]
in `Akebi-GC\bin\Debug` or `Akebi-GC\bin\Release`

**Comment by AnZhuoMan** [comment]
Just one exe file and a whole bunch of other files and a folder

**Comment by Fanixtar** [comment]
everything inside the folder is the files you built

**Comment by AnZhuoMan** [comment]
But I only built an exe file shouldn't there be a dll file to build

**Comment by Lunairayz** [comment]
omg
copy these files to a separate folder
![image](https://user-images.githubusercontent.com/45308130/174428605-98d9dd68-ba60-4d6b-bbf1-f71e33d48edf.png)
