### ISSUE TITLE
several .dll not found causing the injector.exe not running

### ISSUE THREAD

**Issue by Raiden39** [Akebi-Group/Akebi-GC#134]
![image](https://user-images.githubusercontent.com/98318018/174475591-95a2d3ad-4eee-4df5-810d-189a346e870e.png)
![image](https://user-images.githubusercontent.com/98318018/174475596-925ca163-4fa3-48ce-8a30-4875c6f71f4c.png)
![image](https://user-images.githubusercontent.com/98318018/174475601-cf8f4dfc-8539-4bac-aeb9-79ddaf7f2e9c.png)

**Comment by Shichiha** [comment]
Install the Microsoft Visual C++ Redistributables on your PC, or download the same missing DLLs and place them in the same directory

**Comment by tedzify** [comment]
Install all necessary `Visual C++ Redistributable Runtimes`. I recommend this [All in one vcredist 2005-2019](https://www.techpowerup.com/download/visual-c-redistributable-runtime-package-all-in-one/)
