### ISSUE TITLE
game crash after use some hour with cheat active 

### ISSUE THREAD

**Issue by Badsha71** [Akebi-Group/Akebi-GC#136]
when I use the cheat like god mod on and attack mod my game crash on a certain moment and closed with pop up message like not responding. 2days ago my game was running well with active cheat but now it crushing when fighting or teleporting, I don't know why its happened it occur after random time.

I found the issue why its crushing. With god mod and one punch hit active and using the character xiangling. (screenshot below):
![Screenshot (379)](https://user-images.githubusercontent.com/57755184/174556242-c987be05-89ac-4a64-b8df-1fb010ee67e4.png)
![Screenshot (380)](https://user-images.githubusercontent.com/57755184/174556269-16e76302-13aa-45e7-b81b-f73da6cd21dc.png)

Here is my log file: 
[log_2022-05-18_10-15.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938800/log_2022-05-18_10-15.txt)
[log_2022-05-18_13-32.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938801/log_2022-05-18_13-32.txt)
[log_2022-05-18_18-44.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938802/log_2022-05-18_18-44.txt)
[log_2022-05-19_07-51.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938803/log_2022-05-19_07-51.txt)
[log_2022-05-19_08-49.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938804/log_2022-05-19_08-49.txt)
[log_2022-05-19_10-28.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938805/log_2022-05-19_10-28.txt)
[log_2022-05-19_15-09.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938806/log_2022-05-19_15-09.txt)
[log_2022-05-19_16-21.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938807/log_2022-05-19_16-21.txt)
[log_2022-05-20_05-56.txt](https://github.com/Akebi-Group/Akebi-GC/files/8938808/log_2022-05-20_05-56.txt)

**Comment by Thereallo1026** [comment]
any logs or info

**Comment by Sergiy3013** [comment]
I and at least two other people have the same problem. This happens both in your world and in the world of other players. However, there are no error messages. The cheat just closes, and with it the game.

Here's what I had included during one of these sorties:
https://cdn.discordapp.com/attachments/980008184045527060/988124167675187240/unknown.png

**Comment by Badsha71** [comment]
I am using just active 2 cheat god mod and once punch attack,maybe its not with the cheat active, maybe its happening for the ejectoe which opening the game

**Comment by Badsha71** [comment]
@Thereallo1026  here is the log file
[log_2022-05-18_10-15.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937878/log_2022-05-18_10-15.txt)
[log_2022-05-18_13-32.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937879/log_2022-05-18_13-32.txt)
[log_2022-05-18_18-44.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937880/log_2022-05-18_18-44.txt)
[log_2022-05-19_07-51.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937881/log_2022-05-19_07-51.txt)
[log_2022-05-19_08-49.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937884/log_2022-05-19_08-49.txt)
[log_2022-05-19_10-28.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937885/log_2022-05-19_10-28.txt)
[log_2022-05-19_15-09.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937886/log_2022-05-19_15-09.txt)
[log_2022-05-19_16-21.txt](https://github.com/Akebi-Group/Akebi-GC/files/8937887/log_2022-05-19_16-21.txt)

**Comment by Fanixtar** [comment]
did it crash when you opened the Map?

**Comment by Sergiy3013** [comment]
In my case, it crashed when I was just walking around the world, right while running.

In the case of my friends:
• A couple of minutes walk after an hour in AFC
• When walking through the winter mountains in the alternate god mode.

(Sorry, no logs)

**Comment by Badsha71** [comment]
> did it crash when you opened the Map?

i dont know its happening random time when i am idle or doing some quest and teleporting myself for mission

**Comment by Badsha71** [comment]
@Fanixtar @Sergiy3013 @Thereallo1026 
I found the issue why its crushing. With god mod and one punch hit active and using the character xiangling.

**Comment by Sergiy3013** [comment]
@Badsha71 In my case, the problem of crashes is only in god mode

**Comment by Legend-Recalls** [comment]
in my case the game's like frozen with just 10 mins of afk, with everything off

**Comment by Sergiy3013** [comment]
> > @Badsha71 In my case, the problem of crashes is only in god mode. I have been playing for several hours without god mode and there are no crashes.
> 
> one time my game crush without any active cheat just opening with injector and playing few times then it crush.see my screenshot on main issue i just updated

@Badsha71, regarding your screenshot, it is noticeable that you attacked a hydro slime, sometimes when attacks create a lot of particles (from slimes, hypostasis or abyss mages) the game can freeze, this was before and is not related to the current problem.

**Comment by cip300** [comment]
Indeed the new god mode is problematic , it will randomly crash the game , at just a simple to only running trough dragonn spine mountain .
I notice a new file in injector folder : 
upload_err.log than contain this : 
upload_crash release upload:495363
200
file upload finish

**Comment by Sergiy3013** [comment]
I played 6 hours without god mode (old and new), everything is fine. I think this is enough to argue that the departures are connected with him.
