### ISSUE TITLE
The cheat is spreading in youtube. idk

### ISSUE THREAD

**Issue by Artherisk** [Akebi-Group/Akebi-GC#147]
I just found out the cheat is spreading in Youtube. are you guys the one who uploaded those cause I just want to clarify. Like these one https://www.youtube.com/watch?v=mdR5SyjXNws

**Comment by Taiga74164** [comment]
none of us have uploaded anything in youtube

**Comment by Taiga74164** [comment]
you should be only getting your information through GitHub or our discord server

**Comment by Fanixtar** [comment]
bruh
![image](https://user-images.githubusercontent.com/96950043/174722294-140a93fb-69ae-4604-a6a4-53a673363a81.png)

**Comment by RyujinZX** [comment]
All the videos on YouTube are spreading a virus, why in the year 22 people still don't know about it...
