### ISSUE TITLE
In game with hack some buttons don't work.

### ISSUE THREAD

**Issue by LipaSuiRed** [Akebi-Group/Akebi-GC#149]
In a normal game, everything is fine, but in a game with a cheat, some buttons stop working.  I reset the config and everything is fine, I set up functions and put binds, everything is also fine, but after restarting the game, the run buttons (shift and right mouse click) stop working, and I also cannot open the glider in the fall, plus a hold attack on  hu tao does not work at all, and on some catalysts the hold works from the fifth time.  The same thing happened when another player entered my world.  I corresponded with him and in order not to activate the functions, I unbind all the buttons, after which this problem appeared again.

**Comment by tedzify** [comment]
Disable `Infinite Stamina` or use `Infinite Stamina with [Move Sync Packet Replacement]`. This is a bug with `Infinite Stamina`.
