### ISSUE TITLE
UI getting misplaced

### ISSUE THREAD

**Issue by thesadru** [Akebi-Group/Akebi-GC#15]
Sometimes a UI module can move and block parts of the screen. It's still interactable, just inconvenient.

<details>
  <summary>Screenshots</summary>
  <img src="https://user-images.githubusercontent.com/58166507/169529998-81f4715a-668c-49d4-bee0-3fcdf525e723.png"/>
  <img src="https://user-images.githubusercontent.com/58166507/169530107-40598568-c6ba-4c6e-82a4-9aba8130d7c7.png"/>
  <img src="https://user-images.githubusercontent.com/58166507/169530188-e7dc831f-b82a-407c-b9de-c9d360262fc1.png"/>
</details>

(Are these even ok to show here? Idk the policy on this kinda stuff)

### metadata
Date Occurred: 2022-05-19
Is it reproducible: Not intentionally but it happens often enough to be relevant
Release Version: 0.7
Commit is unknown since the repository is unavailable

**Comment by G1DE30N** [comment]
This is very old bug with Interactive map and unfortunately cannot be fixed, Because Callow cant find What exactly makes this happening.

**Comment by thesadru** [comment]
If I don't use the interactive map does this mean I can just disable it to fix the issue?

**Comment by CallowBlack** [comment]
> Unfortunately not, bacause this wont fix bug. For fix you need erase all interactive map code from cheat by hand. Disabling int. map from menu just disables render, some parts of code still running.
> 
> You need to remove InteractiveMap.cpp and then Manually search and erase all links (and funcs) to this file in whole cheat code. (all source files) a can't help you with that because i don't do that for myself becacuse i just restarted game if this bug occurs and don't see a problem with that too much.

Why you ensure that the deal with interactive map?

**Comment by G1DE30N** [comment]
Because rapidly changed interactive map offsets affects to ui elements.

**Comment by G1DE30N** [comment]
I simply tp to Enkanomya -> world -> encanomya - over 10 or 20 times in a row and get ui offsets with 100% success.
I also noticed that the interface offsets are beating in domains and similar places almost every time the cheat spits out an exception related to the inability to display any elements of the interactive map because there is no place to get them from

**Comment by G1DE30N** [comment]
Answer to you callow - My simple research about that.

**Comment by G1DE30N** [comment]
I'M NOT SAYING that disabling the interactive map WILL FIX the problem, I'm just GUESSING, based on my experiments and conclusions, I may be WRONG. It's just A GUESS. I would check the disconnection of the map and look at the results, but alas, my programming SKILLS are only the ability to deploy a project in visual studio and assemble it, I'm a complete ZERO in the code.

**Comment by G1DE30N** [comment]
```
SAFE_BEGIN();
return app::Behaviour_get_isActiveAndEnabled(reinterpret_cast<app::Behaviour*>(_monoMiniMap), nullptr);
SAFE_ERROR();
_monoMiniMap = nullptr;
return false;
SAFE_END();
```

This is not related to UI offsets, just my another observation.
When tp: Encanomia - World - Underground Chasm - Encanomia and repeat, with each teleportation, this piece of code spits out an exception.
![image](https://user-images.githubusercontent.com/104440397/169374760-f5a65fe5-380f-4bdf-b258-a9e52fbd9770.png)

**Comment by CallowBlack** [comment]
Wow, thank you with your research, I think it helps me to detect reason.

**Comment by G1DE30N** [comment]
You're welcome, if I can catch the error in more precise ways, I'll definitely let you know about it.

**Comment by Legend-Recalls** [comment]
@thesadru just saying, ur uid is visible ahem

**Comment by G1DE30N** [comment]
> @thesadru just saying, ur uid is visible ahem

Ahhh now i see why hiding Uid func is needed, because someone like @thesandru just don't know how to crop screenshots xD

**Comment by thesadru** [comment]
it's more like I didn't see the reason to hide my uid, I already have it public in many other places anyways

**Comment by G1DE30N** [comment]
> It's more like I didn't see the reason to hide my uid, I already have it public in many other places anyways. No need to assume inability when it could've been negligence (and vice versa) 😕

I mean it's not a big deal to send this uid to support for cheating check and got you ban. You need secure this info if you use cheats.)

**Comment by G1DE30N** [comment]
Another observation - Ui screwed if you changed things in esp (types to render) and if you changed item types in interactive map.

**Comment by cip300** [comment]
As [G1DE30N](https://github.com/G1DE30N) say , the interactive map seams the culprit , everytime i swich worlds the UI mismach in crafting menu also this : [https://ibb.co/ncFs6GF](url)

**Comment by G1DE30N** [comment]
irdk what exactly interactive map or esp trigger the bug. But i think both some affect this in some ways. My test lead to the fact - esp itself triggers this bug too. I think anything in cheat what render anything on screen leads to this bug. I tell to Callow recently that I believe that the problem lies not even in the map and not even in the esp. The problem lies in the implementation of the rendering of these cheat functions, that is, most likely it is not the functions themselves that need to be rewritten, but the render itself.

**Comment by cip300** [comment]
[G1DE30N](https://github.com/G1DE30N) I think you are right , the bug reaper after some times , but when i tried to reproduce it , i couldn't ,  i suspected the esp Puzzle filter , but no.

**Comment by G1DE30N** [comment]
> [G1DE30N](https://github.com/G1DE30N) I think you are right , the bug reaper after some times , but when i tried to reproduce it , i couldn't , i suspected the esp Puzzle filter , but no. Edit: I managed to reproduce the bug , when i use Alt+Tab to desktop multiple times or when i stay to long on desktop Alt+Tab to much and come back to ingame. First will misplace the Characters Menu and Inventory and after i go to Enkanomiya from Teyvat for exemple then will ocur ui bug for chat enter ui and craft ui. And it will fix itself if i do again Alt+Tab to desktop and then enter the game.

I know about alt-tabing but for me this not fix the problem everytime. Something about 40/60.

**Comment by tedzify** [comment]
Happened multiple times to me already, it happens when I open the map and then teleport quickly using the cheat.

**Comment by cip300** [comment]
So ... i played over 9 hours in The Chasm and never ocured the ui misplace bug.

**Comment by tedzify** [comment]
It's really hard to replicate 100% of the time because it happens at random.

**Comment by KingRainbow44** [comment]
for me, the UI misplace occurs whenever i teleport into or from scene 3 to scene 5(? not sure but I'm referring to the scene for `The Chasm: Underground Mines`). it never happens when im transitioning from other scenes

**Comment by cip300** [comment]
The UI misplaced was fixed in #112

**Comment by thesadru** [comment]
Woo 🥳

**Comment by Taiga74164** [comment]
This issue should be fixed from the latest commit

**Comment by KingRainbow44** [comment]
someone close it

**Comment by thesadru** [comment]
Now just gotta wait for a release.

**Comment by tedzify** [comment]
Or compile it yourself.

**Comment by thesadru** [comment]
Yeah, obviously that too. I already do.
