### ISSUE TITLE
Need to delete config.json everytime

### ISSUE THREAD

**Issue by Emilia33** [Akebi-Group/Akebi-GC#152]
After updating to latest commit i, i need to delete the config.json to start the game.
if i dont delete the file, i got upload crash everytime

**Comment by CPP-Callow** [comment]
What exactly you're enabling?

**Comment by Emilia33** [comment]
> Would help if you upload the logs and config that crashes, and it would help if you add some more info

the only logs file it generate is upload_err.log, and it say upload_crash release upload:70381
200
file upload finish



> What exactly you're enabling?

i only enable decrease cd and instant bow, and turning it off on exit, its just when i try to log back in.. i got crash everytime

**Comment by CPP-Callow** [comment]
Can you drop one of config files with you got crash?

**Comment by Emilia33** [comment]
> Can you drop one of config files with you got crash?
[akebi.zip](https://github.com/Akebi-Group/Akebi-GC/files/8966528/akebi.zip)
this is the latest config i use after each reset.. also i remove the user id

**Comment by Emilia33** [comment]
fixed by reinstalling all vcredist
