### ISSUE TITLE
`Custom Teleports`  Uncheck "All" crashes game when teleports filtered

### ISSUE THREAD

**Issue by m0nkrel** [Akebi-Group/Akebi-GC#153]
Commit used: c396f3cec348fab6dca6dc1edf447f1fe2f2e3d5
How to reproduce: Filter teleports by letter or word, check "All" then uncheck it

**Comment by Sergiy3013** [comment]
We also noticed this error, if at least one teleport is selected, and you press the refresh button, then an error occurs

**Comment by m0nkrel** [comment]
> 

I tried like you say, but didn't have any errors

**Comment by harlanx** [comment]
> Commit used: [c396f3c](https://github.com/Akebi-Group/Akebi-GC/commit/c396f3cec348fab6dca6dc1edf447f1fe2f2e3d5) How to reproduce: Filter teleports by letter or word, check "All" then uncheck it

Thanks for reporting. My dumbass made final quick changes which breaks it. I should've stayed with the for loop. I'll push a fix soon with additional checks.

**Comment by harlanx** [comment]
> We also noticed this error, if at least one teleport is selected, and you press the refresh button, then an error occurs

can you elaborate the error? I'm also not getting any errors by your description.

**Comment by Sergiy3013** [comment]
Oh, I'm sorry, apparently this was due to an erroneous file in the package. I deleted all the teleportation points, and checked again, now everything is normal.
Instead, may I suggest adding support for categories like in an interactive map? For example like this.

Uncategorized file:
`{
    "name": "Point 1",
    "position": [ 1, 1, 1 ]
}`

File with categories:
`[
    {
        "name": "Point 1",
        "position": [ 1, 1, 1 ]
    },
    {
        "name": "Point 2",
        "position": [ 2, 2, 2 ]
    },
    {
        "name": "Point 3",
        "position": [ 3, 3, 3 ]
    }
]`
