### ISSUE TITLE
Geogranum / Electrogranum / Geo Pressure Plates not working

### ISSUE THREAD

**Issue by HotdogMassacre** [Akebi-Group/Akebi-GC#160]
When you pick up objects that will get placed into something, ie Geogranum into the little torch places, Electrogranum into their equivalent little torch places, Geo Pressure Plates, or even in Inazuma domains that you have to pick up the 3 swirling electro things that slot into the door, these do not function. They can be picked up, or stepped on, but it never activates.

**Comment by Taiga74164** [comment]
okay. what features did you have on when this happened?

**Comment by HotdogMassacre** [comment]
Generally NoClip, Vacuum, God, Autoloot (no treasure, custom range of 18, looting speed of 350). From what i'm hearing from others it may be auto-loot causing it trying to get back to one of those areas to see. I had turned off no-clip and the others that i thought may effect it but didn't see a difference. Though maybe i should have done a client restart as well.

**Comment by Nobzie** [comment]
Have been running with AutoLoot a lot recently and did not have that happen, which leads me to think it could be game or cheat just bugging because of NoClip being turned on and off a lot.

**Comment by tedzify** [comment]
Perhaps a bug with `Alternate Godmode`?

**Comment by Taiga74164** [comment]
just tried replicating the issue with NoClip, Vacuum, Alt GodMode and the puzzle still worked.. could you perhaps record a video ?

**Comment by HotdogMassacre** [comment]
I'll do that if it bugs out again, it seems to be working fine as of the last week. Will let you know if it goes belly up again.
