### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by genikTOP** [Akebi-Group/Akebi-GC#162]
Please fix the following errors: 
1) When using teleport on chests (5+ times in a row), the game crashes. 
2) When using the cheat for a long time, the game interface (buttons and windows) are shifted to the left side or to the upper left corner. 3) Sometimes, when the statue of the archons is raised, the game freezes in the window with the offerings of the oculi (you can turn on the noclip and move, but after disconnecting and turning on the character no longer moves). (Used the function of fast-forward dialogues and clips).

**Comment by Lunairayz** [comment]
1 and 3 never happen for me
2 is a known issue

**Comment by CallowBlack** [comment]
Please create 1 issue for 1 bug.
