### ISSUE TITLE
make uid & nickname hider (change on fake uid || nickname).

### ISSUE THREAD

**Issue by decausedinside** [Akebi-Group/Akebi-GC#163]

**Comment by NctimeAza** [comment]
You just need to build from source,the latest build includes the feature

**Comment by jcatrdev** [comment]
Isn't this feature already implemented? Check the latest build

**Comment by m0nkrel** [comment]
already from 50d1cec7f09bf283d043c5e2bc60e5eb6d64ccfa commit
