### ISSUE TITLE
Banned 1m

### ISSUE THREAD

**Issue by Demnlight** [Akebi-Group/Akebi-GC#165]
logs blocked
C:\Windows\System32\drivers\etc\hosts
`
0.0.0.0 log-upload-os.mihoyo.com
0.0.0.0 log-upload.mihoyo.com
0.0.0.0 devlog-upload.mihoyo.com
`
 crash reporter blocked.
 `C:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact_Data\upload_crash.exe`
 file:
[cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/8968048/cfg.txt)
raw:
`
{
    "current_profile": "default",
    "profiles": {
        "default": {
            "AutoCook": {
                "QualityField": 3
            },
            "AutoDestroy": {
                "DestroyOres": {
                    "toggled": true,
                    "value": null
                },
                "Enabled": {
                    "toggled": true,
                    "value": null
                },
                "Range": 5.0
            },
            "AutoLoot": {
                "AutoPickup": {
                    "toggled": true,
                    "value": null
                },
                "AutoTreasure": {
                    "toggled": true,
                    "value": null
                },
                "Chest": true,
                "DelayTime": 241,
                "Investigate": true
            },
            "AutoTalk": {
                "CutsceneUSM": {
                    "toggled": true,
                    "value": null
                },
                "Enabled": {
                    "toggled": true,
                    "value": null
                },
                "FastDialog": {
                    "toggled": true,
                    "value": null
                },
                "TimeSpeedup": 4.0
            },
            "AutoTreeFarm": {
                "AttackDelay": 231,
                "Range": 10.0
            },
            "Damage mode": {
                "DamageMode": {
                    "toggled": true,
                    "value": null
                }
            },
            "ESP": {
                "DrawDistance": true,
                "DrawName": true,
                "Enabled": {
                    "toggled": true,
                    "value": null
                },
                "Filters": {
                    "Chest": {
                        "Common Chest": {
                            "color": 4292861919,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Exquisite Chest": {
                            "color": 4278255425,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Luxurious Chest": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Precious Chest": {
                            "color": 4293819126,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Search Point": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        }
                    },
                    "Collection": {
                        "Quest Interact": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        }
                    },
                    "Featured": {
                        "Anemoculus": {
                            "color": 4292607744,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Crimson Agate": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Electroculus": {
                            "color": 4294932149,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Geoculus": {
                            "color": 4278255586,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Lumenspar": {
                            "color": 4294966931,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Time Trial Challenge": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        }
                    },
                    "Guide": {
                        "Campfire Torch": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        }
                    },
                    "Living": {
                        "Starconch": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        }
                    },
                    "Mineral": {
                        "Scarlet Quartz": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "White Iron Chunk": {
                            "color": 4286085240,
                            "enabled": true,
                            "hotkey": null
                        }
                    },
                    "Monster": {
                        "Abyss Mage": {
                            "color": 4294932327,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Fatui Agent": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Ruin Guard": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Ruin Hunter": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Ruin Sentinel": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Shadowy Husk": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Whopperflower": {
                            "color": 4280811264,
                            "enabled": false,
                            "hotkey": null
                        }
                    },
                    "Plant": {
                        "Mist Flower Corolla": {
                            "color": 4294919936,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Naku Weed": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Philanemo Mushroom": {
                            "color": 4286085240,
                            "enabled": true,
                            "hotkey": null
                        },
                        "Silk Flower": {
                            "color": 4278190335,
                            "enabled": true,
                            "hotkey": null
                        }
                    },
                    "Puzzle": {
                        "Bloatty Floatty": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Cube Devices": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Electro Seelie": {
                            "color": 4294937267,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Elemental Monument": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Floating Anemo Slime": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Luminous Seelie": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Pressure Plate": {
                            "color": 4289309183,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Relay Stone": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Seelie": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Torch Puzzle": {
                            "color": 4278255605,
                            "enabled": false,
                            "hotkey": null
                        },
                        "Warming Seelie": {
                            "color": 4278190335,
                            "enabled": false,
                            "hotkey": null
                        }
                    }
                },
                "FontSize": 26,
                "MinSize": 0.10000000149011612,
                "Range": 200.0
            },
            "General": {
                "SelectedSection": 3
            },
            "InfiniteStamina": {
                "Enabled": {
                    "toggled": true,
                    "value": null
                },
                "PacketReplacement": true
            },
            "InteractMap": {
                "ObjectCheckOnlyShowed": false
            },
            "InteractiveMap": {
                "CheckObjectsDelay": 930,
                "CompletePointTransparency": 0.1899999976158142,
                "Filters": {
                    "Scene3": {
                        "InazumaShrineofDepths": true,
                        "Liyue": true
                    },
                    "Scene6": {
                        "Lumenspar": true
                    }
                },
                "GatheredItemsDetectRange": 30.0,
                "IconSize": 54.79999923706055,
                "MinimapIconSize": 37.09000015258789,
                "ObjectDetectRange": 30.0,
                "ShowCompleted": true,
                "ShowHDIcons": true,
                "m_InteractiveMap": {
                    "toggled": true,
                    "value": null
                }
            },
            "KillAura": {
                "Enabled": {
                    "toggled": true,
                    "value": null
                }
            },
            "MapTeleport": {
                "Enabled": {
                    "toggled": true,
                    "value": null
                }
            },
            "NoCD": {
                "AbilityReduce": {
                    "toggled": true,
                    "value": null
                },
                "Sprint": {
                    "toggled": true,
                    "value": null
                },
                "UtimateMaxEnergy": {
                    "toggled": true,
                    "value": null
                }
            },
            "NoClip": {
                "AltSpeed": 20.899999618530273,
                "AltSpeedEnabled": true,
                "Enabled": {
                    "toggled": false,
                    "value": 88
                },
                "Speed": 13.800000190734863
            },
            "Visuals": {
                "FPSUnlocker": {
                    "Enabled": true
                },
                "NoFog": {
                    "toggled": true,
                    "value": null
                }
            }
        }
    },
    "shared": {
        "InteractiveMap": {
            "CustomPointIndex": 1004854
        },
        "PatternScanner": {
            "m_CheckSumTimestamp": {
                "UnityPlayer.dll": 132967628640000000,
                "UserAssembly.dll": 132967628640000000
            }
        }
    }
}
`

**Comment by Fanixtar** [comment]
your host is outdated, it's now hoyoverse
