### ISSUE TITLE
Game suddenly crush 

### ISSUE THREAD

**Issue by Badsha71** [Akebi-Group/Akebi-GC#166]
check my ss and log file 
![Screenshot (385)](https://user-images.githubusercontent.com/57755184/175325393-2537f899-2053-4b5f-aad8-061478c31345.png)

[log_2022-05-23_06-05.txt](https://github.com/Akebi-Group/Akebi-GC/files/8968218/log_2022-05-23_06-05.txt)

**Comment by harlanx** [comment]
Can I ask what were you doing before it crashed? Map Teleport and Custom Teleport uses the same method for teleporting, which one you were using?

**Comment by Badsha71** [comment]
> Can I ask what were you doing before it crashed? Map Teleport and Custom Teleport uses the same method for teleporting, which one you were using?

I just doing some quest and killing enemy,teleporting and then fight with the enemy all of a sudden it crush and totally stop from task manager,it happen after playing 5hour+

**Comment by harlanx** [comment]
You've opened something similar before in #136 . I've experience random crash before even when AFK and everything's disabled so It's hard to pinpoint the issue.

**Comment by Badsha71** [comment]
that was happing when i am fighting with slime and it crush but now i am doing nothing like that it crush on of a sudden
