### ISSUE TITLE
Looking to add automatic pickup and classified pickup (not range pickup is dangerous)

### ISSUE THREAD

**Issue by kevinkong1999** [Akebi-Group/Akebi-GC#17]
I'm not good at English.  .  .  Don't be offended.  .  i am a malaysian

Can new tools be added?  Add automatic pickup (automatically enter the school bag) and pickup categories (such as magical powers, I only want to pick up food, but do not want to take magical powers and treasure chests. If both are turned off, it will not be picked up automatically. Only food will be picked up, no  Automatically pick up magical powers and treasure chests) Picking up within the range will have a certain risk of being banned.  The picture below was secretly shared by my Chinese friend to a Malaysian, and I don't have any more pictures.

![1652996586685](https://user-images.githubusercontent.com/101958260/169411969-250d7b93-d28e-47fe-aafb-c2a78ef8f0d3.png)

![mmexport1652997476329](https://user-images.githubusercontent.com/101958260/169412011-3892473b-6324-4bd9-96c9-1434f1f87357.jpg)

![mmexport1652997478654](https://user-images.githubusercontent.com/101958260/169412047-0f6234e0-e342-4b99-9b88-5f0379064e85.jpg)

![mmexport1652997474337](https://user-images.githubusercontent.com/101958260/169412079-64529e44-1b6d-46c0-8ee1-574eb1d7a2c0.jpg)

![mmexport1652997480899](https://user-images.githubusercontent.com/101958260/169413210-b5de1e3c-f5ea-42fb-a826-59ec7b327c19.jpg)

![mmexport1652997486995](https://user-images.githubusercontent.com/101958260/169413228-361d4630-94a0-4031-9558-4c8520d8917d.jpg)

**Comment by Shichiha** [comment]
Auto pickup is already in the list of features

**Comment by kevinkong1999** [comment]
> Auto pickup is already in the list of features

But that's automatic, not counting

**Comment by CallowBlack** [comment]
Do you want us to add filters for pickup items?

**Comment by kevinkong1999** [comment]
> Do you want us to add filters for pickup items?

Yes, there is hope to be able to stealth uid

https://user-images.githubusercontent.com/101958260/169417020-c6d85d3a-239e-448c-83c2-e3bc2e657e15.mp4

![Screenshot_2022-05-20-06-50-08-673_tv danmaku bili](https://user-images.githubusercontent.com/101958260/169417063-ee6f944a-2f35-4e22-bfd7-793f6b04855e.jpg)

This is shared to me by Chinese friends

**Comment by kevinkong1999** [comment]
> > Do you want us to add filters for pickup items?
> 
> Yes, there is hope to be able to stealth uid
> 
>  Screenrecorder-2022-05-20-06-49-56-143.mp4 
> ![Screenshot_2022-05-20-06-50-08-673_tv danmaku bili](https://user-images.githubusercontent.com/101958260/169417063-ee6f944a-2f35-4e22-bfd7-793f6b04855e.jpg)
> 
> This is shared to me by Chinese friends



> > Do you want us to add filters for pickup items?
> 
> Yes, there is hope to be able to stealth uid
> 
>  Screenrecorder-2022-05-20-06-49-56-143.mp4 

>This figure hides the uid

> ![Screenshot_2022-05-20-06-50-08-673_tv danmaku bili](https://user-images.githubusercontent.com/101958260/169417063-ee6f944a-2f35-4e22-bfd7-793f6b04855e.jpg)
> 
> This is shared to me by Chinese friends

**Comment by kevinkong1999** [comment]
> Do you want us to add filters for pickup items?

Yes, automatic pickup is safer than range pickup

https://user-images.githubusercontent.com/101958260/169417475-b02400a6-e1dd-4502-973c-593df3784d96.mp4

It is also hoped that the uid hiding function can be added

![Screenshot_2022-05-20-06-50-08-673_tv danmaku bili](https://user-images.githubusercontent.com/101958260/169417813-305c3f25-b4f8-4f53-8c56-17182a0b55bd.jpg)

**Comment by kevinkong1999** [comment]
These are shared by my international friends

**Comment by kevinkong1999** [comment]
>

> Do you want us to add filters for pickup items?

Yes, automatic pickup is safer than range pickup

The video is here..（https://mega.nz/file/do4wlRLI#KXH7qTyUYs1VeUve3JX9KQfbkg24rEtos3-vbe32zas）


It is also hoped that the uid hiding function can be added

![Screenshot_2022-05-20-06-50-08-673_tv danmaku bili](https://user-images.githubusercontent.com/101958260/169418512-8cd58abb-df2a-407e-9de4-f65d878ce650.jpg)

**Comment by kevinkong1999** [comment]
> Do you want us to add filters for pickup items?

I asked about the original video 

https://b23.tv/YOVqGJZ

**Comment by kevinkong1999** [comment]
> Auto pickup is already in the list of features

That's range picking. It's not safe... My friend has been driving automatic pickup for 5 months...... Unsealed account number

**Comment by kevinkong1999** [comment]
> Auto pickup is already in the list of features

That's a range pickup, not safe.  .  .  My friend has opened automatic pickup for 5 months, and the account has not been closed.

**Comment by Shichiha** [comment]
You can use automatic pickup without the range

**Comment by kevinkong1999** [comment]
> You can use automatic pickup without the range

watch this video https://mega.nz/file/do4wlRLI#KXH7qTyUYs1VeUve3JX9KQfbkg24rEtos3-vbe32zas

**Comment by kevinkong1999** [comment]
> You can use automatic pickup without the range



> You can use automatic pickup without the range

Figure 1 is automatic picking, Figure 2 is range picking
![mmexport1653003148721](https://user-images.githubusercontent.com/101958260/169420757-7cdeee07-cbb1-426b-ac91-0917263f780d.jpg)

**Comment by Fanixtar** [comment]
#148
