### ISSUE TITLE
Could not generate solution

### ISSUE THREAD

**Issue by xiao-Roly** [Akebi-Group/Akebi-GC#175]
Build started...
1>------ Build started: Project: cheat-base, Configuration: Release x64 ------
1>pch.cpp
1>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(560,5): error MSB6006: "CL.exe" exited with code 2.
1>D:\Agc\Akebi-GC-master\cheat-base\framework\pch.h(13,10): fatal error C1083: Cannot open include file: 'magic_enum.hpp': No such file or directory
1>Done building project "cheat-base.vcxproj" -- FAILED.
2>------ Build started: Project: injector, Configuration: Release x64 ------
2>injector.cpp
2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
2>main.cpp
2>D:\Agc\Akebi-GC-master\injector\src\main.cpp(6,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
2>util.cpp
2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
2>Done building project "injector.vcxproj" -- FAILED.
3>------ Build started: Project: cheat-library, Configuration: Release x64 ------
3>pch-il2cpp.cpp
3>D:\Agc\Akebi-GC-master\cheat-library\src\framework\pch-il2cpp.h(13,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
3>Done building project "cheat-library.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========

**Comment by m0nkrel** [comment]
Use english, please.


- Clone repository with '''git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git'''
- Open '''Akebi-GC/akebi-gc.sln'''
- Build solution '''akebi-gc.sln'''

**Comment by xiao-Roly** [comment]
> Use english, please.
> 
> * Clone repository with `git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git`
> * Open `Akebi-GC/akebi-gc.sln`
> * Build solution `akebi-gc.sln `

Build started...
1>------ Build started: Project: cheat-base, Configuration: Release x64 ------
1>pch.cpp
1>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(560,5): error MSB6006: "CL.exe" exited with code 2.
1>D:\Agc\Akebi-GC-master\cheat-base\framework\pch.h(13,10): fatal error C1083: Cannot open include file: 'magic_enum.hpp': No such file or directory
1>Done building project "cheat-base.vcxproj" -- FAILED.
2>------ Build started: Project: injector, Configuration: Release x64 ------
2>injector.cpp
2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
2>main.cpp
2>D:\Agc\Akebi-GC-master\injector\src\main.cpp(6,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
2>util.cpp
2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
2>Done building project "injector.vcxproj" -- FAILED.
3>------ Build started: Project: cheat-library, Configuration: Release x64 ------
3>pch-il2cpp.cpp
3>D:\Agc\Akebi-GC-master\cheat-library\src\framework\pch-il2cpp.h(13,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
3>Done building project "cheat-library.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========

**Comment by Zatix-rus** [comment]
I have the same thing

**Comment by Taiga74164** [comment]
> > Use english, please.
> > 
> > * Clone repository with `git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git`
> > * Open `Akebi-GC/akebi-gc.sln`
> > * Build solution `akebi-gc.sln `
> 
> Build started...
> 1>------ Build started: Project: cheat-base, Configuration: Release x64 ------
> 1>pch.cpp
> 1>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(560,5): error MSB6006: "CL.exe" exited with code 2.
> 1>D:\Agc\Akebi-GC-master\cheat-base\framework\pch.h(13,10): fatal error C1083: Cannot open include file: 'magic_enum.hpp': No such file or directory
> 1>Done building project "cheat-base.vcxproj" -- FAILED.
> 2>------ Build started: Project: injector, Configuration: Release x64 ------
> 2>injector.cpp
> 2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
> 2>main.cpp
> 2>D:\Agc\Akebi-GC-master\injector\src\main.cpp(6,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
> 2>util.cpp
> 2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
> 2>Done building project "injector.vcxproj" -- FAILED.
> 3>------ Build started: Project: cheat-library, Configuration: Release x64 ------
> 3>pch-il2cpp.cpp
> 3>D:\Agc\Akebi-GC-master\cheat-library\src\framework\pch-il2cpp.h(13,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
> 3>Done building project "cheat-library.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========
> 

like @m0nkrel says, ``git clone --recurse-submodules``

**Comment by xiao-Roly** [comment]
> > > Use english, please.
> > > 
> > > * Clone repository with `git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git`
> > > * Open `Akebi-GC/akebi-gc.sln`
> > > * Build solution `akebi-gc.sln `
> > 
> > 
> > Build started...
> > 1>------ Build started: Project: cheat-base, Configuration: Release x64 ------
> > 1>pch.cpp
> > 1>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(560,5): error MSB6006: "CL.exe" exited with code 2.
> > 1>D:\Agc\Akebi-GC-master\cheat-base\framework\pch.h(13,10): fatal error C1083: Cannot open include file: 'magic_enum.hpp': No such file or directory
> > 1>Done building project "cheat-base.vcxproj" -- FAILED.
> > 2>------ Build started: Project: injector, Configuration: Release x64 ------
> > 2>injector.cpp
> > 2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
> > 2>main.cpp
> > 2>D:\Agc\Akebi-GC-master\injector\src\main.cpp(6,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
> > 2>util.cpp
> > 2>D:\Agc\Akebi-GC-master\cheat-base\src\cheat-base\util.h(9,10): fatal error C1083: Cannot open include file: 'SimpleIni.h': No such file or directory
> > 2>Done building project "injector.vcxproj" -- FAILED.
> > 3>------ Build started: Project: cheat-library, Configuration: Release x64 ------
> > 3>pch-il2cpp.cpp
> > 3>D:\Agc\Akebi-GC-master\cheat-library\src\framework\pch-il2cpp.h(13,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
> > 3>Done building project "cheat-library.vcxproj" -- FAILED.
> > ========== Build: 0 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========
> 
> like @m0nkrel says, `git clone --recurse-submodules`

`Administrator@SK-20211115AURH MINGW64 ~/Desktop/1
$ git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git
Cloning into 'Akebi-GC'...
remote: Enumerating objects: 2032, done.
remote: Counting objects: 100% (470/470), done.
remote: Compressing objects: 100% (247/247), done.
remote: Total 2032 (delta 262), reused 403 (delta 217), pack-reused 1562
Receiving objects: 100% (2032/2032), 34.83 MiB | 4.92 MiB/s, done.
Resolving deltas: 100% (740/740), done.
Submodule 'cheat-base/vendor/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'cheat-base/vendor/fmt'
Submodule 'cheat-base/vendor/imgui' (https://github.com/CallowBlack/imgui-brightness-fix.git) registered for path 'cheat-base/vendor/imgui'
Submodule 'cheat-library/vendor/json' (https://github.com/nlohmann/json.git) registered for path 'cheat-base/vendor/json'
Submodule 'cheat-base/vendor/magic_enum' (https://github.com/Neargye/magic_enum.git) registered for path 'cheat-base/vendor/magic_enum'
Submodule 'cheat-base/vendor/simpleIni' (https://github.com/brofield/simpleini.git) registered for path 'cheat-base/vendor/simpleIni'
Submodule 'cheat-base/vendor/stb' (https://github.com/nothings/stb.git) registered for path 'cheat-base/vendor/stb'
Cloning into 'C:/Users/Administrator/Desktop/1/Akebi-GC/cheat-base/vendor/fmt'...
fatal: unable to access 'https://github.com/fmtlib/fmt.git/': OpenSSL SSL_read: Connection was reset, errno 10054
fatal: clone of 'https://github.com/fmtlib/fmt.git' into submodule path 'C:/Users/Administrator/Desktop/1/Akebi-GC/cheat-base/vendor/fmt' failed
Failed to clone 'cheat-base/vendor/fmt'. Retry scheduled
Cloning into 'C:/Users/Administrator/Desktop/1/Akebi-GC/cheat-base/vendor/imgui'...
fatal: unable to access 'https://github.com/CallowBlack/imgui-brightness-fix.git/': Failed to connect to github.com port 443 after 21090 ms: Timed out
fatal: clone of 'https://github.com/CallowBlack/imgui-brightness-fix.git' into submodule path 'C:/Users/Administrator/Desktop/1/Akebi-GC/cheat-base/vendor/imgui' failed
Failed to clone 'cheat-base/vendor/imgui'. Retry scheduled
Cloning into 'C:/Users/Administrator/Desktop/1/Akebi-GC/cheat-base/vendor/json'...

Administrator@SK-20211115AURH MINGW64 ~/Desktop/1
$
`

**Comment by harlanx** [comment]
> 

I was also having the same issue where it was failing to download some submodules before. I suggest you to use cloudflare warp before you clone the repo again.

**Comment by xiao-Roly** [comment]
> > 
> 
> I was also having the same issue where it was failing to download some submodules before. I suggest you to use cloudflare warp before you clone the repo again.

I tried to manually download the submodule to the corresponding directory, but still can't solve the problem
`Build started...
1>------ Build started: Project: cheat-base, Configuration: Release x64 ------
1>pch.cpp
1>C:\Users\Administrator\Desktop\1\Akebi-GC\cheat-base\framework\pch.h(13,10): fatal error C1083: Cannot open include file: 'magic_enum.hpp': No such file or directory
1>Done building project "cheat-base.vcxproj" -- FAILED.
2>------ Build started: Project: injector, Configuration: Release x64 ------
2>D:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(1092,5): error MSB6006: "link.exe" exited with code 1181.
2>LINK : fatal error LNK1181: cannot open input file 'cheat-base.lib'
2>Done building project "injector.vcxproj" -- FAILED.
3>------ Build started: Project: cheat-library, Configuration: Release x64 ------
3>pch-il2cpp.cpp
3>C:\Users\Administrator\Desktop\1\Akebi-GC\cheat-library\src\framework\pch-il2cpp.h(13,10): fatal error C1083: Cannot open include file: 'nlohmann/json.hpp': No such file or directory
3>Done building project "cheat-library.vcxproj" -- FAILED.
========== Build: 0 succeeded, 3 failed, 0 up-to-date, 0 skipped ==========`

**Comment by xiao-Roly** [comment]
the issue has been resolved
