### ISSUE TITLE
Whether multiple languages can be adapted

### ISSUE THREAD

**Issue by daofeng2015** [Akebi-Group/Akebi-GC#177]
Can you support multiple languages? Different languages can be selected during imGUI initialization

**Comment by tayhm0817** [comment]
actually can get cn language from taobao

**Comment by Taiga74164** [comment]
> actually can get cn language from taobao

what? theyre selling it?

**Comment by tayhm0817** [comment]
> > actually can get cn language from taobao
> 
> what? theyre selling it?

yep lots of it

**Comment by Taiga74164** [comment]
🤣

**Comment by keexers** [comment]
> > > actually can get cn language from taobao
> > 
> > 
> > what? theyre selling it?
> 
> yep lots of it

https://deepl.com exists
