### ISSUE TITLE
Profile Changer UID Display Mistake

### ISSUE THREAD

**Issue by itsyourap** [Akebi-Group/Akebi-GC#178]
Changing UID via Profile Changer should display ```UID: 6969696969``` at the bottom right corner but it displays only ```6969696969```.

**Problem :-**
![6969696969](https://user-images.githubusercontent.com/90060131/175998563-79210ca5-a323-43b5-ba5e-72106061bea1.png)

**Should Be :-** 
![UID: 6969696969](https://user-images.githubusercontent.com/90060131/175998431-30c7b33b-d75e-4aa9-93d8-bda818dd3fa6.png)

**Comment by m0nkrel** [comment]
just add ```UID:```💀

**Comment by itsyourap** [comment]
> just add `UID:`💀

Adding `UID:` will show `UID: 69696969` in the nav profile menu after `UID`. Seems weird.

![dont send anything](https://user-images.githubusercontent.com/90060131/176001384-75b245ca-a2df-4028-8263-1bea415ed91d.png)

**Comment by keexers** [comment]
ARE YOU HAVE NO BRAIN? THATS WHY UR GAY AND A TRANNY

**Comment by chirinu** [comment]
Bruh

**Comment by itsyourap** [comment]
> ARE YOU HAVE NO BRAIN? THATS WHY UR GAY AND A TRANNY

I see that you think that "having no brain = gay and tranny". How did you actually know that? Maybe you are.

**Comment by keexers** [comment]
@itsyourap "I see that you think that "having no brain = gay and tranny". How did you actually know that? Maybe you are."

well i was drunk while reading the "issue", if i was a faggot i wouldnt say "gay and tranny" to other faggots 🥰🥰🥰🥰🥰🥰

**Comment by itsyourap** [comment]
> @itsyourap "I see that you think that "having no brain = gay and tranny". How did you actually know that? Maybe you are."
> 
> well i was drunk while commenting, if i was a faggot i wouldnt say "gay and tranny" to other faggots 🥰🥰🥰🥰🥰🥰

I see! So you are a faggot!

**Comment by keexers** [comment]
> > @itsyourap "I see that you think that "having no brain = gay and tranny". How did you actually know that? Maybe you are."
> > well i was drunk while commenting, if i was a faggot i wouldnt say "gay and tranny" to other faggots 🥰🥰🥰🥰🥰🥰
> 
> @keexers I see! So you are a faggot!

are you fucking retarded mister? 🥰🥰🥰 i was drunk didnt you read?

**Comment by keexers** [comment]
> > are you fucking retarded mister? 🥰🥰🥰 i was drunk didnt you read?
> 
> @keexers You said
> 
> > if i was a faggot i wouldnt say "gay and tranny" to other faggots
> 
> But you said this to someone who is not a faggot! So you are a faggot according to your saying!

you are a faggot tho? what the fuck are you saying

**Comment by itsyourap** [comment]
> > > are you fucking retarded mister? 🥰🥰🥰 i was drunk didnt you read?
> > 
> > 
> > @keexers You said
> > > if i was a faggot i wouldnt say "gay and tranny" to other faggots
> > 
> > 
> > But you said this to someone who is not a faggot! So you are a faggot according to your saying!
> 
> you are a faggot tho? what the fuck are you saying

Nope! I ain't a faggot! Can we stop this now? You were drunk and I am getting the hangover now

**Comment by keexers** [comment]
> > > > are you fucking retarded mister? 🥰🥰🥰 i was drunk didnt you read?
> > > 
> > > 
> > > @keexers You said
> > > > if i was a faggot i wouldnt say "gay and tranny" to other faggots
> > > 
> > > 
> > > But you said this to someone who is not a faggot! So you are a faggot according to your saying!
> > 
> > 
> > you are a faggot tho? what the fuck are you saying
> 
> Nope! I ain't a faggot! Can we stop this now? You were drunk and I am getting the hangover now

calling me a faggot while youre a faggot too????????? yes i know i was drunk and shit and since you said to stop this sure mr faggot

**Comment by keexers** [comment]
> best not to argue in the issues.... 😓

yea no shit drinking wasnt the best idea either

**Comment by Screenatyouruse** [comment]
2 liters of orange juice and ill fix it

**Comment by RyujinZX** [comment]
> 2 liters of orange juice and ill fix it

2 bottles of beer actually!

**Comment by Screenatyouruse** [comment]
> > 2 liters of orange juice and ill fix it
> 
> 2 bottles of beer actually!

how about both at the same time!!!!
