### ISSUE TITLE
Hope to add UID hiding function

### ISSUE THREAD

**Issue by kevinkong1999** [Akebi-Group/Akebi-GC#18]
Hope to add UID hiding function

![Screenshot_2022-05-20-06-50-08-673_tv danmaku bili](https://user-images.githubusercontent.com/101958260/169422010-21ee33be-c7ba-40b9-a663-ba6920fb07ce.jpg)

Shared by international friends

**Comment by Taiga74164** [comment]
planning on adding this soon

**Comment by G1DE30N** [comment]
I have one stupid question. Why?

**Comment by kevinkong1999** [comment]
> I have one stupid question. Why?

No UID will appear when you screenshot/live.  .  .  😅 When you share, you don't need to modify the picture, etc.

**Comment by G1DE30N** [comment]
Maybe I'm being picky, of course, but for me, in order not to get burned on cheats, it's enough just not to do things like photo or video fixing of the game. After all, why introduce this at the cheat level if there is such a thing as post-processing?

**Comment by kevinkong1999** [comment]
> Maybe I'm being picky, of course, but for me, in order not to get catched on cheats, it's enough just not to do things like photo or video fixing of the game. After all, why introduce this at the cheat level if there is such a thing as post-processing? Like you can just cover up the uid and that's it. Like if that uid is not the only way to discredit the account on the video.

😂

**Comment by G1DE30N** [comment]
Well, like it seems to me that playing with cheats and shining it is a bit childish or something 😂

**Comment by kevinkong1999** [comment]
> Well, like it seems to me that playing with cheats and show it is a bit childish or something 😂 Moreover, as far as I know from the experience of many other cheats in other games, the more a cheat spreads over the Internet in the form of media, the more it attracts the attention of developers and the faster it is fixed by new anticheat meashures or simply DMCA or other Striking. Not good. DMCA on previous repo is the proof of that concept.

I'm just suggesting😂

**Comment by G1DE30N** [comment]
I don't mind if Callow wants to, let him add. It just seems to me that this is a slightly dubious function ))))0

**Comment by kevinkong1999** [comment]
> 



> I don't mind if Callow wants to, let him add. It just seems to me that this is a slightly dubious function ))))0

Yeah?😅

**Comment by G1DE30N** [comment]
Don't be offended) It's just my opinion)

**Comment by kevinkong1999** [comment]
> 不要被冒犯）这只是我的意见）



> Don't be offended) It's just my opinion)

😂 It's okay, we're just talking，I am using translation.  .  .  There may be a typo 😂

**Comment by kevinkong1999** [comment]
> Don't be offended) It's just my opinion)

😂 It's okay, we're just talking。。。。I am using translation.  .  .  There may be a typo 😂

**Comment by Legend-Recalls** [comment]
> Don't be offended) It's just my opinion)

well well then tell me why does non range auto pickup is there since it bans in like 5 minutes. sometimes we just like to have it rather than use it. yk hide uid is very much helpful in screenshares just in case they start to troll

**Comment by G1DE30N** [comment]
> > Don't be offended) It's just my opinion)
> 
> well well then tell me why does non range auto pickup is there since it bans in like 5 minutes. sometimes we just like to have it rather than use it. yk hide uid is very much helpful in screenshares just in case they start to troll

I explained above why screensharing is terrible idea. If you mean screensharing here, just crop it, don't be such lazy :D

**Comment by Legend-Recalls** [comment]
> > > Don't be offended) It's just my opinion)
> > 
> > 
> > well well then tell me why does non range auto pickup is there since it bans in like 5 minutes. sometimes we just like to have it rather than use it. yk hide uid is very much helpful in screenshares just in case they start to troll
> 
> I explained above why screensharing is terrible idea. If you mean screensharing here, just crop it, don't be such lazy :D

i mean not screenshot but share like those discord ones or zoom ones ik sounds weird but sometimes have  to call guys to help with puzzles

**Comment by G1DE30N** [comment]
Thats okay. But for example stream cheat gameplay or something like that is not good.

**Comment by monado1110** [comment]
> > I have one stupid question. Why?
> 
> No UID will appear when you screenshot/live. . . 😅 When you share, you don't need to modify the picture, etc.

if you use cheats while livestreaming you deserve the ban

**Comment by keexers** [comment]
> Well, like it seems to me that playing with cheats and show it is a bit childish or something 😂 Moreover, as far as I know from the experience of many other cheats in other games, the more a cheat spreads over the Internet in the form of media, the more it attracts the attention of developers and the faster it is fixed by new anticheat meashures or simply DMCA or other Striking. Not good. DMCA on previous repo is the proof of that concept.

meh, people took cheating seriously on other games except for genshin or any rpg games. most toxic and serious cheating communities ive ever seen are minecraft and roblox. and only genshin (from my opinion) only dmcas anything thats related to genshin. for the minecraft and roblox ones the game companies dont know it, as far as i know these community likes to dmca each other or crack cheats 😂 (sorry for the bad english, im not used to speaking it)

**Comment by keexers** [comment]
> > > I have one stupid question. Why?
> > 
> > 
> > No UID will appear when you screenshot/live. . . 😅 When you share, you don't need to modify the picture, etc.
> 
> if you use cheats while livestreaming you deserve the ban

closet cheaters sweating rn

**Comment by Taiga74164** [comment]
#99

**Comment by Taiga74164** [comment]
Added
