### ISSUE TITLE
UI offset and infinite stamina bug

### ISSUE THREAD

**Issue by SunnySissi** [Akebi-Group/Akebi-GC#183]
1.Some UI will offset sometimes,I must restart all game to figure it out.
2.Sometimes after using teleport feature the player stamina will use up.

**Comment by LEMON4D3** [comment]
Yep and the infinite stamina cause the player can't sprint

**Comment by tedzify** [comment]
> 1.Some UI will offset sometimes,I must restart all game to figure it out. 2.Sometimes after using teleport feature the player stamina will use up.

1. Are you using the latest commit [fc657f1](https://github.com/Akebi-Group/Akebi-GC/commit/fc657f144c88a0865a6a740975cad2dfc5c2f537)](https://github.com/Akebi-Group/Akebi-GC/commit/fc657f144c88a0865a6a740975cad2dfc5c2f537) (not the release version)
2. Inf. stamina is buggy, so use it with `Move Sync Packet Replacement`. Not a solution but an alternative.

**Comment by SunnySissi** [comment]
> > 1.Some UI will offset sometimes,I must restart all game to figure it out. 2.Sometimes after using teleport feature the player stamina will use up.
> 
> 1. Are you using the latest commit [[fc657f1](https://github.com/Akebi-Group/Akebi-GC/commit/fc657f144c88a0865a6a740975cad2dfc5c2f537)] (not the release version)
> 2. Inf. stamina is buggy, so use it with . Not a solution but an alternative.`Move Sync Packet Replacement`

release version(I was uesing before) and lastest version(I am using now) all have the UI offset issue.

**Comment by SunnySissi** [comment]
[cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9015980/cfg.txt)

**Comment by ATF-zero** [comment]
> [cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9015980/cfg.txt)

Just a suggestion, you can delete your uid and name when sharing cfg file

**Comment by Taiga74164** [comment]
Both this issue should be solved if you build the source
