### ISSUE TITLE
can anyone analyse the cfg to find out the ban cause

### ISSUE THREAD

**Issue by SunnySissi** [Akebi-Group/Akebi-GC#188]
[cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9017114/cfg.txt)

**Comment by Taiga74164** [comment]
Auto Loot

**Comment by xuewuji** [comment]
Auto Cheast

**Comment by SunnySissi** [comment]
> A level 38 account, but passed 12-3, This is the most likely possibility of banning you

but 12-3 was completed in level 25(maybe),i think banned cause mostly is something about Fragile Resin.

**Comment by keexers** [comment]
> > > A level 38 account, but passed 12-3, This is the most likely possibility of banning you
> > 
> > 
> > but 12-3 was completed in level 25(maybe),i think banned cause mostly is something about Fragile Resin.
> 
> Acquiring a large amount of resources in a short period of time may also be one of the reasons, But it is impossible to complete 12-3 with full stars without cheating, and if you are reported, you will definitely be banned

it IS possible to complete the whole spiral abyss if your characters are good enough. just impossible for low ars. and the rest are true though

**Comment by ATF-zero** [comment]
> 

What you said is exactly what I missed

**Comment by SunnySissi** [comment]
Okay, I'll pay more attention next time.
BTW,i never play with anyone online,i just play with myself.Would anyone report me even that？

**Comment by keexers** [comment]
> Okay, I'll pay more attention next time. BTW,i never play with anyone online,i just play with myself.Would anyone report me even that？

yes if anyone finds it suspicious if you beat the whole abyss :kek:

**Comment by SunnySissi** [comment]
learn from mistakes
