### ISSUE TITLE
Can't open the UI

### ISSUE THREAD

**Issue by KhangPhc** [Akebi-Group/Akebi-GC#189]
![image](https://user-images.githubusercontent.com/108499861/176801519-b87390a3-cbfd-40b9-8b15-6c37c2369732.png)
[cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9024299/cfg.txt)

i can't open the cheat UI, pressing F1 do nothing, i have tried reset the game multiple times and download the file again, anyone know what's the problem?

**Comment by Taiga74164** [comment]
d3d11 is hooked so its probably because you have an active overlay such as MSI afterburner, etc.

**Comment by ghoetdaws** [comment]
> ![图片](https://user-images.githubusercontent.com/108499861/176801519-b87390a3-cbfd-40b9-8b15-6c37c2369732.png) [cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9024299/cfg.txt)
> 
> 我打不开作弊界面，按F1什么也没做，我试过多次重置游戏并重新下载文件，有人知道这是什么问题吗？

May I ask how you handled it?
