### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by auruumi** [Akebi-Group/Akebi-GC#196]
When I open game without cheat its okay after elements loading, but with injector I cannot open game further than this elements loading - windows is closing it.
![image](https://user-images.githubusercontent.com/108532886/176905729-cc08d0eb-0851-471b-ad77-59e8b3a85944.png)
(It says that genshin is closed because of some problem, then genshin closes)

**Comment by CPP-Callow** [comment]
Can you give your console output and attach your config file?

**Comment by 421124i** [comment]
When I open akebi from SpecialK, an unexpected crash happen. I wanna know whether the two are compatible.

**Comment by tedzify** [comment]
> When I open akebi from SpecialK, an unexpected crash happen. I wanna know whether the two are compatible.

Probably not, because this tool and SpecialK both inject dlls into the game.

**Comment by Taiga74164** [comment]
> When I open akebi from SpecialK, an unexpected crash happen. I wanna know whether the two are compatible.

You need to inject ``CLibrary.dll`` manually after launching the game with SpecialK

**Comment by Taiga74164** [comment]
closing this since it's old and author didn't provide more information. let us know if it occurs again or re-open this issue
