### ISSUE TITLE
[Bug] fast timeScale Game crash and grey screen

### ISSUE THREAD

**Issue by SunnySissi** [Akebi-Group/Akebi-GC#200]
sometimes game will crush suddenly.

sometimes  like there is a layer of grey covering the screen，and i cant do anything

**Comment by SunnySissi** [comment]
if you want cfg,its here
[cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9032293/cfg.txt)

**Comment by nnoc** [comment]
Try turning off the FPS unlocker and see if you face any crashing?

**Comment by SunnySissi** [comment]
jsut like this:
![image](https://user-images.githubusercontent.com/92515662/177049054-0b209b17-98ef-4a9a-815f-3e7432863e16.png)

**Comment by alt3ri** [comment]
"TimeSpeedup": 10.0
set it to 6 or 7

**Comment by lunaticwhat** [comment]
> "TimeSpeedup": 10.0 set it to 6 or 7

5 sometime would cause this too 
need better fast diag filters :KEKW:

**Comment by CNLouisLiu** [comment]
he appears at the end of the animation

**Comment by SunnySissi** [comment]
it mostly after using teleport
