### ISSUE TITLE
Some files is missing when a try to build the solution

### ISSUE THREAD

**Issue by KNALMEIDA** [Akebi-Group/Akebi-GC#201]
When i try some files is missing like ; Magic_enum.hpp, Simplelni.h, nlohmann/json.hpp, can somebody help me?

**Comment by KNALMEIDA** [comment]
> Duplicate of closed issue #175
it's quite different, can you help me?

**Comment by m0nkrel** [comment]
If you use VS 2022 - then just clone repository using it.
Else - use ```git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git```

**Comment by tedzify** [comment]
Don't forget to build in Release | x64.

**Comment by KNALMEIDA** [comment]
I already tried to build in Release X64 and i already used the git of visual studio 2022, and still giving the same error

**Comment by tedzify** [comment]
Did you read and do what the previous comment said?

**Comment by KNALMEIDA** [comment]
> Did you read and do what the previous comment said?

About yout previous comment? yes i read and i did what you said

**Comment by tedzify** [comment]
> If you use VS 2022 - then just clone repository using it. Else - use `git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git`

This.

**Comment by KNALMEIDA** [comment]
And about M0nkel yes i did it too, and it's giving the same erro

**Comment by tedzify** [comment]
Read issue #52 your answer is there.

**Comment by m0nkrel** [comment]
We already gived you instructions and links to same completed issues.

https://docs.microsoft.com/en-us/visualstudio/version-control/git-clone-repository?view=vs-2022

**Comment by KNALMEIDA** [comment]
Yess i know you gived me the instructions, but i already did all that you said and still giving the same error

**Comment by tedzify** [comment]
You're probably on the wrong folder where you don't have a submodules.

**Comment by KNALMEIDA** [comment]
IDK, what did i did but it worked, thank for you all that helps me, i hope you have a great weekend (English it's not my first language and i'm learning)
