### ISSUE TITLE
Insert a special character to textbox issue.

### ISSUE THREAD

**Issue by KNALMEIDA** [Akebi-Group/Akebi-GC#205]
When i try to insert a special character like Ç or ã, instead of appear Ç just appear ?, can somebody help me?

**Comment by Taiga74164** [comment]
imgui issue

**Comment by KNALMEIDA** [comment]
But is it possibel to solve?

**Comment by Taiga74164** [comment]
yes ofc

**Comment by KNALMEIDA** [comment]
But, how?

**Comment by Taiga74164** [comment]
glyphrange

**Comment by KNALMEIDA** [comment]
Glyphrange?

**Comment by tedzify** [comment]
ImGUI won't support those characters unless you edit the code to support for them.

**Comment by KNALMEIDA** [comment]
Oh, this seems to be pretty hard

**Comment by Taiga74164** [comment]
related to #71
