### ISSUE TITLE
Add Transparency for Incompleted Points on Interactive Map

### ISSUE THREAD

**Issue by HotdogMassacre** [Akebi-Group/Akebi-GC#211]
It's nice to have the completed points support transparency, would be great to have a slider for the Incomplete points as well. Just so you can see stuff under them. I tend to not show the completed points and often i find myself on the incomplete ones not being able to see the Lumenspar (for example) under them.

**Comment by Screenatyouruse** [comment]
uh bro. i think u forgor 💀 
![image](https://user-images.githubusercontent.com/78191668/177052540-c43a0001-f27b-4dfc-80d4-c527a22dea60.png)

**Comment by HotdogMassacre** [comment]
@Screenatyouruse re-read what i said :) I said the Completed point transparency is nice, but it would be nice to also have Incomplete points have transparency capabilities as well.

**Comment by HotdogMassacre** [comment]
@Fanixtar you are the best!!
