### ISSUE TITLE
Disable anti-addiction禁用防沉迷

### ISSUE THREAD

**Issue by 3058132083** [Akebi-Group/Akebi-GC#214]
Disable anti-addiction (chinese version)
![image](https://user-images.githubusercontent.com/52588960/177152522-cce6d111-0e10-49f1-b177-32f90423aa7a.png)
This should be possible by modifying the package

**Comment by daofeng2015** [comment]
> 不是，之前自动对话和抽卡在弹出后还可以吧这个窗口卡掉

主要是关闭后其他功能是否正常?

**Comment by 3058132083** [comment]
是的，只是过几分钟又会重新弹出来，理论上掌握好时机可以无限玩

**Comment by NctimeAza** [comment]
进门之后服务器不会返回玩家信息，除非你已经在大世界里了

**Comment by 3058132083** [comment]
如果已经成功登录能不能一直保持登录状态呢

**Comment by NctimeAza** [comment]
> 如果已经成功登录能不能一直保持登录状态呢

我认为是的

**Comment by 3058132083** [comment]
![gg](https://user-images.githubusercontent.com/52588960/178254437-2b12a3c2-f608-41db-946a-8de105c38e17.gif)

**Comment by 3058132083** [comment]
请问该如何实现，我无法使用vs调试器，我的编程水平也很糟糕

**Comment by 3058132083** [comment]
有人回应我吗

**Comment by daofeng2015** [comment]
自己关闭这个issues吧，目前都没研究这个方向，只能自己找了

**Comment by Thafoxes** [comment]
这个是服务器那边的限制，这里没有办法卡。就算有，这里的contributor 应该是不会去花时间研究这些。毕竟这里大部分玩家都是玩国际服没有时间限制

**Comment by 3058132083** [comment]
那有具体调试并添加自制功能的说明文档吗
