### ISSUE TITLE
Infinite Stamina not working with Move Sync Packet Replacement turned on

### ISSUE THREAD

**Issue by FallenAngelII** [Akebi-Group/Akebi-GC#220]
Yesterday I updated to the July 3rd build by overwriting my old files. Ever since, even if I go back to a previous build from June 29th or earlier, the same glitch persists:

If I turn Infinite Stamina and Move Sync Packet Replacement on, I will not have Infinite Stamina. The injector will just pretend like I haven't got Infinite Stamina toggled. Only if I turn off Move Sync Packet Replacement does the Infinite Stamina cheat start working.

**Comment by Taiga74164** [comment]
Release build or latest commit?

**Comment by FallenAngelII** [comment]
This one: https://drive.google.com/file/d/1B30A0wrh5mDgXabwyBVYjA-olrYqAIRb/view

I rely on someone else to build the builds and then use that.

**Comment by cip300** [comment]
You download have the latest commits , mybe because of the fix stamina commits the packet is no need anymore

**Comment by tedzify** [comment]
Think of `Packet Replacement` as an alternative of `Infinite Stamina`.
