### ISSUE TITLE
Add timed custom teleports

### ISSUE THREAD

**Issue by FallenAngelII** [Akebi-Group/Akebi-GC#221]
Is it possible to make it so that after you mark certain custom teleport points, you can just have the game automatically teleport to each of them in turn on a timer (like, teleport, wait 5 seconds, teleport again). With crash damage on and auto-looting on, you can then automate the Elite enemy farming process.

**Comment by harlanx** [comment]
Have you tried Custom Teleport and use a macro like AHK to simulate keypress with interval? Though waiting for 5 seconds wouldn't be enough. Sometimes load times may take longer. Defo need a checker to make sure player has loaded before can be triggered again.
