### ISSUE TITLE
Got banned 2nd time,anyone any idea about my cfg?

### ISSUE THREAD

**Issue by RaidenSN** [Akebi-Group/Akebi-GC#223]
1st time im pretty sure its auto-loot, never used it once since my acct was lifted.
Btw this is my main: ar 57 and i can easily clear abyss without cheat
[cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9046599/cfg.txt)
.

**Comment by firstapostle** [comment]
Did you go through the abyss on the first day?

**Comment by RaidenSN** [comment]
> Did you go through the abyss on the first day?

actually i did, is that a thing?

**Comment by firstapostle** [comment]
> > Did you go through the abyss on the first day?
> 
> actually i did, is that a thing?
That is the reason. I've tested almost all genshin cheats (both paid and free). And all were banned if passed on the first day of the abyss. 
Better to pass on day 2-3 (and later)

**Comment by Taiga74164** [comment]
> That is the reason. I've tested almost all genshin cheats (both paid and free). And all were banned if passed on the first day of the abyss. Better to pass on day 2-3 (and later)

i dont think this matters at all coz i speed run it every first day at ar58 lol

**Comment by ourlib** [comment]
noclip speed far more away from recommended value(5)
rapidfire better no more than 5
mobvaccum radius too large
chest and occuli teleport too often also return you a ban

**Comment by LEMON4D3** [comment]
Teleport is risky
