### ISSUE TITLE
Reload & adding teleports in JSON format crashes

### ISSUE THREAD

**Issue by Fractune** [Akebi-Group/Akebi-GC#23]
FYI: I made a video so I don't need to explain this issue => https://youtu.be/LYv1tU_y5KI
It crashes every time I reload or I add JSON

**Comment by tedzify** [comment]
The format on the `.json` is wrong. It only should be `ONE` coordinate per `.json` file.

Example:
`Cathedral.json`

content:
`{"name":"Cathedral (Mondstadt)","position":[2354.583984375,260.9907531738281,-685.9517211914063]}`

**Comment by Fractune** [comment]
Ah I see. I thought I could just add a file with multiple coordinates and just view those in the game... That sucks, I'll have to waste my time to divide the coords now 🤷🏼

**Comment by tedzify** [comment]
Use the `debug menu` to copy your current position as `.json` then add it to the `JSON input` on your `Custom Teleports`. Don't forget to put a name.

**Comment by Fractune** [comment]
I got the file with coords from a discord server, it's not rly something I made

**Comment by WitchGod** [comment]
I have something in the works to address this, which allows creation of multiple folders, files, and multiple coordinates per file. Just busy with real life responsibilities at the moment kek. And yes, it looks like a table but in the backend it's all JSON.

![image](https://user-images.githubusercontent.com/6817524/169647452-1edfa463-d6ff-4383-acf2-ec54fa228a08.png)

**Comment by Fractune** [comment]
By the way @WitchGod I meant to ask but is there a discord server you own by any chance, for this tool at least? I'd like to join

**Comment by WitchGod** [comment]
> By the way @WitchGod I meant to ask but is there a discord server you own by any chance, for this tool at least? I'd like to join

There is, but there's only 4 of us there and we talk about nothing but dev and research stuff. There's no "community" server, just a server where we share findings, todos, features, roadmaps, solve problems, etc.

**Comment by Fractune** [comment]
Any chance you will make one? I can help you with the discord 👍🏼
