### ISSUE TITLE
Long load time during Warning:read before playing pages.

### ISSUE THREAD

**Issue by amilxtech** [Akebi-Group/Akebi-GC#236]
![image](https://user-images.githubusercontent.com/109031177/178148873-04edd91f-3308-4926-907a-4cab16c5c409.png)

took me around 5 minute to get pass that page with the latest build.

**Comment by CPP-Callow** [comment]
> ![image](https://user-images.githubusercontent.com/109031177/178148873-04edd91f-3308-4926-907a-4cab16c5c409.png)
> 
> took me around 5 minute to get pass that page with the latest build.

Seems like old bug with video card drivers. Try update drivers and check again.

**Comment by Taiga74164** [comment]
> ![image](https://user-images.githubusercontent.com/109031177/178148873-04edd91f-3308-4926-907a-4cab16c5c409.png)
> 
> took me around 5 minute to get pass that page with the latest build.

Seems like you haven't updated your game client.
your checksum says "14648af3df1f47a7858d3335cf7288b0". that's for 2.7

**Comment by Taiga74164** [comment]
PlayerLoginReq checksum for 2.8 should be
```		"ed9fb95b179f957394ef2d984a397f35",
		"e8b31b9850496833399c259b358c9ba723",```

**Comment by amilxtech** [comment]
after updating my gpu driver , and testing using latest commit 2.8 everything back to normal load time 

case closed.
