### ISSUE TITLE
Sword Cemetery - Auto Talk bug

### ISSUE THREAD

**Issue by Fractune** [Akebi-Group/Akebi-GC#238]
This bug happens when you literally have Auto Talk enabled. You can't escape unless you close & reopen genshin. 

Enabled | Disabled
:-: | :-: 
<video src='https://user-images.githubusercontent.com/74881934/178161192-b69581ba-f4d6-44b8-85fa-86ecca5c4d1a.mp4' /> | <video src='https://user-images.githubusercontent.com/74881934/178161200-b8bc507a-6b36-442c-bfb6-733a7f3aa685.mp4' />

Occurs on latest build

**Comment by MemesPwr** [comment]
You're not able to interact with game when this happens? If so, try to build from sources if you can (or just wait for another release build).  
btw, seems like it was with statues, when you giving oculi

**Comment by alt3ri** [comment]
I've already encountered this since genshinxyz, so it's a common issue.

**Comment by Fractune** [comment]
> You're not able to interact with game when this happens? If so, try to build from sources if you can (or just wait for another release build). btw, seems like it was with statues, when you giving oculi

don't mean to be rude but are u blind? what did I write underneath those videos?
It's already the latest build also yes, I can't interact with the game when it's enabled

**Comment by Fractune** [comment]
> You're not able to interact with game when this happens? If so, try to build from sources if you can (or just wait for another release build). btw, seems like it was with statues, when you giving oculi

I'll remind you since u didn't read it fully, yes I have the latest build, Also yes, I can't interact with the game when it's enabled

Otherwise I wouldn't have opened this issue 🧠

**Comment by MemesPwr** [comment]
> I'll remind you since u didn't read it fully

damn. sorry. I was really missed your comment above videos :(


but...

> I have the latest build

i think there is a lot ppl who can misunderstand you with that  

how about to clarify in first post that you're builded this "DLC" from sources (not just `i have the latest build`)?

btw, what about statues? it looks like to be same bug behavior  
just try to feed a statue with oculus so you can get new level of it. same bug may appear (but I'm not sure, for me it was with commits from old repo which is taked down by dmca)

**Comment by Fractune** [comment]
> how about to clarify in first post that you're builded this "DLC" from sources (not just `i have the latest build`)?

You're the only one who misinterpeted what i said. I've clearly clarified that I have "the latest build" I never said that I used the "release" one on packages, get it over your head already.

> btw, what about statues? it looks like to be same bug behavior

I don't know about any statues. I've made this issue about this specific bug, if you know other ones then you should just go ahead & report them? what are u honestly thinking will happen if u tell me there are other relevant bugs to this? nothing.

**Comment by AndreiAdii** [comment]
It does not matter if it's the latest build or not. It's because of the Auto Talk, read it's description carefully

**Comment by Taiga74164** [comment]
related to #200
