### ISSUE TITLE
God Mode is immune to special damage (e.g. Cold, Electric Shock)

### ISSUE THREAD

**Issue by CNLouisLiu** [Akebi-Group/Akebi-GC#24]

**Comment by G1DE30N** [comment]
Cannot because Instaban.

**Comment by RyujinZX** [comment]
> Cannot because Instaban.

Have you personally checked? I don't think you can get an insta ban for that.

**Comment by G1DE30N** [comment]
I mean i think Callow cant do add that because to risky.

**Comment by Taiga74164** [comment]
It's not instant ban. It's just a difference in hook..
FireBeingHitEvent can solve this issue and it's already in the code. it's just not being used.
```DO_APP_FUNC(0x02ADE320, void, LCBaseCombat_FireBeingHitEvent, (LCBaseCombat* __this, uint32_t attackeeRuntimeID, AttackResult* attackResult, MethodInfo* method));```

**Comment by CNLouisLiu** [comment]
> 这不是即时禁令。这只是钩子的区别。 FireBeingHitEvent 可以解决这个问题，它已经在代码中。它只是没有被使用。 `DO_APP_FUNC(0x02ADE320, void, LCBaseCombat_FireBeingHitEvent, (LCBaseCombat* __this, uint32_t attackeeRuntimeID, AttackResult* attackResult, MethodInfo* method));`

thank you.
