### ISSUE TITLE
The passage of riddles in cheat + protection against hacking scripts.

### ISSUE THREAD

**Issue by Humawayy** [Akebi-Group/Akebi-GC#241]
It would be convenient for the cheat to immediately show how to pass this or that riddle, for example, how to correctly place monuments, etc. and also protection from breaking scripts, for example, until the inazuma for the quest opens, you can't teleport there, but I mean that this function can be turned on / off at will.

**Comment by Taiga74164** [comment]
1. You can use google to search how to solve puzzle
2. Just don't teleport to Inazuma
