### ISSUE TITLE
Support for beta version

### ISSUE THREAD

**Issue by zhouqingyi1127** [Akebi-Group/Akebi-GC#242]
hello

i use this project for the private server in beta with the @Taiga74164 fork. i just wondering will this project accept update for the beta version again? maybe create a branch separate?

**Comment by zhouqingyi1127** [comment]
sorry bad english i try not to translate

**Comment by zhouqingyi1127** [comment]
i wish to use the new Free Camera function for beta to take photos and other

**Comment by tedzify** [comment]
Just build from source. Clone repo using Visual Studio.

**Comment by Taiga74164** [comment]
I always work on the following version anyways so, yes, I will have probably have a branch on my fork for 2.8.5x Beta.. It's still up to Callow if he wants to create another branch for other versions tho

**Comment by tedzify** [comment]
Oh my bad, it was a request for beta support. Haven't got much sleep LOL

**Comment by zhouqingyi1127** [comment]
@Taiga74164 brother, cannot make branch?

**Comment by Fractune** [comment]
Just build from source for now bud, here tut how: https://www.youtube.com/watch?v=vwMT5iwVe9g

**Comment by CPP-Callow** [comment]
I don’t mind if you do.

> I always work on the following version anyways so, yes, I will probably have a branch on my fork for 2.8.5x Beta.. It's still up to Callow if he wants to create another branch for other versions tho
