### ISSUE TITLE
DMG multiplier not working on "flower monsters"

### ISSUE THREAD

**Issue by Fractune** [Akebi-Group/Akebi-GC#243]
dmg multiplier doesn't work on this type of monster(?) whatever to call them

https://user-images.githubusercontent.com/74881934/178474708-09b29f2d-9db9-4848-97d5-0902a205fd74.mp4

Occured on latest build

**Comment by Taiga74164** [comment]
not even normal attacks?

**Comment by Fractune** [comment]
nope

**Comment by m0nkrel** [comment]
it have type `Field`, not `Monster`.
Entity: 
`SceneObj_Stages_Property_Ani_Prop_SentryTurrets_01(Clone)`
