### ISSUE TITLE
checksum don't match with version 2.7

### ISSUE THREAD

**Issue by nalhiff** [Akebi-Group/Akebi-GC#245]
![image](https://user-images.githubusercontent.com/36839431/178650470-92fb3b6e-360d-4883-b888-f5fb908d1592.png)

its on 2.8 the global version, should i wait for the 2.8 support or any way to bypass the checksum but still close the mhyprot?

**Comment by RyujinZX** [comment]
My God, are you blind? The update has not yet been added to the repository...

**Comment by nalhiff** [comment]
kay thanks. yes im blind
