### ISSUE TITLE
2.8 Cooking has now a cooldown

### ISSUE THREAD

**Issue by Fractune** [Akebi-Group/Akebi-GC#246]
As the title says, so autocook sometimes isn't working properly.

https://user-images.githubusercontent.com/74881934/178656618-95d1706a-9c77-42e1-9e0a-c6c9c52776f5.mp4

Occurs on taiga's latest build

**Comment by RyujinZX** [comment]
Send a screenshot of the function settings

**Comment by Fractune** [comment]
> Send a screenshot of the function settings

<image src="https://i.imgur.com/NGkXAR5.png" />

**Comment by RyujinZX** [comment]
Ohh, I'll take a look today

**Comment by tedzify** [comment]
It still gives you the cooked items, but it doesn't show the complete animation.

**Comment by cip300** [comment]
Mine give server error 
[url=https://ibb.co/pLVG14f][img]https://i.ibb.co/z49jmPX/2022-07-13-21-27-47.png[/img][/url]

**Comment by Sergiy3013** [comment]
It can still be used if you then cook everything manually, here is an example:
https://cdn.discordapp.com/attachments/980008184045527060/996863320000835704/Genshin_Impact_2022-07-13_22-37-11.mp4

**Comment by Fractune** [comment]
> It can still be used if you then cook everything manually, here is an example: https://cdn.discordapp.com/attachments/980008184045527060/996863320000835704/Genshin_Impact_2022-07-13_22-37-11.mp4

that's basically without the autocook from akebi ... obv it works 🙏🏼
