### ISSUE TITLE
crash upon opening

### ISSUE THREAD

**Issue by trashyboats** [Akebi-Group/Akebi-GC#247]
tried running it in admin but it still crashes the moment it launches. using #228 unofficial update.

edit: sorry if this sound unappreciative, i just thought im missing out on something to make it launch.

**Comment by tedzify** [comment]
The current latest commit still doesn't support ver 2.8. #240 is still under testing and development. The reason why your game is crashing is because you're using an outdated version.

**Comment by trashyboats** [comment]
> 

i see, thanks much!

**Comment by CPP-Callow** [comment]
What version of genshin you use, global or cn?

**Comment by CPP-Callow** [comment]
Yeah, you should use the latest commit, if you got same result create new PR.
