### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by IcyKishi** [Akebi-Group/Akebi-GC#248]
![imagen_2022-07-13_033251157](https://user-images.githubusercontent.com/109209055/178688623-16b6d9bc-42c2-419e-b63c-55ba994accca.png)

this hapend just before i opened the game, while the elements are loading

**Comment by joblesscoder** [comment]
Game update to 2.8

**Comment by IcyKishi** [comment]
> Game update to 2.8

so isnt akebi updated to 2.8 yet?  i already had the lastest zip (master) the only thing i didnt got was the injector that i got from the 2.7 file (idk if theres any for the 2.8 yet)

**Comment by CPP-Callow** [comment]
What version you use, CN or Global?

**Comment by Lunairayz** [comment]
> > Game update to 2.8
> 
> so isnt akebi updated to 2.8 yet? i already had the lastest zip (master) the only thing i didnt got was the injector that i got from the 2.7 file (idk if theres any for the 2.8 yet)

build the source, it's updated

**Comment by joblesscoder** [comment]
> th

I think that in order to get support for 2.8 you need to compile the sources yourself

**Comment by IcyKishi** [comment]
> > th
> 
> I think that in order to get support for 2.8 you need to compile the sources yourself

alr thanks i sadly have no idea abt this, thanks for the time

**Comment by IcyKishi** [comment]
> What version you use, CN or Global?

global

**Comment by CPP-Callow** [comment]
> > th
> 
> I think that in order to get support for 2.8 you need to compile the sources yourself

.

**Comment by Lunairayz** [comment]
> > > th
> > 
> > 
> > I think that in order to get support for 2.8 you need to compile the sources yourself
> 
> alr thanks i sadly have no idea abt this, thanks for the time

here you go, i built like 3 seconds ago https://cdn.discordapp.com/attachments/986013153437548594/996705868219416656/genshin_cheat_dev.zip

**Comment by nalhiff** [comment]
thanks for the latest commit Lunairayz, but i dont know why.. genshin impact keep not responding after click to begin on start game screen

does anyone else got the same thing? i even tried using it without my 0.7.5 cfg

**Comment by Lunairayz** [comment]
> thanks for the latest commit Lunairayz, but i dont know why.. genshin impact keep not responding after click to begin on start game screen
> 
> does anyone else got the same thing? i even tried using it without my 0.7.5 cfg

doesn't happen to me, idk what's happening

**Comment by nalhiff** [comment]
https://user-images.githubusercontent.com/36839431/178717167-076cfcbd-8040-4726-910a-10cee87cf59e.mp4

![image](https://user-images.githubusercontent.com/36839431/178717237-69166347-ff36-46a3-a6d4-a963dd6a26d1.png)
![Capture](https://user-images.githubusercontent.com/36839431/178717441-71f72973-a663-4f52-9059-5304ad7e079b.JPG)
