### ISSUE TITLE
[Solution]Game crashes on startup. "Initializing D3D11 hook: started"

### ISSUE THREAD

**Issue by nalhiff** [Akebi-Group/Akebi-GC#252]
https://user-images.githubusercontent.com/36839431/178717167-076cfcbd-8040-4726-910a-10cee87cf59e.mp4

![image](https://user-images.githubusercontent.com/36839431/178717237-69166347-ff36-46a3-a6d4-a963dd6a26d1.png)
![Capture](https://user-images.githubusercontent.com/36839431/178717441-71f72973-a663-4f52-9059-5304ad7e079b.JPG)

_Originally posted by @nalhiff in https://github.com/Akebi-Group/Akebi-GC/issues/248#issuecomment-1183073332_

**Comment by Micah123321** [comment]
This is also the case with me. I can't start the game normally and use the latest version 2.8

**Comment by Cephetir** [comment]
Same issue, happens randomly on startup

**Comment by nalhiff** [comment]
> Same issue, happens randomly on startup

not random for me, 5 of 5 happens 100% for me

**Comment by beckgreen** [comment]
me too

**Comment by itvhot1** [comment]
how to fix it ?

**Comment by zhouqingyi1127** [comment]
first of all thank you callow and the team

i encounter crash too when build chinese-2.8 but only once
after it seems okay

**Comment by waldo55s** [comment]
go to device manager and uninstall your display adapter aka gpu and then restart ur pc or update the driver with geforce experience or idk

worked for me

**Comment by CorkyPotato** [comment]
Same issue, completely disabled antivirus and game still becomes unresponsive after booting through injector. PC: Acer RTX 2060

**Comment by genshinim** [comment]
I got a i7-9750H+GTX1660Ti laptop. When I disable the 1660Ti in device manager and use the UHD 630 in my CPU, this works fine. You might also want to lower the visual effects if you got a weak integrated graphics like I do.

**Comment by Micah123321** [comment]
> I got a i7-9750H+GTX1660Ti laptop. When I disable the 1660Ti in device manager and use the UHD 630 in my CPU, this works fine. You might also want to lower the visual effects if you got a weak integrated graphics like I do.


所以看起来是显卡驱动的问题，或者是dx11插件更新导致的兼容问题，我现在尝试去更新一下驱动再运行注入器

So it seems that it is the problem of the graphics card driver or the compatibility problem caused by the update of the Dx11 util. Now I try to update the driver and run the injector

**Comment by Micah123321** [comment]
Everyone, I updated the graphics card driver to the latest version can be successfully injected, problem solved
各位,我更新显卡驱动到最新版本之后可以成功注入了,问题解决
