### ISSUE TITLE
upload_crash

### ISSUE THREAD

**Issue by q00rwa** [Akebi-Group/Akebi-GC#255]
First of all, thank you for your work.
I downloaded the latest release, the game crashes on startup. Version 0.75 worked without problems and now I did everything the same way. What is this problem and what can I do to solve it?
![Desktop Screenshot 2022 07 13 - 15 20 38 66](https://user-images.githubusercontent.com/77891864/178733599-fc08264c-79f7-44d2-8dba-bfdbb7a9fe87.png)

https://user-images.githubusercontent.com/77891864/178734057-bf5bd636-9174-4114-aaa7-2e01bce91101.mp4

**Comment by q00rwa** [comment]
I also tried to compile it from sources, but I had few errors in VS and idk how to fix it (I'm bad in programming). I did everything according to the instructions.

![image](https://user-images.githubusercontent.com/77891864/178751146-20308eb1-cca4-4629-9028-ca7c27eb4fcf.png)

**Comment by q00rwa** [comment]
> download and install git, then paste this command on git bash "git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git" and build the .sln file. make sure to select "release x64" in the vsc or https://www.youtube.com/watch?v=vwMT5iwVe9g

Thx for answer. I did it step-by-step, but still have same result:

![Desktop Screenshot 2022 07 13 - 17 49 29 51](https://user-images.githubusercontent.com/77891864/178764705-88de4e26-237c-4d18-9de7-2894a8b65b08.png)

**Comment by tedzify** [comment]
Did you update your game yet?

**Comment by q00rwa** [comment]
> Have you updated your game yet?

Yeah, sure

**Comment by q00rwa** [comment]
I'm so stupid, damn me.
Two days later, I realized that I have two game clients - on hdd and on ssd. Due to inattention, I pointed the injector to the wrong exe. 
My bad.
