### ISSUE TITLE
Request:AutoDestroy add support for Dandelion Seed、Sakura Bloom、Mister Flower、Flaming Flower

### ISSUE THREAD

**Issue by xuewuji** [Akebi-Group/Akebi-GC#256]
These Plant need Elemental to gather，can AutoDestroy and Loot them?

**Comment by zhouqingyi1127** [comment]
i remember genshin xyz auto destroy have this feature before

**Comment by Taiga74164** [comment]
> i remember genshin xyz auto destroy have this feature before
> These Plant need Elemental to gather，can AutoDestroy and Loot them?

Seems auto destroying sakura bloom completely destroys the entity and it won't let you pick it up. Its the same function used with XYZ but i can't recall if it was the same case too

**Comment by Wansn-w** [comment]
i found that the entity manager couldn't find it either
![image](https://user-images.githubusercontent.com/49867372/182073363-5d66802e-d925-47b2-a62e-3ea71ad991a9.png)

**Comment by Taiga74164** [comment]
> i found that the entity manager couldn't find it either ![image](https://user-images.githubusercontent.com/49867372/182073363-5d66802e-d925-47b2-a62e-3ea71ad991a9.png)


that is sakura bloom tho

**Comment by Wansn-w** [comment]
> > i found that the entity manager couldn't find it either ![image](https://user-images.githubusercontent.com/49867372/182073363-5d66802e-d925-47b2-a62e-3ea71ad991a9.png)
> 
> that is sakura bloom tho
😥

**Comment by Wansn-w** [comment]
maybe we can add automatic shrub destruction, because when bushes are destroyed, they randomly produce matsutake, bird eggs or lizards 🤔
