### ISSUE TITLE
How to enabled Chinese?

### ISSUE THREAD

**Issue by guchang233** [Akebi-Group/Akebi-GC#260]
Q:like the title . How to enabled Chinese?
 im a Chinese ,my English is not very good , so Im going to have a lot of trouble looking at this interface QAQ

**Comment by beckgreen** [comment]
https://meihua.lanzouq.com/ishY006hufti 这是之前版本的翻译，应该够用了

**Comment by guchang233** [comment]
不不不,由于他的tag项里有一个“akebi-gc-v0.8-g2.8-binaries-chinese.zip”我看到了Chinese 所以我想它可能已经支持更换语言了（

**Comment by guchang233** [comment]
> https://meihua.lanzouq.com/ishY006hufti 这是之前版本的翻译，应该够用了

不不不,由于他的tag项里有一个“akebi-gc-v0.8-g2.8-binaries-chinese.zip”我看到了Chinese 所以我想它可能已经支持更换语言了（

**Comment by beckgreen** [comment]
他的意思是中国版本，小误会。你能够正常使用吗？我卡在这里一晚上了
![图片](https://user-images.githubusercontent.com/109228275/178806310-3b23350c-bdd6-43cc-a863-811ff544bab8.png)

**Comment by guchang233** [comment]
> 他的意思是中国版本，小误会。你能够正常使用吗？我卡在这里一晚上了 ![图片](https://user-images.githubusercontent.com/109228275/178806310-3b23350c-bdd6-43cc-a863-811ff544bab8.png)

哦哦 原来是这样 
关于你的问题 你试试选中debug窗口然后按下 空格 或者 回车 一次不行就多几次 出现错误提示音大概率就行了

**Comment by beckgreen** [comment]
> 

  谢谢，但是可惜没有用、2.7还正常 就今晚无法进入了。群里有人正常使用，重新安装也是一样、不太理解...
只能看后续更新了。这么晚早点睡吧。

**Comment by guchang233** [comment]
> > 
> 
> 谢谢，但是可惜没有用、2.7还正常 就今晚无法进入了。群里有人正常使用，重新安装也是一样、不太理解... 只能看后续更新了。这么晚早点睡吧。

睡觉的话 你也早点睡
关于进不去游戏 不介意的话试试我修改的
https://wwu.lanzouj.com/iSMKE07sv0xa
密码:d4h9

**Comment by guchang233** [comment]
> > 
> 
> 谢谢，但是可惜没有用、2.7还正常 就今晚无法进入了。群里有人正常使用，重新安装也是一样、不太理解... 只能看后续更新了。这么晚早点睡吧。

要不加个q吧 在这里聊天不太合适 57262494

**Comment by jiushiduhui** [comment]
> > 
> 
> 谢谢，但是可惜没有用、2.7还正常 就今晚无法进入了。群里有人正常使用，重新安装也是一样、不太理解... 只能看后续更新了。这么晚早点睡吧。

群是多少，加我一个

**Comment by wonidiess** [comment]
兄弟你交互式的地图能不显示已经拿过的点吗，我这个版本好像不行。

**Comment by Taiga74164** [comment]
> 兄弟你交互式的地图能不显示已经拿过的点吗，我这个版本好像不行。

compile the source code

**Comment by guchang233** [comment]
> > 兄弟你交互式的地图能不显示已经拿过的点吗，我这个版本好像不行。
> 
> 编译源代码

不我不行 它的原理就是硬读坐标 目前还不能这么智能 最好还是配合罗盘用

**Comment by Micah123321** [comment]
可以自己修改源码进行翻译 这是我翻译的部分截图
You can modify the source code and translate it yourself. This is a screenshot of my translation
![截图](https://btxo.cn/oss/2022-07-17/96f91d8e.png)

**Comment by guchang233** [comment]
> 可以自己修改源码进行翻译 这是我翻译的部分截图 You can modify the source code and translate it yourself. This is a screenshot of my translation ![截图](https://camo.githubusercontent.com/353d79006cc88bbd6d2f0560ea7f11fe60ce5c8fd97a419e6d12079696916e80/68747470733a2f2f6274786f2e636e2f6f73732f323032322d30372d31372f39366639316438652e706e67)

我不是很擅长imgui，做不到添加中文，我还是看得懂的 只不过为了分享给朋友.您能把自己的中文版发我吗或者给个链接啥的

**Comment by Micah123321** [comment]
>> 可以自己修改源码进行翻译 这是我翻译的部分截图 You can modify the source code and translate it yourself. This is a screenshot of my translation ![123](https://camo.githubusercontent.com/8ee5851606b9dc85ff09230ea5cb832a6a59b345127f3b8fc8cd2091ee9ad160/68747470733a2f2f6f73732e7869616f6d616f362e636f6d2f6d6b6f73732f323032322f30372f31372f65633063366133322e706e67)
> 我不是很擅长imgui，做不到添加中文，我还是看得懂的 只不过为了分享给朋友.您能把自己的中文版发我吗或者给个链接啥的

并没有翻译完,工作量小大,具体实现原理参考这段

```c

     //定义
	static void LoadCustomFont()
	{
		/*if (_customFontData.data == nullptr)
			return;

		for (int i = 0; i < _fontsCount; i++)
		{
			ImGuiIO& io = ImGui::GetIO();
                  auto fonts = ImGui::GetIO().Fonts;
                  auto newFont = io.Fonts->AddFontFromMemoryTTF(
                      _customFontData.data, _customFontData.size,
                      static_cast<float>((i + 1) * _fontSizeStep));

				      ImFont* font = io.Fonts->AddFontFromFileTTF(
                      "c:\\Windows\\Fonts\\simhei.ttf", 16.0f, NULL,
                      io.Fonts->GetGlyphRangesChineseFull());
                  IM_ASSERT(font != NULL);

			if (newFont == nullptr)
				return;

			
		}
		_isCustomFontLoaded = true;*/
          ImGuiIO& io = ImGui::GetIO();
          ImFont* font = io.Fonts->AddFontFromFileTTF(
              "c:\\Windows\\Fonts\\simhei.ttf", 16.0f, NULL,
              io.Fonts->GetGlyphRangesChineseFull());
          IM_ASSERT(font != NULL);
          _fonts[0] = font;

	}
```

**Comment by daofeng2015** [comment]
> > > 可以自己修改源码进行翻译 这是我翻译的部分截图 You can modify the source code and translate it yourself. This is a screenshot of my translation ![123](https://camo.githubusercontent.com/8ee5851606b9dc85ff09230ea5cb832a6a59b345127f3b8fc8cd2091ee9ad160/68747470733a2f2f6f73732e7869616f6d616f362e636f6d2f6d6b6f73732f323032322f30372f31372f65633063366133322e706e67)
> > > 我不是很擅长imgui，做不到添加中文，我还是看得懂的 只不过为了分享给朋友.您能把自己的中文版发我吗或者给个链接啥的
> 
> 并没有翻译完,工作量小大,具体实现原理参考这段
> 
> ```c
>      //定义
> 	static void LoadCustomFont()
> 	{
> 		/*if (_customFontData.data == nullptr)
> 			return;
> 
> 		for (int i = 0; i < _fontsCount; i++)
> 		{
> 			ImGuiIO& io = ImGui::GetIO();
>                   auto fonts = ImGui::GetIO().Fonts;
>                   auto newFont = io.Fonts->AddFontFromMemoryTTF(
>                       _customFontData.data, _customFontData.size,
>                       static_cast<float>((i + 1) * _fontSizeStep));
> 
> 				      ImFont* font = io.Fonts->AddFontFromFileTTF(
>                       "c:\\Windows\\Fonts\\simhei.ttf", 16.0f, NULL,
>                       io.Fonts->GetGlyphRangesChineseFull());
>                   IM_ASSERT(font != NULL);
> 
> 			if (newFont == nullptr)
> 				return;
> 
> 			
> 		}
> 		_isCustomFontLoaded = true;*/
>           ImGuiIO& io = ImGui::GetIO();
>           ImFont* font = io.Fonts->AddFontFromFileTTF(
>               "c:\\Windows\\Fonts\\simhei.ttf", 16.0f, NULL,
>               io.Fonts->GetGlyphRangesChineseFull());
>           IM_ASSERT(font != NULL);
>           _fonts[0] = font;
> 
> 	}
> ```

不要随便做翻译的事，某些商家就等着你做好事，自己用着就行别传播
