### ISSUE TITLE
I seem to have some small problems

### ISSUE THREAD

**Issue by beckgreen** [Akebi-Group/Akebi-GC#261]
![图片](https://user-images.githubusercontent.com/109228275/178803895-e769530a-1333-4685-a152-d7517c2adea3.png)
I can't get into the game normally, but I don't know why  Every time I stop at this place and report an error
First time encountering this situation 
what should i do？

**Comment by tedzify** [comment]
Chinese and Global version have different offsets. Build [this branch](https://github.com/Akebi-Group/Akebi-GC/tree/chinese-2.8) for CN version.

**Comment by beckgreen** [comment]
> Chinese and Global version have different offsets. Build [this branch](https://github.com/Akebi-Group/Akebi-GC/tree/chinese-2.8) for CN version.

So i just need Akebi to wait for the update？

**Comment by beckgreen** [comment]
> I don't know if they will upload the binaries of the CN version. It would be faster to build the source yourself, than waiting for a release.
I understand, thank you sir

**Comment by Ltxwd1** [comment]
> > I don't know if they will upload the binaries of the CN version. It would be faster to build the source yourself, than waiting for a release.
> > I understand, thank you sir
Is it solved？

**Comment by beckgreen** [comment]
> > > I don't know if they will upload the binaries of the CN version. It would be faster to build the source yourself, than waiting for a release.
> > > I understand, thank you sir
> > > Is it solved？

I think not yet

**Comment by Taiga74164** [comment]
Seems like your issue is related with #252 .
> Everyone, I updated the graphics card driver to the latest version can be successfully injected, problem solved 各位,我更新显卡驱动到最新版本之后可以成功注入了,问题解决




> > > > I don't know if they will upload the binaries of the CN version. It would be faster to build the source yourself, than waiting for a release.
> > > > I understand, thank you sir
> > > > Is it solved？
> 
> I think not yet

Binaries are uploaded already for Chinese clients
https://github.com/Akebi-Group/Akebi-GC/releases/download/v0.8/akebi-gc-v0.8-g2.8-binaries-global.zip
