### ISSUE TITLE
My program has been stuck here

### ISSUE THREAD

**Issue by ghoetdaws** [Akebi-Group/Akebi-GC#264]
If I could just have a moment of your time？I'd like to ask why the program has been stuck here.
![NT G99%2@MD_ C0E{C0D$YR](https://user-images.githubusercontent.com/93196361/178862066-d24a6574-d187-4d23-96e8-5e2b8fd194f4.jpg)

**Comment by Taiga74164** [comment]
d3d11 is hooked so everything looks fine on the program's end. If you're having trouble accessing the menu, it's most likely because you have an active overlay running. Make sure to disable it when running Akebi.

**Comment by ghoetdaws** [comment]
> d3d11 被钩住了，所以在程序结束时一切看起来都很好。如果您在访问菜单时遇到问题，很可能是因为您正在运行一个活动的覆盖。确保在运行 Akebi 时禁用它。

Thanks, problem solved. MSI afterburner took up d3d11, causing the menu to not open properly.
