### ISSUE TITLE
Unable to Compile in VS

### ISSUE THREAD

**Issue by thelostabbey** [Akebi-Group/Akebi-GC#265]
hey all!

having a slight problem compiling program in VS.  

anytime I try to compile I keep coming across "file not found".  

Windows defender did see some parts as a "virus" but I excluded the directory from future scans. 

is this a problem with anti-virus or something else?  i scanned the repo for the files it's requesting and I'm not getting any hits.  

![image](https://user-images.githubusercontent.com/48223004/178866536-85b26f0d-6fec-4ffb-a1f8-bb908b80cfbf.png)

Note: the pre-built release 0.8 works fine

**Comment by Taiga74164** [comment]
please refer to # 1 in https://github.com/Akebi-Group/Akebi-GC#building-from-source

**Comment by thelostabbey** [comment]
@Taiga74164, thank you for the suggestion.  Yes, I've done this multiple times. reinstalled VS and redownloaded the C++ redistributables.  

`$ git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git
Cloning into 'Akebi-GC'...
remote: Enumerating objects: 2777, done.
remote: Counting objects: 100% (881/881), done.
remote: Compressing objects: 100% (287/287), done.
remote: Total 2777 (delta 672), reused 695 (delta 591), pack-reused 1896
Receiving objects: 100% (2777/2777), 34.93 MiB | 14.07 MiB/s, done.
Resolving deltas: 100% (1269/1269), done.
Submodule 'cheat-base/vendor/fmt' (https://github.com/fmtlib/fmt.git) registered for path 'cheat-base/vendor/fmt'
Submodule 'cheat-base/vendor/imgui' (https://github.com/CallowBlack/imgui-brightness-fix.git) registered for path 'cheat-base/vendor/imgui'
Submodule 'cheat-library/vendor/json' (https://github.com/nlohmann/json.git) registered for path 'cheat-base/vendor/json'
Submodule 'cheat-base/vendor/magic_enum' (https://github.com/Neargye/magic_enum.git) registered for path 'cheat-base/vendor/magic_enum'
Submodule 'cheat-base/vendor/simpleIni' (https://github.com/brofield/simpleini.git) registered for path 'cheat-base/vendor/simpleIni'
Submodule 'cheat-base/vendor/stb' (https://github.com/nothings/stb.git) registered for path 'cheat-base/vendor/stb'
Cloning into 'E:/GitHub Repositories/Akebi-GC 2/Akebi/Akebi-GC/cheat-base/vendor/fmt'...
remote: Enumerating objects: 30041, done.
remote: Counting objects: 100% (163/163), done.
remote: Compressing objects: 100% (83/83), done.
remote: Total 30041 (delta 90), reused 118 (delta 64), pack-reused 29878
Receiving objects: 100% (30041/30041), 14.26 MiB | 11.50 MiB/s, done.
Resolving deltas: 100% (20262/20262), done.
Cloning into 'E:/GitHub Repositories/Akebi-GC 2/Akebi/Akebi-GC/cheat-base/vendor/imgui'...
remote: Enumerating objects: 44312, done.
remote: Total 44312 (delta 0), reused 0 (delta 0), pack-reused 44312
Receiving objects: 100% (44312/44312), 79.78 MiB | 16.48 MiB/s, done.
Resolving deltas: 100% (33724/33724), done.
Cloning into 'E:/GitHub Repositories/Akebi-GC 2/Akebi/Akebi-GC/cheat-base/vendor/json'...
remote: Enumerating objects: 90297, done.
remote: Counting objects: 100% (300/300), done.
remote: Compressing objects: 100% (190/190), done.
remote: Total 90297 (delta 118), reused 255 (delta 84), pack-reused 89997
Receiving objects: 100% (90297/90297), 289.01 MiB | 10.65 MiB/s, done.
Resolving deltas: 100% (71450/71450), done.
Cloning into 'E:/GitHub Repositories/Akebi-GC 2/Akebi/Akebi-GC/cheat-base/vendor/magic_enum'...
remote: Enumerating objects: 1915, done.
remote: Counting objects: 100% (718/718), done.
remote: Compressing objects: 100% (193/193), done.
remote: Total 1915 (delta 598), reused 558 (delta 513), pack-reused 1197
Receiving objects: 100% (1915/1915), 576.97 KiB | 2.02 MiB/s, done.
Resolving deltas: 100% (1076/1076), done.
Cloning into 'E:/GitHub Repositories/Akebi-GC 2/Akebi/Akebi-GC/cheat-base/vendor/simpleIni'...
remote: Enumerating objects: 445, done.
remote: Counting objects: 100% (148/148), done.
remote: Compressing objects: 100% (60/60), done.
remote: Total 445 (delta 84), reused 144 (delta 81), pack-reused 297
Receiving objects: 100% (445/445), 223.04 KiB | 1.47 MiB/s, done.
Resolving deltas: 100% (262/262), done.
Cloning into 'E:/GitHub Repositories/Akebi-GC 2/Akebi/Akebi-GC/cheat-base/vendor/stb'...
remote: Enumerating objects: 7844, done.
remote: Counting objects: 100% (573/573), done.
remote: Compressing objects: 100% (209/209), done.
remote: Total 7844 (delta 372), reused 544 (delta 364), pack-reused 7271
Receiving objects: 100% (7844/7844), 5.45 MiB | 7.13 MiB/s, done.
Resolving deltas: 100% (5217/5217), done.
Submodule path 'cheat-base/vendor/fmt': checked out '86e27ccb41c2708e17ba264359223ef664d9bb78'
Submodule path 'cheat-base/vendor/imgui': checked out '47fb633e73f69e1ba57cef16cd077ddc4d97f0ee'
Submodule path 'cheat-base/vendor/json': checked out 'a94430615d8360272151f602b8c9eeb58509ecde'
Submodule path 'cheat-base/vendor/magic_enum': checked out 'd1ccd22c853ac3afaf7a0f1c86019ea641e777c5'
Submodule path 'cheat-base/vendor/simpleIni': checked out '9b3ed7ec815997bc8c5b9edf140d6bde653e1458'
Submodule path 'cheat-base/vendor/stb': checked out 'af1a5bc352164740c1cc1354942b1c6b72eacb8a'
`

I've also compiled this cheat multiple times in the past but this is the first time I'm seeing these errors. I guess I'll just use the one from releases

**Comment by Taiga74164** [comment]
oh wait yours says cannot find Windows.h lol

**Comment by thelostabbey** [comment]
@Taiga74164 ah, I see. it says it's an issue with SDK install. I'm reinstalling to see if it fixes it.  I'll edit this if it works, thanks!
