### ISSUE TITLE
I have a  problem

### ISSUE THREAD

**Issue by Ltxwd1** [Akebi-Group/Akebi-GC#266]
Seems like assembly checksum don't match with version 2.8. It's normal only if you using Chinese version of genshin impact.
   Save the child, what should I do

**Comment by Taiga74164** [comment]
you can ignore this aslong as you're running version 2.8 of the game

**Comment by Ltxwd1** [comment]
> you can ignore this aslong as you're running version 2.8 of the game

I used 2.8, and I reinstalled the game
