### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Ltxwd1** [Akebi-Group/Akebi-GC#269]
[Warning] [il2cpp-init.cpp:148] Seems like assembly checksum don't match with version 2.8. It's normal only if you using Chinese version of genshin impact.

**Comment by Taiga74164** [comment]
like I said you can ignore this. it's just a warning

**Comment by Ltxwd1** [comment]
> 
Big brother, ignore him and can't use your program. After entering, it shows no found，I don't know what to do if I press the F11 program and don't display it

**Comment by Ltxwd1** [comment]
sorry，I can use

**Comment by whisper1188** [comment]
@Taiga74164 I had the same problem, but mine will not into the game. Keep getting stuck in the text interface.
