### ISSUE TITLE
能不能发一下适用于中国的源码

### ISSUE THREAD

**Issue by bo171** [Akebi-Group/Akebi-GC#270]
这样便于我们去调试编译，谢谢大哥

**Comment by bo171** [comment]
您发行的那份源码好像编译不了

**Comment by grxp** [comment]
https://github.com/Akebi-Group/Akebi-GC/tree/chinese-2.8 适用于中国版的源码

**Comment by restarteded** [comment]
方便你拿去卖是吗

**Comment by bo171** [comment]
我拿着全英的去卖给中国人吗，哈哈哈，单纯的学习一下而已

**Comment by x-rainy** [comment]
那希望你在搬运的时候不要加上自己的注册码呢

**Comment by CNLouisLiu** [comment]
自己关掉你的issue吧.仅允许英文的issue.大家也别回复了.
