### ISSUE TITLE
Auto Heal when Hurt

### ISSUE THREAD

**Issue by ArthaVerx** [Akebi-Group/Akebi-GC#272]
Auto Eating when your hp is below a certain point, or allowing waypoint to heal you like statue of the seven, or somethin. is it possible?

**Comment by milkboy77** [comment]
So why not use that quick food bag?
Ake seems to have achieved immunity to almost all the injuries received. Why not try this?

**Comment by milkboy77** [comment]
Good idea, but there is no need to take this risk:(

**Comment by Taiga74164** [comment]
healing is done in server
