### ISSUE TITLE
CN server cannot run properly 

### ISSUE THREAD

**Issue by Sthhus** [Akebi-Group/Akebi-GC#277]
CN server cannot run properly  

And when I checked it out,

It seems AssemblyDLL is compiled separately for CN server and international server

As a result, the data of the two servers is inconsistent. At present, CN server will crash directly after DLL injection

My English is not very good, most of the time need to use translation, hope to understand

**Comment by CNLouisLiu** [comment]
https://github.com/Akebi-Group/Akebi-GC/releases
akebi-gc-v0.8-g2.8-binaries-chinese.zip

**Comment by Sthhus** [comment]
> https://github.com/Akebi-Group/Akebi-GC/releases akebi-gc-v0.8-g2.8-binaries-chinese.zip

I need the source code. Do you have the source code

**Comment by NctimeAza** [comment]
> > https://github.com/Akebi-Group/Akebi-GC/releases akebi-gc-v0.8-g2.8-binaries-chinese.zip
> 
> I need the source code. Do you have the source code

https://github.com/Akebi-Group/Akebi-GC/tree/chinese-2.8
cn版分支

**Comment by CNLouisLiu** [comment]
> > > https://github.com/Akebi-Group/Akebi-GC/releases akebi-gc-v0.8-g2.8-binaries-chinese.zip
> > 
> > 
> > I need the source code. Do you have the source code
> 
> https://github.com/Akebi-Group/Akebi-GC/tree/chinese-2.8 cn版分支

Get the source code to sell?

**Comment by milkboy77** [comment]
> > https://github.com/Akebi-Group/Akebi-GC/releases akebi-gc-v0.8-g2.8-binaries-chinese.zip
> 
> 我需要源代码。你有源代码吗

If it's just for learning, isn't there already a source code?XD

**Comment by Sthhus** [comment]
> > > > https://github.com/Akebi-Group/Akebi-GC/releases akebi-gc-v0.8-g2.8-binaries-chinese.zip
> > > 
> > > 
> > > I need the source code. Do you have the source code
> > 
> > 
> > https://github.com/Akebi-Group/Akebi-GC/tree/chinese-2.8 cn版分支
> 
> Get the source code to sell?

No, it's not for sale.

I was playing on two servers at the same time, and I made a version based on the original for my own play,

Some things that I think are not very useful have been removed, but since the update of version 2.7,dump tool cannot work properly, and the data of the two servers are inconsistent, so it takes time to update. I need to compare the bytecode of the two servers, so I want to be lazy and copy the address.

**Comment by Sthhus** [comment]
> 

Selling an open source project is a stupid thing to do.

But this happens a lot in China and I don't like it.

And the person who sells it will tell others that he made it himself. They don't seem to have any brains.

**Comment by Sthhus** [comment]
> > > > https://github.com/Akebi-Group/Akebi-GC/releases akebi-gc-v0.8-g2.8-binaries-chinese.zip
> > > 
> > > 
> > > I need the source code. Do you have the source code
> > 
> > 
> > https://github.com/Akebi-Group/Akebi-GC/tree/chinese-2.8 cn版分支
> 
> Get the source code to sell?

Selling an open source project is a stupid thing to do.

But this happens a lot in China and I don't like it.

And the person who sells it will tell others that he made it himself. They don't seem to have any brains.

**Comment by Sthhus** [comment]
> ###

Selling an open source project is a stupid thing to do.

But this happens a lot in China and I dont like it.

And the person who sells it will tell others that he made it himself. They dont seem to have any brains.
