### ISSUE TITLE
GameSpeed HotKey Option

### ISSUE THREAD

**Issue by EchoesFromBeyond** [Akebi-Group/Akebi-GC#280]
Loving the FastDialog, but there are some frames where it doesn't happen when you want it to. It would be amazing to have a Hotkey you can press that will invoke the Game Speedup that happens, that way you can just do it when you need to.

**Comment by Taiga74164** [comment]
Yea sure. A separate section for timeScale can be added or just add an option to automatically speed up those specific frames

**Comment by EchoesFromBeyond** [comment]
I have created this feature and submitting the PR now.
