### ISSUE TITLE
Instant Bow Charge Bugs

### ISSUE THREAD

**Issue by EchoesFromBeyond** [Akebi-Group/Akebi-GC#281]
Please contribute your issues related to the Instant Bow Charge option and how it functions on certain characters.
------------------------------------------------------------------------------------------------------
Current Known Character Issues:
Fischl - Not Working
Yelan - Not Working - See [Yelan Instant Bow Charge Bug](https://github.com/Akebi-Group/Akebi-GC/issues/92)

**Comment by TheOrangekey** [comment]
Character: Fischl
Ability Log:
19:30:28 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:30:26 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:26 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:25 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:25 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:25 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:24 | Key: _Enchanted_Time value: -5 | min: 0 | max: 0.
19:30:20 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:30:20 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:20 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:20 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:30:19 | Key: _Enchanted_Time value: -5 | min: 0 | max: 0.
19:29:54 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:53 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:53 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:52 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:29:52 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:52 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:51 | Key: _Enchanted_Time value: -5 | min: 0 | max: 0.
19:29:50 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:29:50 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:49 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:48 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:29:48 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:48 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:48 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:47 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:29:46 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:29:45 | Key: _Enchanted_Time value: -5 | min: 0 | max: 5.
19:29:45 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:45 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:45 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:44 | Key: _Enchanted_Time value: 1 | min: 0 | max: 5.
19:29:44 | Key: _Enchanted_Time value: -5 | min: 0 | max: 0.
19:29:42 | Key: _ElectricWaterLoseHp value: -10 | min: 0 | max: 6.
19:29:13 | Key: _ABILITY_BURNING_IGNITE_ONLY value: 1 | min: 1 | max: 1.
19:29:06 | Key: _SCENE_GADGET_ISSUMMON value: 1 | min: 0 | max: 1.
19:29:06 | Key: _SCENE_GADGET_ISSUMMON value: 1 | min: 0 | max: 1.
19:29:03 | Key: _ABILITY_Klee_Extra_Attack value: -1 | min: 0 | max: 1.
19:28:33 | Key: _SCENE_GADGET_ISSUMMON value: 1 | min: 0 | max: 1.
19:28:31 | Key: _SCENE_GADGET_ISSUMMON value: 1 | min: 0 | max: 1.
19:28:28 | Key: _ABILITY_CRASH_RECENTLY_CRASHED value: -10 | min: 0 | max: 1.
19:28:28 | Key: _ABILITY_CRASH_RECENTLY_CRASHED value: -10 | min: 0 | max: 1.
19:28:27 | Key: _SCENE_GADGET_ISSUMMON value: 1 | min: 0 | max: 1.
19:28:26 | Key: _ABILITY_CRASH_RECENTLY_CRASHED value: 1 | min: 0 | max: 1.
19:28:26 | Key: _ABILITY_CRASH_RECENTLY_CRASHED value: 1 | min: 0 | max: 1.
19:28:26 | Key: _ABILITY_GrapplingHookSkill_JoypadAirSkill_Mark value: -1 | min: 0 | max: 5.
19:28:25 | Key: _ABILITY_GrapplingHookSkill_JoypadAirSkill_Mark value: 1 | min: 0 | max: 5.
19:28:25 | Key: _ABILITY_GrapplingHookSkill_JoypadAirSkill_Mark value: -1 | min: 0 | max: 5.
19:28:25 | Key: _ABILITY_GrapplingHookSkill_JoypadAirSkill_Mark value: 1 | min: 0 | max: 5.

**Comment by Taiga74164** [comment]
@TheOrangekey Fischl works just fine. theres just a visual bug

**Comment by LegendofGJA** [comment]
well, my fischl character at first bow charge not working, then working
fix:
1. unchecked box of your "Instant Bow Charge"
2. test shot without "Instant Bow Charge" until arrow come out // basicaly just hold LMB then release
3. check the box of "Instant Bow Charge"
4. then test it

Mine work like that, btw u have to do that everytime u close the game / if the "Instant Bow Charge" not work with fischl

**Comment by LegendofGJA** [comment]
> > well, my fischl character at first bow charge not working, then working fix:
> > 
> > 1. unchecked box of your "Instant Bow Charge"
> > 2. test shot without "Instant Bow Charge" until arrow come out // basicaly just hold LMB then release
> > 3. check the box of "Instant Bow Charge"
> > 4. then test it
> > 
> > Mine work like that, btw u have to do that everytime u close the game / if the "Instant Bow Charge" not work with fischl
> 
> its just a visual bug for Fischl's chrage attack
> 
>  2022-08-31.07-31-53.mp4

Well thanks for the fast reply
