### ISSUE TITLE
empty fitters in new map

### ISSUE THREAD

**Issue by ATF-zero** [Akebi-Group/Akebi-GC#285]
![3 UNK)QRJW I{RG4`NA4)52](https://user-images.githubusercontent.com/53086059/179201709-f06db3db-9062-48c8-a884-f6ab3301e10f.png)

**Comment by Taiga74164** [comment]
this is a new area so we didn't have access to the data. if this map will stay forever then interactive map will be updated.

**Comment by xuewuji** [comment]
> this is a new area so we didn't have access to the data. if this map will stay forever then interactive map will probably be updated.

In fact, it has data
![6CVXF@`%N3CM9AK9Q_{3 4K](https://user-images.githubusercontent.com/40057008/179207535-3f3c00e1-82a5-4b8d-95ab-dab32f6f3a48.png)
.

**Comment by Taiga74164** [comment]
send lua

**Comment by milusocool** [comment]
> > 这是一个新领域，所以我们无法访问数据。如果这张地图将永远存在，那么交互式地图可能会被更新。
> 
> 事实上，它有数据 。 ![6CVXF@`%N3CM9AK9Q_{3 4K](https://user-images.githubusercontent.com/40057008/179207535-3f3c00e1-82a5-4b8d-95ab-dab32f6f3a48.png)

This is just a plugin for map, no data shared or something like this
