### ISSUE TITLE
Instant Furnishing, Making Food, Ores, etc.

### ISSUE THREAD

**Issue by ArthaVerx** [Akebi-Group/Akebi-GC#286]
Make it instant without waiting for a whole day, possible?

**Comment by m0nkrel** [comment]
Autocook for food

**Comment by ArthaVerx** [comment]
auto cook works with on furnishing?

**Comment by m0nkrel** [comment]
ofc no

**Comment by 2b-code** [comment]
recommend dont hide the weapon after finish the combat pliz taiga * - * would be great uwu

**Comment by Taiga74164** [comment]
not sure. dont think you can manipulate the time when making those things

**Comment by Taiga74164** [comment]
theres also a detection for when unity time is not the same as local time.

**Comment by Taiga74164** [comment]
seems undoable so ill close it for now. i'll re-open if we/someone else finds possible ways to do it
