### ISSUE TITLE
Wtf

### ISSUE THREAD

**Issue by djhashh** [Akebi-Group/Akebi-GC#292]
Wtf is this????????? Cringey af 
Maybe spend your time on something better than weeaboo trash

**Comment by tedzify** [comment]
You know what's not cringey? This ratio.

**Comment by Nobzie** [comment]
Ah yes, another hater.

You literally pointed out all the things you just did.
If you knew any better you wouldn't be creating a pointless and _"Cringey"_ issue on a repo when you could _"Maybe spend your time on something better"_

Speaking of _"weeaboo trash"_, you literally got a "cartoonizer" repo on your profile and cringe ass status _" (♥_♥) - 8===O - - ᶫᵒᵛᵉᵧₒᵤᶫᵒᵛᵉᵧₒᵤ - - ~~o - 💩 - (__{*}__) 💩"_

**Comment by Taiga74164** [comment]
lol
