### ISSUE TITLE
[Error] [main.cpp:131] Failed to create game process.. Error: 6 句柄无效。

### ISSUE THREAD

**Issue by X-oliver** [Akebi-Group/Akebi-GC#295]
I'm using the chinese version,but its not woking on v0.8.I've tried cfg.ini,still not work.

![11111](https://user-images.githubusercontent.com/30556370/179334646-b7b0ca03-4251-4bf1-b70e-5cce09b7cb8b.jpg)

**Comment by tedzify** [comment]
Is the path to GenshinImpact.exe correct? The .exe should be located at `Genshin Impact\Genshin Impact game`. And are you running the injector as `Administrator`?

**Comment by X-oliver** [comment]
> Is the path to `GenshinImpact.exe` correct? The .exe should be located at `Genshin Impact\Genshin Impact game\`. And are you running the injector as `Administrator`?

yes,i've run it as Administrator,and its my path to the game
![111111](https://user-images.githubusercontent.com/30556370/179334878-4e965e13-fe27-45da-a986-03e6b70e7ead.jpg)

**Comment by ourlib** [comment]
搁哪搞得野鸡版本，去问发布者

**Comment by CNLouisLiu** [comment]
Check your antivirus soft

**Comment by skycon8** [comment]
this doesn't looks like our official version.

**Comment by X-oliver** [comment]
> 搁哪搞得野鸡版本，去问发布者

还真不是野鸡版本，我能找到这来肯定是在这里下的啊

**Comment by X-oliver** [comment]
> this doesn't looks like our official version.

It's THE official version,I downloaded it from Releases here!

**Comment by X-oliver** [comment]
> Check your antivirus soft

I don't have a antivirus soft,only windows' default and i closed it.

**Comment by daofeng2015** [comment]
你确定你下的对的？这个他怎么检测的是国际服的名称

**Comment by CNLouisLiu** [comment]
If you haven't solved it, you can find me at dc, LouisLiu#7632

**Comment by X-oliver** [comment]
> 你确定你下的对的？这个他怎么检测的是国际服的名称

chinese和global都试了，一样的提示，明明0.7.5的时候能正常使用

**Comment by Taiga74164** [comment]
Seems to happen when you don't select the correct game.

![image](https://user-images.githubusercontent.com/67109235/179382499-39e3aeb8-9b1b-45f5-9dc8-45affea63ef5.png)

**Comment by Testingacc-now** [comment]
> 

this is a different issue the error here is 2 and what is shown on the thread is error 6
in 6 it is the correct path and in 2 it cannot find the file

**Comment by Taiga74164** [comment]
> > 
> 
> this is a different issue the error here is 2 and what is shown on the thread is error 6 in 6 it is the correct path and in 2 it cannot find the file

oh you're right

**Comment by aimoyusheng** [comment]
我也是如此，请问您解决了吗

**Comment by X-oliver** [comment]
> 我也是如此，请问您解决了吗

没有解决

**Comment by CNLouisLiu** [comment]
> > 我也是如此，请问您解决了吗
> 
> 没有解决

DC找我 我给你远程看看 LouisLiu#7632

**Comment by X-oliver** [comment]
> > > 我也是如此，请问您解决了吗
> > 
> > 
> > 没有解决
> 
> DC找我 我给你远程看看 LouisLiu#7632

可以用了，感谢！

**Comment by X-oliver** [comment]
> 我也是如此，请问您解决了吗

上面的大佬帮我把注入器就是injector.exe换成了0.7.5的就可以用了，dll还是0.8的，你试试

**Comment by louisyonge** [comment]
Same problem

**Comment by ReturnIsNull** [comment]
injector doesn't work for me after #208

i think it might caused by using windows 10 with a local user account,
since the admin account does not have explorer.exe process at the moment
not sure anyway

Solution which works for me:

1. Run `Windows PowerShell` as Administrator
2. Execute `injector.exe` in the PowerShell window you opened

or, i made a script, just unzip
[script.zip](https://github.com/Akebi-Group/Akebi-GC/files/9301388/script.zip)
run `run.ps1` with powershell and select injector.exe you use. it works well for me.

**Comment by Shichiha** [comment]
(or sign the other user off)
