### ISSUE TITLE
Geo Sigil show both tag (Geo Sigil/Search Point)

### ISSUE THREAD

**Issue by CR4Player** [Akebi-Group/Akebi-GC#307]
Tags stacking when Seach Point and Geo Sigil in ESP are both enabled.
<img width="243" alt="Snipaste_2022-07-17_14-39-11" src="https://user-images.githubusercontent.com/12210261/179387188-8ba3ef14-6a40-466c-a57e-55b03d17b4cd.png">

**Comment by Taiga74164** [comment]
where's this in the map

**Comment by CR4Player** [comment]
> where's this in the map

Mingyun Village in Liyue.
<img width="654" alt="image" src="https://user-images.githubusercontent.com/12210261/179388684-25ee3473-38c3-48c3-990f-852db858da9f.png">

**Comment by Taiga74164** [comment]
ah i see. because it gives both 🤣 

![image](https://user-images.githubusercontent.com/67109235/179393950-8ab5fe94-1555-44ba-b0a3-dd684e78245b.png)

**Comment by m0nkrel** [comment]
It's because Geo sigils is like a subpart of searching points, like floating boxes
