### ISSUE TITLE
Element attachment does not work properly when Multi-hit Mode is enabled|当Multi-hit Mode启用时，元素附着工作不正常

### ISSUE THREAD

**Issue by zhaopinglai** [Akebi-Group/Akebi-GC#308]

**Comment by zhaopinglai** [comment]
> 当Multi-hit Mode启用时，使用能造成元素附着的普攻攻击某个能作用Multi-hit的物体，攻击不会造成元素附着或只会造成一次元素附着（我没有进行太多测试） When Multi-hit Mode is enabled, use a basic attack that causes an elemental attachment to attack a multi-hit object, the attack will not cause an elemental attachment or will only cause once elemental attachment (I didn't do much testing)

**Comment by Thafoxes** [comment]
More info on the issue:

Only a specific character will have this issue, xiao for example.

https://gofile.io/d/49mWQq

video above is the proof

**Comment by zhaopinglai** [comment]
我的意思是元素不会正常附着...我使用了砂糖和丽莎，当Multi-hit启用时砂糖第一次普攻没有触发扩散
后面我又调整了Multi-hit的次数，没有明显规律，目前是砂糖的普攻、丽莎的普攻和短e有这个问题
