### ISSUE TITLE
Smarter name filter in [Debug -> Entity Manager]

### ISSUE THREAD

**Issue by Philoxophy** [Akebi-Group/Akebi-GC#31]
The current name filter won't match entities unless I type correct leading name like "SceneObj_blah blah blah" which is really long and inconvenient. I want to be able to type just short keywords and see what I want to see.

**Comment by Taiga74164** [comment]
you can literally do it yourself 💀

**Comment by WitchGod** [comment]
Man, after writing 500 lines of code, it's still not smart enough? I quit ☠️

**Comment by Philoxophy** [comment]
> You don't need to type all of that... for example the entity you're searching for is `SceneObj_SakuraBloom`, you can just search for `Sakura` or `Bloom` it doesn't have to be the whole thing. Note that it's case sensitive.

Yeah, lol. I just noticed now that this thing is case-sensitive. Thank you for all the attention though.
