### ISSUE TITLE
Auto Time Trial Challenge particles

### ISSUE THREAD

**Issue by Zatix-rus** [Akebi-Group/Akebi-GC#314]
Create a function that would teleport time trial challenge particles to the character.
The particle name in debug SkillObj_EmptyGadget(Clone) authority :True

**Comment by m0nkrel** [comment]
huh?

**Comment by Zatix-rus** [comment]
> хм?

It's just that there are 2 types of time trials in Inazuma, kill monsters and collect particles. For the first one there is killaura, but no nothing for a quick collection of particles.

**Comment by Ayiemfyloo** [comment]
Not everything need to be made auto.. You can use debug menu to find it and summon them to the active chara

**Comment by Zatix-rus** [comment]
> Вы хотите это?
> 
>  тест.mp4

Yes

**Comment by m0nkrel** [comment]
> @m0nkrel ahh i see. Now i know it can be use for that too. Thanks again for that 🙏🏻

it's not implemented for now. I used AutoSeelie checkbox for fast debugging. I'll do separate block for it
