### ISSUE TITLE
What any not to do？

### ISSUE THREAD

**Issue by clCata** [Akebi-Group/Akebi-GC#315]
What any not to do？Like some game modes

**Comment by clCata** [comment]
OK

**Comment by clCata** [comment]
![image](https://user-images.githubusercontent.com/105795611/179676828-e91d716f-355c-4696-8d8a-7429c0a5eb27.png)
![image](https://user-images.githubusercontent.com/105795611/179676829-acc77b85-7288-42c5-a9fb-7838fbff3496.png)
Can these be used?

**Comment by Fanixtar** [comment]
you shouldn't use it in abyss since most of the data is recorded/logged
