### ISSUE TITLE
visuals>TextureChanger 

### ISSUE THREAD

**Issue by LipaSuiRed** [Akebi-Group/Akebi-GC#318]
Have a question, where i can find skin files for texture changer in visuals, i found some on gamebanana but it is for a private server

**Comment by Taiga74164** [comment]
> Have a question, where i can find skin files for texture changer in visuals, i found some on gamebanana but it is for a private server

use [GI_Assets](https://github.com/zeroruka/GI_Assets)

the one in game banana you have to use [3dmigoto](https://github.com/SilentNightSound/GI-Model-Importer) by our friend @SilentNightSound ❤️
