### ISSUE TITLE
Cannot interact with object in `NoClip`

### ISSUE THREAD

**Issue by thelostabbey** [Akebi-Group/Akebi-GC#32]
Is there a way to allow the player interact with items/objects/people while in noclip mode?
while in noclip, you aren't able to collect orbs/particles from open-world trials and can't interact with objects/NPC's.

**Comment by thelostabbey** [comment]
> Don't you just need to turn on Freeflight Mode?
i see no such option
![image](https://user-images.githubusercontent.com/48223004/170329830-dc933fd9-f424-4f5a-8567-73e288651138.png)

**Comment by CallowBlack** [comment]
I reopen it, because this problem exist.

**Comment by qiaozhi-4** [comment]
> > 你不只需要打开自由飞行模式吗？
> 
> 编辑：我看到它有一个热键，但它不在 noclip 的选项下。使用热键启用似乎可以按照这里的要求工作。



> > 你不需要只打开自由飞行模式吗？
> 
> 编辑：我看到它有一个热键，但它不在noclip选项下。使用热键启用的似乎可以按照这里的要求工作。

what is the hotkey?

**Comment by qiaozhi-4** [comment]
> > 你不需要只打开自由飞行模式吗？
> 
> 编辑：我看到它有一个热键，但它不在热键选项下。使用键启用的看起来可以按照这里的要求工作。

what is the hotkey?
请问是那个热键，
