### ISSUE TITLE
Nothing happens when I try to run a cheat

### ISSUE THREAD

**Issue by btfspace** [Akebi-Group/Akebi-GC#321]
Running the file injector.exe, an inscription appears that successfully injected LoadLibraryA, then the console closes, the game starts and nothing happens: the console does not appear, nothing comes out in the game when pressing F1.

OS: Win 11

**Comment by Helltu** [comment]
Same issue

**Comment by btfspace** [comment]
> Same issue

So, i solved this, just downgrade to Win 10, it worked for me

**Comment by Helltu** [comment]
Nice fix, thx
