### ISSUE TITLE
1."Attach/detattach" what is the work for this button.
2.should I tick the disable protection ? 

### ISSUE THREAD

**Issue by Badsha71** [Akebi-Group/Akebi-GC#326]
![IMG20220720142943.jpg](https://user-images.githubusercontent.com/57755184/179935566-dff6af54-04b3-4d01-9338-53f43f9187b4.jpg)![IMG20220720142933.jpg](https://user-images.githubusercontent.com/57755184/179935579-9819ed66-1a8f-43bb-87ff-9f8afdc431a3.jpg)

**Comment by Taiga74164** [comment]
1. It attaches your config to your account
2. Yes. You need to enable it unless you have another way to bypass the checksum on PlayerLogin

**Comment by Badsha71** [comment]
Thanks it help
