### ISSUE TITLE
Add Control Animation

### ISSUE THREAD

**Issue by ArthaVerx** [Akebi-Group/Akebi-GC#347]
Add an Idle Animation control. so you can do it without waiting. if its possible

**Comment by ArthaVerx** [comment]
Also skip custscene bosses like azhdaha

**Comment by Taiga74164** [comment]
![image](https://user-images.githubusercontent.com/67109235/180989374-42e6e423-bac7-4190-bd59-7dcc142cbda7.png)

**Comment by ArthaVerx** [comment]
Ehe
