### ISSUE TITLE
Auto Loot Bug

### ISSUE THREAD

**Issue by ArthaVerx** [Akebi-Group/Akebi-GC#348]
when the range is above 40, you cant collect items. is it a bug or just the limit?

**Comment by hellomykami** [comment]
Because the server will not send item information after the range exceeds a certain limit , so i think the range is 40m

**Comment by RyujinZX** [comment]
> Because the server will not send item information after the range exceeds a certain limit , so i think the range is 40m

That's right.

**Comment by ArthaVerx** [comment]
I see, thank you :D

**Comment by EchoesFromBeyond** [comment]
You also shouldn't be using that large of a range. That will get you banned very quick. Read the instructions.
