### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by pikachu0621** [Akebi-Group/Akebi-GC#350]
I want to consult the clibrary compiled by myself DLL prompt is not a WIN32 program. Is there any way to solve it
![image](https://user-images.githubusercontent.com/28878309/180601393-37f7f3e9-b961-491c-b6a4-c8901d646709.png)

**Comment by Micah123321** [comment]
目前没有什么办法,因为要先编译dll再运行注入器,然后vs默认运行了编译文件 除非手动生成 不运行dll 
Currently there is nothing to be done because the DLL is compiled before the injector is run, and vs runs the compiled file by default unless the DLL is manually generated and not run

**Comment by pikachu0621** [comment]
> 目前没有什么办法,因为要先编译动态链接库再运行注入器,然后相对默认运行了编译文件 除非手动生成 不运行动态链接库目前不需要做什么，因为DLL是在注入器运行之前编译的，默认情况下vs运行编译的文件，除非DLL是手动生成的并且没有运行

因为我是个小白，想简单翻译下 ，但是这个问题解决不了。如果可以我希望能用你翻译好的 ^_^
Because I'm a novice, I want to translate simply, but this problem can't be solved. If I can, I hope I can use your translation ^_^

**Comment by Fanixtar** [comment]
are you still using windows 32 bit? install the 64 one

**Comment by pikachu0621** [comment]
> are you still using windows 32 bit? install the 64 one

I am using windows 64 bit
![1658799762797](https://user-images.githubusercontent.com/28878309/180904885-b1a6aa05-e3f9-4073-8d2d-ea0bbdc1edfc.jpg)

**Comment by Taiga74164** [comment]
https://stackoverflow.com/questions/48602869/unable-to-start-program-value-dll-is-not-a-valid-win32-application-error-in-v

**Comment by Taiga74164** [comment]
Happened to a friend as well.. Launch the injector manually instead of using Post-Build Event
