### ISSUE TITLE
NPC display filter running in ESP, which caused some item names not to appear

### ISSUE THREAD

**Issue by Micah123321** [Akebi-Group/Akebi-GC#351]
[](url)- There is a problem with the NPC display filter running in ESP, which caused some item names not to appear
```c
					if (entry.m_Name == "Npc" || "AvatarOwn" || "AvatarTeammate")
					{
						auto name = entity->name();
						GetNpcName(name);
						esp::render::DrawEntity(name, entity, entry.m_Color, entry.m_ContrastColor);
						break;
					}
```
There is a problem with the name judgment here

![](https://oss.xiaomao6.com/mkoss/2022/07/23/18caf18c.png)
![](https://oss.xiaomao6.com/mkoss/2022/07/23/c41e98e7.png)

**Comment by m0nkrel** [comment]
It's fixed in #340
