### ISSUE TITLE
Genshin impact does not start

### ISSUE THREAD

**Issue by eternaldespair22** [Akebi-Group/Akebi-GC#352]
![image](https://user-images.githubusercontent.com/109737945/180603143-b0ed9a86-5747-4ba9-8944-ed4acc0b9bda.png)
On windows 11 cmd just prints these 2 lines and crashes and genshin doesn't run

**Comment by eternaldespair22** [comment]
I updated the video card drivers, turned off the antivirus, the path to the game was laid correctly, ran the injector as administrator, rebooted the computer, MSI AfterBurner and RivaTuner were not downloaded.

**Comment by daofeng2015** [comment]
hook d3d close msi

**Comment by eternaldespair22** [comment]
I don't have MSI AfterBurner

**Comment by tanxiaofx** [comment]
On windows11 is working maybe your system have problem
