### ISSUE TITLE
In ImGui::InputText() in this project, there is no way to call the input method for other languages

### ISSUE THREAD

**Issue by Micah123321** [Akebi-Group/Akebi-GC#353]
我尝试了各种输入法,都不能在ImGui::InputText正常输入其他语言 包括微软,搜狗等等
但是在官方的案例中,就可以正常输入,请问有办法可以解决吗
I have tried various input methods, but none of them can input normally in ImGui::InputText. Other languages include Microsoft, Sogou and so on
But in the official case, it can be input normally. Is there any way to solve it

![](https://btxo.cn/oss/2022-07-23/3f51bd4b.png)

![](https://btxo.cn/oss/2022-07-23/323eb444.png)

**Comment by tanxiaofx** [comment]
这是要汉化的节奏吗（苦笑

**Comment by Ligture** [comment]
能教一下怎么弄的吗,我使用中文字体就崩溃了
