### ISSUE TITLE
UserAssembly.dll isn't initialized.

### ISSUE THREAD

**Issue by Liujunhua007** [Akebi-Group/Akebi-GC#356]
use action latest 2.8.5x and my client is 2.8.50
![QQ图片20220724203309](https://user-images.githubusercontent.com/62129047/180647226-bd03ae4f-3134-469e-88a0-a48c27524960.png)

**Comment by tanxiaofx** [comment]
好像不支持国服 别想了

**Comment by tanxiaofx** [comment]
![IMG_20220724_225249.jpg](https://user-images.githubusercontent.com/68837376/180653468-457a4746-c976-4b14-baf4-3c30594f4426.jpg)

**Comment by Taiga74164** [comment]
the current build in Actions page only supports OS/CN 2.8.51 and OS 2.8.52
