### ISSUE TITLE
no-Clip

### ISSUE THREAD

**Issue by qiaozhi-4** [Akebi-Group/Akebi-GC#358]
Can't talk when the no-clip function is turned on

**Comment by zhouqingyi1127** [comment]
我的也是

**Comment by EchoesFromBeyond** [comment]
This is a known bug, please read through the Issues before submitting new ones. It usually is fixed by restarting. Sometimes you will get into a bugged state.

**Comment by qiaozhi-4** [comment]
> fixed

ok
好的👌🏻

**Comment by Taiga74164** [comment]
duplicate of #32
