### ISSUE TITLE
idk

### ISSUE THREAD

**Issue by NotEvenYami** [Akebi-Group/Akebi-GC#362]
![image](https://user-images.githubusercontent.com/99720335/180680261-2d7ab8c9-56bd-4ca0-b654-77311f0cb6ae.png)

**Comment by NotEvenYami** [comment]
it's still generating more like that:/

**Comment by NotEvenYami** [comment]
Sometimes while using the map,i also need to click on the game once to exit using the esc button:/,After that my character will go in a strange line even though i dont press the "W" button

**Comment by m0nkrel** [comment]
It's harmless. Ignore it

**Comment by NotEvenYami** [comment]
what about the auto walk straight one?

> It's harmless. Ignore it

**Comment by m0nkrel** [comment]
Tell me, how to reproduce this bug

**Comment by NotEvenYami** [comment]
> Tell me, how to reproduce this bug

idk either

**Comment by NotEvenYami** [comment]
![image](https://user-images.githubusercontent.com/99720335/180681046-a2ae3c4a-fb0d-4878-9247-39d904d48fab.png)
the auto walk straight start whenever i use the"chest teleport" or custom teleport

**Comment by Taiga74164** [comment]
at least give us a better title and try to elaborate more

**Comment by zhouqingyi1127** [comment]
hello. i experience this with hide ui
