### ISSUE TITLE
[feat. request] Allows players to attack each other

### ISSUE THREAD

**Issue by Wansn-w** [Akebi-Group/Akebi-GC#363]
for well-known reasons, my friends and I, who are tired of the existing way of playing the game, are looking for ways to try to discover new ones. we [saw it](https://www.bilibili.com/video/BV16F411M7Qi) on the Bilibili... some kind of program makes it possible for players to attack each other.

**Comment by Taiga74164** [comment]
does free fire actually exist in this game 💀💀💀💀💀💀

**Comment by Wansn-w** [comment]
> does free fire actually exist in this game 💀💀💀💀💀💀

just watch [THIS VIDEO](https://www.bilibili.com/video/BV16F411M7Qi)... But idk which program the player use😕😕😕

**Comment by NctimeAza** [comment]
这种功能对游戏环境影响挺大的，不如去国内买挂，他们都实现了这种功能

**Comment by Wansn-w** [comment]
> 这种功能对游戏环境影响挺大的，不如去国内买挂，他们都实现了这种功能

确实... 不过本来就是想开个房间互相打着玩XD

**Comment by tanxiaofx** [comment]
笑死我了想互相伤害是吧

**Comment by QinCaii** [comment]
这很容易搞乱游戏环境从而让官方重视此程序，这是损人不利己的事情
