### ISSUE TITLE
UI getting messed up

### ISSUE THREAD

**Issue by GarethOz** [Akebi-Group/Akebi-GC#37]
I don't know if this is from the program or the game itself.
![image](https://user-images.githubusercontent.com/104610042/170575693-f76f94aa-8861-4ba2-8c97-88a87820beb7.png)

**Comment by Fractune** [comment]
I got this issue as well when I entered The Chasm or teleported while I was in there, I don't recall exactly how I produced that.

**Comment by CallowBlack** [comment]
Duplicate of #15
