### ISSUE TITLE
UserAssembly.dll isn't installed On Windows 10

### ISSUE THREAD

**Issue by mantadddddd** [Akebi-Group/Akebi-GC#370]

**Comment by mantadddddd** [comment]
UserAssembly.dll isn't installed

**Comment by tedzify** [comment]
`UserAssembly.dll` comes with the game.

![image](https://user-images.githubusercontent.com/99535026/180852263-d5a94c07-1b9c-4dd9-b3fc-e4732ae28b5a.png)
