### ISSUE TITLE
Not working on Win 11

### ISSUE THREAD

**Issue by alhrmss** [Akebi-Group/Akebi-GC#374]
Hi, i run the EXE and i open it and it just saw a black screen and it disappears

**Comment by Lunairayz** [comment]
on win11 dev insider here

are u sure u got the prerequisites installed

**Comment by alhrmss** [comment]
yes everything is good and i follow this video

https://www.youtube.com/watch?v=vwMT5iwVe9g&ab_channel=FractuneCh.

**Comment by Lunairayz** [comment]
mentally stable people don't build from source anymore

[go here](https://github.com/Akebi-Group/Akebi-GC/actions?query=branch%3Amaster), click the latest and then "akebigc-release" at the bottom or something

**Comment by alhrmss** [comment]
it's not working, pls look at the video I made now

https://streamable.com/em0zt3

**Comment by Lunairayz** [comment]
alright that's quite interesting now
just to double check you [installed these](https://github.com/Akebi-Group/Akebi-GC#requirements) right? 

and, my guess is that the injector cant even find where game files are
try throwing [this](https://cdn.discordapp.com/attachments/953633258984333313/1001822077550088212/cfg.ini) into the folder (change the address with the location of your game, if edited)

**Comment by alhrmss** [comment]
yes i [installed these] 

look where is it 

![Uploading image.png…]()

**Comment by alhrmss** [comment]
![image](https://user-images.githubusercontent.com/25882209/181243209-54c699b0-9b6d-43fd-b045-6ee3af71e0c1.png)

**Comment by alhrmss** [comment]
C:\Games\Genshin Impact

**Comment by alhrmss** [comment]
i did this but didnt work

[Inject]
GenshinPath = C:\Games\Genshin Impact\launcher.exe

**Comment by Thafoxes** [comment]
Please inject in this file path C:\Program Files\Genshin Impact\Genshin Impact game

**Comment by RyujinZX** [comment]
> i did this but didnt work
> 
> [Inject] GenshinPath = C:\Program Files\Genshin Impact\Genshin Impact game\GenshinImpact.exe

**Comment by Lunairayz** [comment]
![unknown-1](https://user-images.githubusercontent.com/45308130/181244596-281bb481-0d85-4663-a145-7ed30e0379de.png)

**Comment by alhrmss** [comment]
i move the game folder to C:\Program Files\Genshin Impact and i use the C:\Games\Genshin Impact\Genshin Impact game\GenshinImpact.exe and not working

**Comment by alhrmss** [comment]
![image](https://user-images.githubusercontent.com/25882209/181245093-d49ae782-822a-48c0-bf78-6e7a0cd32799.png)

**Comment by alhrmss** [comment]
![image](https://user-images.githubusercontent.com/25882209/181245260-e2ab47f6-62d0-4610-8b18-280a1264847c.png)

**Comment by Thafoxes** [comment]
> ![image](https://user-images.githubusercontent.com/25882209/181245260-e2ab47f6-62d0-4610-8b18-280a1264847c.png)

same issue happen? ( closed instantly after open)

**Comment by RyujinZX** [comment]
> ![image](https://user-images.githubusercontent.com/25882209/181245260-e2ab47f6-62d0-4610-8b18-280a1264847c.png)

Is cfg.ini in the injector folder?

**Comment by Thafoxes** [comment]
make sure you have these installed properly
![image](https://user-images.githubusercontent.com/43284628/181246194-75d302af-be43-44ff-820a-c7eeaea6858f.png)

you can get it from here 
https://aka.ms/vs/17/release/vc_redist.x64.exe
https://aka.ms/vs/17/release/vc_redist.x86.exe

**Comment by alhrmss** [comment]
> 

yes

> cfg

yes


![image](https://user-images.githubusercontent.com/25882209/181246308-0efb6ba2-7b04-43fc-ac14-beadd216603a.png)



> make sure you have these installed properly ![image](https://user-images.githubusercontent.com/43284628/181246194-75d302af-be43-44ff-820a-c7eeaea6858f.png)
> 
> you can get it from here https://aka.ms/vs/17/release/vc_redist.x64.exe https://aka.ms/vs/17/release/vc_redist.x86.exe

i have both

**Comment by alhrmss** [comment]
any help guys :(

**Comment by Thafoxes** [comment]
restart your pc, then try again. If problem continue try delete all the akebi software then paste a new one from the zip file

**Comment by alhrmss** [comment]
i did that 4 times

**Comment by alhrmss** [comment]
and i have just 4 files in Akebi-GC folder

![image](https://user-images.githubusercontent.com/25882209/181248985-79e896b2-ef3f-4f28-b634-df2432ed33ab.png)

**Comment by Thafoxes** [comment]
not sure if this is a problem, is your pc in arabic as main display language ? Try to change evrything to US english, might solve a bit of variables here

**Comment by alhrmss** [comment]
everything in English

**Comment by alhrmss** [comment]
anyone

**Comment by FawazTakhji** [comment]
did you use something like a debloater or installed a custom version of windows 11 ?

**Comment by alhrmss** [comment]
No

**Comment by alhrmss** [comment]
I use just normal win 11

**Comment by alhrmss** [comment]
anyone :)

**Comment by alhrmss** [comment]
:_

**Comment by MemesPwr** [comment]
for first, try to put folder with akebi to root of C:\

if don't helps, try to disable Hyper-V, reboot, then try, if still don't works, disable smart-screen and anti-malware software. maybe it can help you...

it everything don't helps, re-enable everything you're disabled.

e.g. disabled Hyper-V breaks WSL2 and/or WSA

**Comment by EchoesFromBeyond** [comment]
Sadly this happened with me with the latest update of Windows 11 as well, starting a few weeks ago. I had to downgrade to Windows 10 to get it working, I think something in some windows update caused it but i'm not sure which, i would recommend we have some debug logs to see what's going on.

**Comment by Lunairayz** [comment]
I'm on win11, dev channel on insider, and everything is working perfectly for me
not gonna blame you but maybe ya fucked something up lole

**Comment by KanzoHattori** [comment]
>stop using multiple accounts, logout from all, keep yo main and then try to run, it fixed mine :)
>stop defender from services.
and it works perfectly fine eh.
>avoid "co-op" for banning issue rightt.

OR go play legit mate, hack's for fun not permanency, you''ll lose yo account before ar55 either ways.
