### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by RhythmLunatic** [Akebi-Group/Akebi-GC#378]
The tool actually works fine in Linux but the GUI doesn't render due to dxvk presumably skipping the injection. You can still enable and disable the cheats by editing the cfg.

To use the tool on Linux, install wine-proton-ge then do `winetricks corefonts vcrun2019 dxvk1102 usetakefocus=n`

You can skip dxvk but Genshin's shaders are broken anyways and it will crash when using akebi due to the directx injection.

Also injector.exe causes input to break when alt tabbing but I think this is not a big issue and is more of a problem with wine.

P.S. game also works in steam with steam overlay, use protontricks and STEAM_COMPAT_MOUNTS if game is not inside the directory where akebi is.

**Comment by Taiga74164** [comment]
modify ur cfg. and bind those hotkeys for now :copium:

**Comment by phineas-pta** [comment]
hi @9xeqt8YziSbF4c do you only use wine to launch the anime game or patch it with the anime launcher?

**Comment by phineas-pta** [comment]
Thanks, I can confirm it works, even with mangohud and vkbasalt enabled

**Comment by KryptoSynth0** [comment]
Can you elaborate on how you got your setup working?

I tried to launch the injector.exe through steam and lutris but it either launched the game without getting injected or crashed on launch. 

Are there any specific arguments I need to use in steam or lutris?

**Comment by phineas-pta** [comment]
@KryptoSynth0 have you properly patched it? does it launch normally (without injector)?

**Comment by KryptoSynth0** [comment]
Yes the game launches properly through both steam and lutris without glitches, I just can't figure out the injector.

**Comment by phineas-pta** [comment]
for my case I modify the launcher script: replace the original exe with injector

**Comment by KryptoSynth0** [comment]
I figured out what was causing my crashes; MangoHud.

Having Mango hidden by default makes the game freeze and exit in the main screen(Server select).

Having Mango shown by default makes the akebi GUI not load but the game loads and cheats still work.

Having Mango hidden by default, then bringing it up during the main screen with its hotkey makes akebi GUI work as intended and the game doesn't freeze either.

I have the game set up with Lutris.
