### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by isa-ardi** [Akebi-Group/Akebi-GC#379]
My game crash after the cheat started. It crashes on warning screen about epilepsy

**Comment by 1103384090** [comment]
me too

**Comment by 1103384090** [comment]
Seems like assembly checksum don't match with version 2.8. It's normal only if you using Chinese version of genshin impact.

**Comment by isa-ardi** [comment]
What is genshin chinese version? I think i use the regular one

**Comment by 1103384090** [comment]
It's just not work

**Comment by ArthaVerx** [comment]
You can fix it by
- Disable one of the grapich card driver if u have 2
- Fix your calendar and time (works for some reason)

**Comment by Baysul** [comment]
I'm also experiencing this problem. Syncing my time/date and disabling my second GPU did not resolve this issue.

I'm using a 6700 XT with the 22.Q2 AMD drivers - though I'm not sure why that'd matter. I am using Grasscutter if that makes a difference.

**Comment by isa-ardi** [comment]
Did you guys using windows 11?

**Comment by 1103384090** [comment]
> 你们用的是windows 11吗？

yeah

**Comment by isa-ardi** [comment]
> > 你们用的是windows 11吗？
> 
> yeah

Have u tried using windows 10?

**Comment by Tizzi** [comment]
crash often after play a while. usually when use E skill

**Comment by angelothehuman** [comment]
Well, im using windows 11 and aways i open the injector the game starts and on loading screen the game just crash and appears a warning "Seems like assembly checksum don't match with version 2.8. It's normal only if you using Chinese version of genshin impact.". But im using the right version of genshin and release of GC

**Comment by ImWarangelus** [comment]
![image](https://user-images.githubusercontent.com/55113782/183267417-6176eeea-3b09-4392-bf4f-61aa9f76a001.png)

**Comment by ImWarangelus** [comment]
![image](https://user-images.githubusercontent.com/55113782/183267438-0b1182e1-2c21-44c4-b8ed-bdda36607abe.png)
![image](https://user-images.githubusercontent.com/55113782/183267443-ba5463f1-b25d-40a2-98cb-a93565dbc801.png)

**Comment by ImWarangelus** [comment]
![image](https://user-images.githubusercontent.com/55113782/183267465-2842b88d-e4cd-4117-abb6-b3f24330697b.png)
![image](https://user-images.githubusercontent.com/55113782/183267467-d8e16fe2-3db2-4113-8be9-bcf6f401f759.png)
![image](https://user-images.githubusercontent.com/55113782/183267512-0c9e465e-cec1-4e01-8514-52ae9dfd6e3b.png)

**Comment by isa-ardi** [comment]
I found the problem if u crash in warning screen about epilepsy. The problem is ur driver. Try update it from website.
