### ISSUE TITLE
在chinese-2.8分支中，冻结（元素反应）无效，时间暂停（原版）无效

### ISSUE THREAD

**Issue by zhaopinglai** [Akebi-Group/Akebi-GC#383]
当我使用 259dc9c 时，冰和水造成的冻结不能使怪物停止动作
使用v0.8 release时正常

**Comment by 1103384090** [comment]
How did you get into the game? Don't you get stuck?

**Comment by 1103384090** [comment]
I get stuck in the reading screen and no response

**Comment by zhaopinglai** [comment]
当我使用 259dc9c 启动游戏时，大部分本应能让时间暂停的行为都无法使时间暂停，可能是同一个bug引起的（我没有在联机状态下测试）

**Comment by Thafoxes** [comment]
我想知道多一点资料， 你是用大陆版 还是国际版。 当时你开了什么按键？

**Comment by zhaopinglai** [comment]
> 我想知道多一点资料， 你是用大陆版 还是国际版。 当时你开了什么按键？
我正在使用大陆版，我使用了Sprint NoCD和ESP

**Comment by Thafoxes** [comment]
> 当我使用 [259dc9c](https://github.com/Akebi-Group/Akebi-GC/commit/259dc9cdddd4bfcd0e7f042f92c3c99c51e71b18) 启动游戏时，大部分本应能让时间暂停的行为都无法使时间暂停，可能是同一个bug引起的（我没有在联机状态下测试） Freeze Enemies有效

刚刚看了你的edit 你说freeze enemies 有效了，所以现在问题是 freeze enemies 开启然后元素反应无效还是什么？

**Comment by zhaopinglai** [comment]
> > 当我使用 [259dc9c](https://github.com/Akebi-Group/Akebi-GC/commit/259dc9cdddd4bfcd0e7f042f92c3c99c51e71b18) 启动游戏时，大部分本应能让时间暂停的行为都无法使时间暂停，可能是同一个bug引起的（我没有在联机状态下测试） Freeze Enemies有效
> 
> 刚刚看了你的edit 你说freeze enemies 有效了，所以现在问题是 freeze enemies 开启然后元素反应无效还是什么？

Freeze Enemies这个作弊功能可以正常运行，但无论Freeze Enemies开启或关闭大世界中的怪物不会被原版的机制暂停

**Comment by NctimeAza** [comment]
因为冰冻或者暂停游戏会把人物与怪物的动画速度设为0。但FreezeEnemies里有一个if-else语句，当Freeze Enemies功能关闭时会把怪物的动画速度设为1，就导致了这种情况。我的编程水平很差，不知道该如何去解决该bug

**Comment by Thafoxes** [comment]
好的明白，刚刚有人发了类似的问题。我会把视频放在这里当作存档。
https://gofile.io/d/MADdfP

**Comment by z7087** [comment]
我使用了https://github.com/Akebi-Group/Akebi-GC/commit/582f5e31fa75c192868e7acba2c3fdeada4871fd，角色自身还是不能被暂停，在冻结时会继续动作。
