### ISSUE TITLE
cheat not inject or work

### ISSUE THREAD

**Issue by 2DxT** [Akebi-Group/Akebi-GC#385]
hello, i start injector and my game opens normally but cheat didn't appears when i press f1 or insert
![5645646](https://user-images.githubusercontent.com/110226224/181727907-f644b5fe-2530-434b-9b8d-37707746582c.PNG) (console ss)

**Comment by tedzify** [comment]
Disable any active overlays you have (msi afterburner, rivertuner, amd software, geforce experience etc.) before you open game with akebi. Check similar issues #189 #264.
