### ISSUE TITLE
Failed to create process

### ISSUE THREAD

**Issue by Muclek** [Akebi-Group/Akebi-GC#392]
i just ran the exe, idk what i did wrong
![image_2022-07-30_213832760](https://user-images.githubusercontent.com/42284618/181995464-64e5ffe4-1ac2-4266-ab1e-e79553c3fea8.png)

**Comment by m0nkrel** [comment]
read 1st and 4th line

**Comment by Lunairayz** [comment]
> read 1st and 4th line

ah yes genshin path not found and "filed to open genshinimpact process"

**Comment by Muclek** [comment]
But i did point the genshin exe

**Comment by m0nkrel** [comment]
You sure that exe is \Genshin Impact\Genshin Impact game\GenshinImpact.exe ?

**Comment by Muclek** [comment]
yeah

**Comment by caliph9k** [comment]
I also am having this issue, was working fine yesterday and today it doesn't.

I tried removing the cfg.ini file and running again. It prompts me for the path, I select the exe file and same error (and no new cfg.ini).

OS: Windows 11 Pro, 64-bit (21H2, with Exp Pack 1000.22000.795.0)

**Comment by Muclek** [comment]
Update: Now it only shows the red text after i used cfg.ini to show where genshinimpact.exe is located, and i run the injector.exe as admin.

**Comment by caliph9k** [comment]
Tried it again today and it just worked. Obviously something changed in the environment (Windows 11, Defender or something).

**Comment by Shichiha** [comment]
this issue happened to me like an hour ago  
and got fixed???  

things that might have fixed it:  
- there was another user running  (i closed it)  
- i verified game files (from the official launcher)

**Comment by Muclek** [comment]
sorry i havent closed the issue, but i fixed it by running it using the admin account.

**Comment by Shichiha** [comment]
Having 2 Users Logged in causes this issue  
To Fix it, simply log out the other account which you aren't using
