### ISSUE TITLE
Is there any cheat leftover?

### ISSUE THREAD

**Issue by GarethOz** [Akebi-Group/Akebi-GC#393]
Finally got banned for 1 month and can't use it on my main anymore. I wanna know if it's completely safe to play my main when it's unbanned, like does the cheat have any leftover or leaves any modified file in the game directory or anything that would cause another ban when playing without it? sry for asking bcuz I dont wanna get banned for 15 years

**Comment by keexers** [comment]
???? the point of cheating is to get banned, no matter what cheat it is

**Comment by GarethOz** [comment]
> ???? the point of cheating is to get banned, no matter what cheat it is

I wouldn't agree with that but still I don't think u understood what I meant.
I cheated on my main and got 1 month ban. When I get unbanned and play without cheat, am I going to be banned again because of the cheat leftovers or not? Because some cheats leave some modified files and configs inside the game directory and if those are detected, you're screwed, even though you aren't using the cheat anymore.

**Comment by keexers** [comment]
> > ???? the point of cheating is to get banned, no matter what cheat it is
> 
> I wouldn't agree with that but still I don't think u understood what I meant. I cheated on my main and got 1 month ban. When I get unbanned and play without cheat, am I going to be banned again because of the cheat leftovers or not? Because some cheats leave some modified files and configs inside the game directory and if those are detected, you're screwed, even though you aren't using the cheat anymore.

if its genshin, no. because when it bans you it only bans your account not your pc hwid, it wont ban you again when you play it without cheats on genshin nor any other game that has no hwid bans
