### ISSUE TITLE
123

### ISSUE THREAD

**Issue by wokkkyd** [Akebi-Group/Akebi-GC#394]
![image](https://user-images.githubusercontent.com/110319387/182009091-3ee6cc72-6e3f-419c-884d-e2f81fd98f67.png)

**Comment by daofeng2015** [comment]
> ![image](https://user-images.githubusercontent.com/110319387/182009091-3ee6cc72-6e3f-419c-884d-e2f81fd98f67.png)

You didn't even choose the right path to run
