### ISSUE TITLE
Unable to inject into Chinese version 无法注入中国版

### ISSUE THREAD

**Issue by Mppedoers** [Akebi-Group/Akebi-GC#395]
我尝试了2种方法
第一种是别人编译好了的
不过会未响应 在详阅事项那里 不管按什么都没有用
第二种就是使用作者发布的chinese版本
我自己编译之后会崩掉游戏
![QQ截图20220731151622](https://user-images.githubusercontent.com/106415120/182018480-3e78e862-84bd-4997-a820-6ef111e5f908.png)
有没有人知道怎么办

**Comment by daofeng2015** [comment]
你确定用对版本？主分支默认是国际服的

**Comment by Mppedoers** [comment]
> 你确定用对版本？主分支默认是国际服的

对的吧 刚刚回复回复错了

**Comment by Sthhus** [comment]
Chinese version has no source code, since you compiled it yourself, so that is the international version
