### ISSUE TITLE
Compile Error (*Another*)

### ISSUE THREAD

**Issue by G1DE30N** [Akebi-Group/Akebi-GC#40]
![image](https://user-images.githubusercontent.com/104440397/170608838-e2639e78-986f-4e10-a4b4-962a577f5c1e.png)

57c2ff0db5eff81c5fdf55d219a2e884db1f7c57 Release(WS)

BUT Release (Without Scanner) compiled Succesfully.

Hmmm also after launch:
![image](https://user-images.githubusercontent.com/104440397/170610943-a6d25c0c-07e7-49d4-94c6-3e2056fa546b.png)

**Comment by Taiga74164** [comment]
just don't include PacketSniffer.. assuming you have no use for it

**Comment by G1DE30N** [comment]
> just don't include PacketSniffer.. assuming you have no use for it

I dont do anything, just pull from git latesst commit and build.

**Comment by LokeYourLord** [comment]
> > just don't include PacketSniffer.. assuming you have no use for it
> 
> I dont do anything, just pull from git latest commit and build. And i dunno how exlude anything because i absolutely zero at coding.

When you have loaded the project, double click "nameofanimegirlgamecheat.sln" on the right side, then on the top bar click "Build", then "Batch Build", and choose the following only:
cheat-base Release x64 Release|x64 ✅
cheat-library Release x64 Release|x64 ✅
injector Release x64 Release|x64 ✅

Picture for reference:
![image](https://user-images.githubusercontent.com/5807595/170682290-7bd2b177-b71e-45b9-a7bc-cec2d8911659.png)

Then click "Build". That is the easiest way to ensure you build the right config.

**Comment by G1DE30N** [comment]
Okay Thanks for the info! ^^
