### ISSUE TITLE
Error 6

### ISSUE THREAD

**Issue by k1romc** [Akebi-Group/Akebi-GC#401]
i dont have file cfg.ini how i can open cfg.ini ?

**Comment by Shichiha** [comment]
the `cfg.ini` file is made when you first launch `injector.exe`  
upon opening, you will get a prompt to select the `GenshinImpact.exe` file  
After selecting it, it should make the `cfg.ini` for you

**Comment by k1romc** [comment]
> 

i open injector and i dont have [cfg.ini]
