### ISSUE TITLE
Menu dosent open

### ISSUE THREAD

**Issue by Matybery** [Akebi-Group/Akebi-GC#404]
When i load akebi global or source it dosent show up in game im on Win 11

**Comment by Shichiha** [comment]
Does a console show up when launching `injector.exe`  
Have you tried clicking F1

**Comment by Matybery** [comment]
yes i did both and in 2.7 it worked

**Comment by Shichiha** [comment]
Can you show a screenshot of the console after launch

**Comment by Matybery** [comment]
source 
![image](https://user-images.githubusercontent.com/109036177/182421541-ef54fc22-4a1b-4e1e-9788-2245580cf5e9.png)
binaries global
![image](https://user-images.githubusercontent.com/109036177/182421992-378f6699-e8a9-460a-8b11-a909f397ecc3.png)

**Comment by Taiga74164** [comment]
d3d11 hook looks fine. if it doesn't show up, then you probably have an overlay on like MSI afterburner or etc.

**Comment by Matybery** [comment]
ye i do have msi afterburner fps

**Comment by Lunairayz** [comment]
smartest akebi user

**Comment by Matybery** [comment]
well sorry i didnt know

**Comment by Matybery** [comment]
ye it now works without msi after
thx for help guys
