### ISSUE TITLE
Moving the character's model by mark

### ISSUE THREAD

**Issue by menleev** [Akebi-Group/Akebi-GC#407]
Is there an opportunity to add the movement of the character on the labels that can be placed yourself? Very similar to a custom teleport, but only with real-time movement (like autorun)

Written via translate I apologize for some incomprehensible words

**Comment by Taiga74164** [comment]
so like interpolate towards the mark?

**Comment by Shichiha** [comment]
https://youtu.be/1Imxn94-qNo ?

**Comment by menleev** [comment]
> 

Yes, about such a movement, this function is not in the final builds?

**Comment by Shichiha** [comment]
it's in the works (probably tomorrow it's finished)

**Comment by menleev** [comment]
> он находится в разработке (вероятно, завтра он будет закончен)

Will it be possible to use this by bind? (Возможно ли это будет использовать через бинды?)

**Comment by Shichiha** [comment]
it wasn't planned, but, yes, i can work with that ✅

**Comment by menleev** [comment]
I am in joyful shock, thank you!🥳🥳🥳

**Comment by Shichiha** [comment]
done with 36a836e
