### ISSUE TITLE
Chest indicator Bug.

### ISSUE THREAD

**Issue by G1DE30N** [Akebi-Group/Akebi-GC#41]
A new feature with a chest display by the method of game mechanics breaks the interface as soon as it displays at least one chest. You can say instantly.

**Comment by RyujinZX** [comment]
Give more information, screenshot?

**Comment by G1DE30N** [comment]
What information you need?
- You log to game.
- You activate Chest Indicator
- You see at least one chest with it
- You got screwed up ping and chat windows like in others issues mentioned here.

**Comment by Emilia33** [comment]
auto  skip dialog also cause the windows error ping everytime i speak to katheryne

**Comment by Taiga74164** [comment]
> breaks the interface
Interface breaking issue has been fixed already. I was trying to reproduce this bug but I don't see anything wrong so I'm closing this. If you experience this again, just comment again and let us know how to reproduce it and I'll re-open this issue
