### ISSUE TITLE
[Feature Request] Skill Stacking?

### ISSUE THREAD

**Issue by Kendu303** [Akebi-Group/Akebi-GC#411]
Not the same thing as multi-hit. Would be cool to see multiple Kazuha's ultimate on the battlefield for example

**Comment by Kendu303** [comment]
A better way of explaining this would be like when Xiangling uses her ultimate, there would be multiple spears

**Comment by Taiga74164** [comment]
> Not the same thing as multi-hit. Would be cool to see multiple Kazuha's ultimate on the battlefield for example

youre only allowed 1 instance of it 

> A better way of explaining this would be like when Xiangling uses her ultimate, there would be multiple spears

#442 maybe

**Comment by Kendu303** [comment]
Can you make it so that rapidfire works with charged bow attacks as well?

**Comment by Taiga74164** [comment]
> Can you make it so that rapidfire works with charged bow attacks as well?

charged attacks works with rapidfire. do you even use this cheat at all? 🤔
