### ISSUE TITLE
Genshin Impact freezing JUST before showing the gate during loading screen

### ISSUE THREAD

**Issue by agent306** [Akebi-Group/Akebi-GC#412]
Weirdly, it works perfectly if launched from the game icon, but crashes when using the injector. I've tried both stable and latest releases, same issue on both. Tried fixing game content from the game launcher. No luck either.

Windows 10

Happy to provide any other technical details

**Comment by Taiga74164** [comment]
hmmm. Perhaps you can try the solution they found on #252 ? I assume that everything injects fine and the GUI shows up at the login door.

**Comment by agent306** [comment]
Yeap. That solved it for me.

TLDR; Re-intsall your graphics drivers, restart PC, get back to 36 starting the abyss without a sweat
