### ISSUE TITLE
Error Code

### ISSUE THREAD

**Issue by Vanaeve** [Akebi-Group/Akebi-GC#419]
Every time i load up the injector it will go to the genshin screen and then cancel and say this error in the screenshot below, i have already disabled and deleted antivirus i only have windows active.
![Screenshot (3)](https://user-images.githubusercontent.com/110660540/183029476-0eccf485-a82c-4975-b1c0-203cb6cd99ee.png)

**Comment by tedzify** [comment]
What version of akebi and the game are you using?

**Comment by Vanaeve** [comment]
Game version: 2.8.0

Launcher: 2.18.1.0

Akebi: v0.8-g2.8

**Comment by Taiga74164** [comment]
only happens if youre using the wrong version of the game or if youre in chinese client

**Comment by Vanaeve** [comment]
im not using chinese client, from what i listed above does everything look good? or no

**Comment by Taiga74164** [comment]
assembly checksum error only triggers when that was the case so it's all up to you to check

**Comment by Taiga74164** [comment]
current version is ``OSRELWin2.8.0_R8078355_S8017153_D8078038``

**Comment by Vanaeve** [comment]
where do i go to download it? or is that the link? if so i cant click it

**Comment by Shichiha** [comment]
Try opening the official launcher, click the cog (settings) button on the top-right of the window

Scroll down, click Repair Game Files

**Comment by Vanaeve** [comment]
same issue

**Comment by Taiga74164** [comment]
load the game without akebi and show the text in the bottom left corner

**Comment by Vanaeve** [comment]
![Uploading Screenshot (4).png…]()

**Comment by Vanaeve** [comment]
here it is, if the pic wont load it says " OSRELWin2.8.0_R9182063_S9401797_D9464149      
![Screenshot (4)](https://user-images.githubusercontent.com/110660540/183091652-dd07fd7c-7ff3-481e-bc97-0561ff1267a5.png)

**Comment by ilya12121928** [comment]
Hello, check the global file there is a lot of excess, clear everything and add only the genshin files!

**Comment by Vanaeve** [comment]
where do i go to find the global files?
