### ISSUE TITLE
Add a simple statistics menu

### ISSUE THREAD

**Issue by Abrasaks** [Akebi-Group/Akebi-GC#420]
Add a new section to the Akebi, with simple stats that the cheat can collect automatically, such as number of chests opened, primogems collected, resources, number of mobs killed, elemental bursts performed, maybe even the distance traveled in flight or running, etc. 
It may have a filter by time, it may not, as it is easier. It would be nice to see, for example, how many resources fall out on average for the n number of killed monsters.

**Comment by Taiga74164** [comment]
bruh
