### ISSUE TITLE
[Bug]Swirl reaction won't trigger with any attack effects mode

### ISSUE THREAD

**Issue by CR4Player** [Akebi-Group/Akebi-GC#427]
Commit[15f493c](https://github.com/Akebi-Group/Akebi-GC/commit/15f493c74dc1ed05b69988d00f171da3c52851d9) in main branch.
<img width="800" alt="Snipaste_2022-08-07_18-48-38" src="https://user-images.githubusercontent.com/12210261/183287209-12ee3998-8d4c-4061-9c18-7e0ed6b0b029.png">
<img width="800" alt="Snipaste_2022-08-07_18-49-00" src="https://user-images.githubusercontent.com/12210261/183287212-06c1098f-8c04-4f36-a9dd-b98e808fe291.png">

**Comment by Taiga74164** [comment]
a

**Comment by CR4Player** [comment]
well, sometime all reaction won't trigger...even physical damage won't register

**Comment by Taiga74164** [comment]
please test #430

**Comment by Taiga74164** [comment]
![image](https://user-images.githubusercontent.com/67109235/183310526-cb06905a-d411-427d-80ff-10e8e78b9057.png)

**Comment by souvikpodder** [comment]
It's working now with @Taiga74164 's commit. And thanks for fixing the multihit. Now I can use my xiao. 🥺

**Comment by CR4Player** [comment]
> please test #430

mihoyo just banned my account for a week🤣

Confirmed working.

**Comment by zhaopinglai** [comment]
https://github.com/Akebi-Group/Akebi-GC/issues/308
Evil machine translation :(
