### ISSUE TITLE
Multiple damage not work in Confront Stormterror 

### ISSUE THREAD

**Issue by Michell-L** [Akebi-Group/Akebi-GC#428]
Multiple damage not work in Confront Stormterror even normal attack still no damage at all ---Version  15f493c master

**Comment by Lunairayz** [comment]
this is balls ass fake

...lemme go try

**Comment by Lunairayz** [comment]
okay +1 
![image](https://user-images.githubusercontent.com/45308130/183300354-d19bf2ea-21f4-4ca8-b530-ff19acea809c.png)


TAIGAAAAAAAAAAAAAAAAAAAAAAA WHAT DID YOU BREAAAAAAAAAAAAAAAK

**Comment by Lunairayz** [comment]
better title - stormterror aint getting hit

**Comment by Taiga74164** [comment]
please tes #430

**Comment by Taiga74164** [comment]
![image](https://user-images.githubusercontent.com/67109235/183310501-df3616c3-baaf-4f4f-8714-c557b7e2bce4.png)
