### ISSUE TITLE
`Inf stamina` breaks many normal game functions.

### ISSUE THREAD

**Issue by souvikpodder** [Akebi-Group/Akebi-GC#43]
Inf Stamina [Normal mode] if on while loading the cheat is breaking many game functions.

Broken functions in game:
1. Sprint
2. Charged attack ( You can't charged attack at all the character does one attack and stops).
3. flying.

You have to turn off Inf stamina and restart the game to start the functions working.

Commit: latest commit.

**Comment by G1DE30N** [comment]
Yep that's true, but i recommend use Packet Mode only.

**Comment by souvikpodder** [comment]
> Yep that's true, but i recommend to use Packet Mode only.

Then ayaka's dash consumes stamina. And charged attacks of characters also consumes stamina.

**Comment by G1DE30N** [comment]
> > Yep that's true, but i recommend to use Packet Mode only.
> 
> Then ayaka's dash consumes stamina. And charged attacks of characters also consumes stamina.

Yep i know, but that it is less bugged than usual until it is fixed, 
I prefer the packet mod because there are fewer problems than without it.
I can say that the packet mode is a temporary stub in an attempt to fix it all, why not use it.

**Comment by hessedvrgn** [comment]
For me, the bug happens if you enabled inf stamina before entering the game (the big door)

Disabling it and then re-enabling it after entering the game fixed it for me

**Comment by Shichiha** [comment]
Better if you understand it as "Freeze Stamina" instead of "Infinite Stamina"
