### ISSUE TITLE
(Question) Unlocking Characters?

### ISSUE THREAD

**Issue by burneraccount3** [Akebi-Group/Akebi-GC#432]
Regardless of the ban risk, is it possible to unlock any character I want? I would like to mod the game, but certain characters I don't have for that.

**Comment by Taiga74164** [comment]
Use ps for that

**Comment by burneraccount3** [comment]
What's ps? I'm new to cheating Genshin, so sorry if I don't know.

**Comment by tedzify** [comment]
A private server. The most popular one, being [Grasscutter](https://github.com/Grasscutters/Grasscutter).
