### ISSUE TITLE
[Solution]Runtime Error!

### ISSUE THREAD

**Issue by 21009123** [Akebi-Group/Akebi-GC#433]
![image](https://user-images.githubusercontent.com/106359592/183561902-e037d9aa-3628-4bda-bb60-d22425f65763.png)
this happens when I pull the latest commit.

**Comment by 21009123** [comment]
same error when i download the latest commit from github action

**Comment by Taiga74164** [comment]
https://github.com/Akebi-Group/Akebi-GC/issues/429#issuecomment-1208396833

**Comment by Taiga74164** [comment]
Pinning this for awhile so people see it.

**Comment by Lunairayz** [comment]
> Pinning this for awhile so people see it.

imo should change the [solved] part to [solution]

**Comment by Lunairayz** [comment]
idk for shit if that's smart but lmoa

**Comment by daofeng2015** [comment]
you need https://www.123pan.com/s/K41rVv-EtT43 this
