### ISSUE TITLE
RapidFire just doesn't work with bow's charged attack 

### ISSUE THREAD

**Issue by Kendu303** [Akebi-Group/Akebi-GC#435]
![image](https://user-images.githubusercontent.com/55598796/183564728-74406061-b48b-4f46-ad17-7c735b0a6ad3.png)
As you can see there's only 1 trail of arrow although there should be multiple

**Comment by Taiga74164** [comment]
Oh you meant the animation.. yeah it doesn't work for Bow Charged Attacks (

**Comment by Kendu303** [comment]
Oh that sucks D:
