### ISSUE TITLE
Mob Vacuum doesn't work to Floating Fungi

### ISSUE THREAD

**Issue by XylioG** [Akebi-Group/Akebi-GC#44]
Yeh, it doesn't work

![1](https://user-images.githubusercontent.com/20736903/170851660-bc55b2d4-f74d-4ef0-866c-0c950039b1b9.png)

**Comment by souvikpodder** [comment]
Yup. I can confirm that also.

**Comment by souvikpodder** [comment]
Monster details:

Entity,RuntimeID,Name,PosX,PosY,PosZ
0x228abd69590,33554510,Monster_Fungus_Un_Gamma_Water_01(Clone) authority :True,290.1633,156.90717,754.6935
