### ISSUE TITLE
The cheat wont show up

### ISSUE THREAD

**Issue by ArthaVerx** [Akebi-Group/Akebi-GC#440]
![Screenshot 2022-08-09 195055](https://user-images.githubusercontent.com/104915027/183648836-7908b478-b7db-4fc6-8d07-b1ab3e461ff0.png)

**Comment by Taiga74164** [comment]
any info what you did? what build? what have you tried? 

your screenshot doesn't explain anything

**Comment by ArthaVerx** [comment]
I didn't do anything
i dont build it
what i have tried doing
Deleting temp
Flushing dns
repairing my genshin
redownload the cc genshin
changing resolution in game
and high priority for genshin.exe

**Comment by ArthaVerx** [comment]
well it worked but cc genshin doesn't load v:

**Comment by Shichiha** [comment]
do you have any external overlays such as msi afterburner?

**Comment by ArthaVerx** [comment]
> a

no i dont

**Comment by Taiga74164** [comment]
if you used an old build and it happened just all of a sudden then idk how to rly help you.. sounds like an issue on your side

**Comment by ArthaVerx** [comment]
> 

welp, then ill build one. anyway thanks
