### ISSUE TITLE
Genshin Impact crashed!

### ISSUE THREAD

**Issue by NotEvenYami** [Akebi-Group/Akebi-GC#441]
i run 3dmigoto with akebi-gc and just 3 seconds after the Genshin Impact's title showed up. It started to not responding then immediatly disappear and both 3dmigoto and akebi disappear too

**Comment by Taiga74164** [comment]
in most cases. people who are using it with 3dmigoto solved it by manually injecting Akebi instead

**Comment by Taiga74164** [comment]
modify the injector and add a delay to injector or use key to call InjectDLL
