### ISSUE TITLE
Automatic teleportation by points with a choice of delay

### ISSUE THREAD

**Issue by menleev** [Akebi-Group/Akebi-GC#443]
Add a function that allows you to automatically teleport between points. It would be nice if it was possible to adjust the delay between these teleports.

This function will be very useful, because many people use clickers to activate teleportation binds. It is strange that akebi still does not have such a function (

**Comment by GIFUS** [comment]
If this is added, that would be cool!

**Comment by Justfeel1337** [comment]
Please add this! This is a very good idea

**Comment by harlanx** [comment]
I'm working on this though I'm still testing the best way to wait for player to load + delay before teleporting again
