### ISSUE TITLE
[Bug] Buried Chest share the same name with other objects

### ISSUE THREAD

**Issue by Kendu303** [Akebi-Group/Akebi-GC#447]
![image](https://user-images.githubusercontent.com/55598796/183921442-db7583f4-8eff-4c12-8f9b-e0ee4583941e.png)
How is this a buried chest lol

**Comment by Taiga74164** [comment]
yeah burried chest name share names with others seems like

**Comment by Julienraptor01** [comment]
Same problem with geogranum
![image](https://user-images.githubusercontent.com/49841713/188195946-f495b16e-ad01-4407-b726-a6c5a1bc3258.png)
