### ISSUE TITLE
Strange things on 2.7

### ISSUE THREAD

**Issue by G1DE30N** [Akebi-Group/Akebi-GC#45]
After launch lattest commit
![image](https://user-images.githubusercontent.com/104440397/171083345-2ab59726-c263-41a3-a270-f7151e005f88.png)

AND

Okay but i don't :D
![image](https://user-images.githubusercontent.com/104440397/171083410-5ff04a54-d84c-4859-9c09-06d04329cf3a.png)

**Comment by Taiga74164** [comment]
First image is because of the added encryption on ``il2cpp_resolve_icall()``

Second image you can ignore that

**Comment by G1DE30N** [comment]
Okay, Thanks for the info Taiga ;D
And thanks for 2.7 ver :)

**Comment by monado1110** [comment]
can anyone send me a 2.7 build pls ? just need rapid to finish the dailies

**Comment by G1DE30N** [comment]
> can anyone send me a 2.7 build pls ? just need rapid to finish the dailies

I upload build in #46
