### ISSUE TITLE
Running akebi for two or more genshin windows

### ISSUE THREAD

**Issue by menleev** [Akebi-Group/Akebi-GC#452]
Is it possible to make akebi run on the second genshin process, etc? When cloning the genshin folder and running the clone, it calmly logs into 2 different accounts, but the injection only works if you run the first genshin process through the injector, and in the second it asks to wait for closure. 

I understand that there is a bypass, but is it possible to implement a launch in two or more windows?

![image](https://user-images.githubusercontent.com/110269230/184448620-6a8edf7a-994d-4e88-bccd-abfb83133567.png)

**Comment by Taiga74164** [comment]
yeah. remove the line where it waits for genshin process in the injector

**Comment by Taiga74164** [comment]
you can inject manually to 2nd window.

> and in the second it asks to wait for closure.

edit injector code and remove waiting to close process
