### ISSUE TITLE
Takes a lot of time to start the game with akebi

### ISSUE THREAD

**Issue by adf2b** [Akebi-Group/Akebi-GC#454]
I put the game on my SSD,  However ,when I start the game with akeb ,it will stay at the 'Warning: Read More Before Playing' screen for several minutes, but when I launch directly through the game's EXE file, it opens quickly.

![1](https://user-images.githubusercontent.com/102723510/184578851-5b159a4d-0700-440a-ba2b-3d9e78e0f421.PNG)

**Comment by Taiga74164** [comment]
please refer to #252 . it's probably the same case for you

**Comment by adf2b** [comment]
> 请参考#252。对你来说可能是同样的情况

Thanks a lot！
