### ISSUE TITLE
Chinese version can not Auto Destory Object about Enabled plant for sakura bloom

### ISSUE THREAD

**Issue by ZongerZY** [Akebi-Group/Akebi-GC#455]
![image](https://user-images.githubusercontent.com/45865254/184582719-4b92756f-64bb-4c85-bd23-346d801aac33.png)
When I turn on the Auto Destory Plant option，
In fact, it can't destroy the sakura bloom，but restricts the sakura bloom.
Others，such as dandelion seeds, fire flower, frost flower, etc，are OK.
At present, this problem only appears in the Chinese version.
The international version has not tried, and I don't know if there is this problem.

**Comment by harlanx** [comment]
Refer to https://github.com/Akebi-Group/Akebi-GC/issues/256#issuecomment-1200095390
