### ISSUE TITLE
перестает работать после 2_3 запусков 

### ISSUE THREAD

**Issue by mtverjfvjpefoav** [Akebi-Group/Akebi-GC#456]
[Debug] [util.cpp:163] genshin path path not found. Please point to it manually.
[Error] [main.cpp:131] Failed to create game process.. Error: 6 ═хтхЁэ√щ фхёъЁшяЄюЁ.

[Error] [main.cpp:132] If you have problem with GenshinImpact.exe path. You can change it manually in cfg.ini.
Failed to open GenshinImpact process.
Для продолжения нажмите любую клавишу . . .

пробовал удалить cfg.ini но его внутри чита не было драйвера с++ обновил устновил это с любым читом с акеби

**Comment by Shichiha** [comment]
try check if it's clone of #392

try:
- sign other user off
- restart
- run in admin account 

make sure genshin path in `cfg.ini` point correct path

**Comment by mtverjfvjpefoav** [comment]
не помогло

ср, 17 авг. 2022 г., 02:39 shichiha ***@***.***>:

**Comment by S1zus** [comment]
Файл cfg.ini должен быть в одной папке с injector.exe, сам путь должен выглядеть так: GenshinPath = C:\...\Genshin Impact\Genshin Impact game\GenshinImpact.exe
