### ISSUE TITLE
failed to open genshin impact process. (after build last ver.)

### ISSUE THREAD

**Issue by decausedinside** [Akebi-Group/Akebi-GC#458]
![[image](https://user-images.githubusercontent.com/67109235/185185572-273fec59-9602-4963-96c4-45b820e1f5ce.png)](https://user-images.githubusercontent.com/69603371/185224292-74e925f0-aed0-4ae1-a7c8-f75a17d2cb90.png)

**Comment by Shichiha** [comment]
try check if it's clone of #392

try:

- sign other users off
- restart
- run in admin account

make sure genshin path in cfg.ini point correct path, injector is running with administrative permission
