### ISSUE TITLE
machine gun bow

### ISSUE THREAD

**Issue by azhdaha-100kg** [Akebi-Group/Akebi-GC#459]
reference : https://youtube.com/shorts/rHNl8Wnqzr8?feature=share

hope someone can add this fun feature

**Comment by Taiga74164** [comment]
Multi-Animation in Attack Modifier already exists..

**Comment by Taiga74164** [comment]
https://github.com/Akebi-Group/Akebi-GC/issues/422#issuecomment-1207153647

**Comment by azhdaha-100kg** [comment]
oh i just know that, but it's kinda scary my potato pc drop the fps to 10fps 😄
maybe could you add something like this 
![image](https://user-images.githubusercontent.com/69887271/185253297-951fa2bb-159a-42e7-8ec0-7a58f1b444bc.png)

so we can make it slower, is that possible?

**Comment by azhdaha-100kg** [comment]
@assBuk thanks that looks good, will try later
