### ISSUE TITLE
[Feature Request] Add Character or Weapon material filter in Interactive Map

### ISSUE THREAD

**Issue by Fanixtar** [Akebi-Group/Akebi-GC#460]
something like this
![image](https://user-images.githubusercontent.com/96950043/185322917-7acdd7b8-83a8-41cc-a1a6-9c8cc5c255f2.png)
![image](https://user-images.githubusercontent.com/96950043/185323134-9531d2ea-a5d6-46f8-9ee9-8127c0c9ee92.png)

**Comment by Taiga74164** [comment]
looks like need database for this
