### ISSUE TITLE
Keep waiting for initialization repeatedly

### ISSUE THREAD

**Issue by 16370** [Akebi-Group/Akebi-GC#463]
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/111580410/185631443-924bec6a-20eb-4ee2-9f96-1844f3a7b3a2.png">

**Comment by 16370** [comment]
Resolved, the location of the injected file is on the launcher, and the game itself has been resolved

**Comment by 16370** [comment]
Resolved, the location of the injected file is on the launcher, and switching to the game body is solved

**Comment by qq857857** [comment]
no no no ! im sorry !




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Akebi-Group/Akebi-GC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 晚上9:59
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [Akebi-Group/Akebi-GC] Keep waiting for initialization repeatedly (Issue #463)





 
Resolved, the location of the injected file is on the launcher, and switching to the game body is solved

**Comment by Taiga74164** [comment]
![image](https://user-images.githubusercontent.com/67109235/185984649-6f67cfc2-f839-4e28-87c3-d0b0f5db0d33.png)
