### ISSUE TITLE
No such file or dictionary

### ISSUE THREAD

**Issue by ThanatosXingYu** [Akebi-Group/Akebi-GC#465]
I clone the soure code directly, and using the VScode stdio 2020,then installed the C++ and .NET, when I debug it, it warns
![QQ截图20220820222622](https://user-images.githubusercontent.com/53430376/185751249-a42e6dae-24dd-4c0f-9890-fcdf05a31a24.png)
.

**Comment by Fanixtar** [comment]
Clone repository with 
```
git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git

**Comment by ThanatosXingYu** [comment]
![QQ截图20220820225655](https://user-images.githubusercontent.com/53430376/185752804-571207fa-b58e-470d-84d2-66fc29665f89.png)
![QQ截图20220820230204](https://user-images.githubusercontent.com/53430376/185753144-7e9f636c-1a01-487d-a0e1-b2640c65ac18.png)
Does this mean I failed. I live in China, and "git clone"  may be a little difficult for me. So can someone send me a compressed file about it?


>

**Comment by Fanixtar** [comment]
how about download pre-built release, it's ready to use
https://github.com/Akebi-Group/Akebi-GC/actions/runs/2824566940

**Comment by ThanatosXingYu** [comment]
Ehhh..About the .lib file, how can I change it?I want a source code compressed file that include all the modules so that I can translate some of them into Chinese.

**Comment by Bilx-ZL** [comment]
> Ehhh..About the .lib file, how can I change it?I want a source code compressed file that include all the modules so that I can translate some of them into Chinese.

倒卖？

**Comment by ThanatosXingYu** [comment]
> > Ehhh..About the .lib file, how can I change it?I want a source code compressed file that include all the modules so that I can translate some of them into Chinese.
> 
> 倒卖？

嘎？自己用。纯英的感觉太别扭了

**Comment by Bilx-ZL** [comment]
> > > Ehhh..About the .lib file, how can I change it?I want a source code compressed file that include all the modules so that I can translate some of them into Chinese.
> > 
> > 
> > 倒卖？
> 
> 嘎？自己用。纯英的感觉太别扭了

嗷..好吧。

**Comment by ThanatosXingYu** [comment]
Thanks everyone in this issue. I clone the necessary modules in the ".gitmodules" file one by one. Then I can success to solve the "No such file or dictionary" problem.
