### ISSUE TITLE
A invalid win32 program

### ISSUE THREAD

**Issue by ThanatosXingYu** [Akebi-Group/Akebi-GC#467]
With "No such file or dictionary" was solved by I clone all the modules in the ".gitmodules" one by one, I meet a new question.
It warns me "A invalid win32 program".  Sometime it also output "Previous IPDB not found
![QQ截图20220821121645](https://user-images.githubusercontent.com/53430376/185775339-bf7967ba-98b8-4710-a77d-f7663992c00c.png)
.
![QQ截图20220821121407](https://user-images.githubusercontent.com/53430376/185775338-12c30a86-f3bf-4dc7-83d2-ff9d649678c9.png)
"
How can I do?

**Comment by ThanatosXingYu** [comment]
I've tried what they said in https://github.com/Akebi-Group/Akebi-GC/issues/350
But it might no help for me.

**Comment by daofeng2015** [comment]
不要尝试用vs直接启动...先生成，再自己运行inject进行注入
