### ISSUE TITLE
AkebiGC Team: Attention Please

### ISSUE THREAD

**Issue by LokeYourLord** [Akebi-Group/Akebi-GC#470]
As was obvious it would happen, some mongoloids copy this repository, make their own malicious launchers, and post it to YouTube. Is there anything you can do about it? Video in question: https://www.youtube.com/watch?v=aFEJ14xAV6U&t=86s

Because of disgusting maggots like him, projects like these go down, which I don't want to happen. I enjoy the open-source nature and ability to compile this myself, and it would suck for AkebiGC to stop because of scum like this CrapTuber.

**Comment by Lunairayz** [comment]
orrrrr we could report vid stating it's a tutorial for hacks in a game xd

**Comment by Taiga74164** [comment]
can't do anything about them sadly. if people can't find where the official repo is then that's their issue

**Comment by Lunairayz** [comment]
> can't do anything about them sadly. if people can't find where the official repo is then that's their issue

why don't you do the xyz thing where shit ton of watermarks float around before you get ingame lul

**Comment by Taiga74164** [comment]
> why don't you do the xyz thing where shit ton of watermarks float around before you get ingame lul

LOL. project is open source and anyone can change them.

**Comment by Shichiha** [comment]
dont add it i hated that shit
