### ISSUE TITLE
Upgraded Treasure compass

### ISSUE THREAD

**Issue by xMizuHix** [Akebi-Group/Akebi-GC#471]
Want to 100% the exploration rate but cant find the remaining chests? Then you are the right place.
Basically an upgraded treasure compass
Wider area and unlimited use
Is it possible?

**Comment by Taiga74164** [comment]
can't really detect any gameobject unless you're a certain distance nearby it so no

**Comment by Taiga74164** [comment]
assuming your suggestion was implementing the same feature as the compass

**Comment by xMizuHix** [comment]
Oh ok
