### ISSUE TITLE
Crashing at epilepsy warning after 50ce89b commit if AutoCook was enabled before this commit

### ISSUE THREAD

**Issue by ufgf** [Akebi-Group/Akebi-GC#473]
Problem commit: https://github.com/Akebi-Group/Akebi-GC/commit/50ce89b1e30df777bd903df6057e6f07a75b0b58

## Detailed description of a problem
The crash is caused by reading a parameter that should be named differently, and have a different value (it was `"AutoCook": { "QualityField": 2 }`, after commit it need to be `"AutoCook": { "Quality": "Normal" }`).

The solution is simple: in your `cfg.json` find and delete ever AutoCook you find or change the name and value of the parameter to the last one listed above.

Of course, it would be better if the migration to new name and value was at the code level (or there would be at least ignoring the parameter so as not to cause a crash), but I rather write this issue for those who do not know why a crash started to occur at startup after any of the latest updates (at the time of writing this issue).

**Comment by harlanx** [comment]
The solution can easily be found on the PR https://github.com/Akebi-Group/Akebi-GC/pull/429 with the commit you mentioned.
