### ISSUE TITLE
[Feature Request] make an artifact substats RNG editor

### ISSUE THREAD

**Issue by Zenjuuro** [Akebi-Group/Akebi-GC#476]
for example 
you can edit chance to get
- **Crit Rate**
- **Atk**
- **Elemental Mastery**

so we could reduce time to get good artifact with perfect stats and substats

![image](https://user-images.githubusercontent.com/111912435/186248788-14e34f25-15e4-4854-a7fc-1f556b0419c4.png)

**Comment by Taiga74164** [comment]
at least make a request that's realistic 💀

**Comment by Lunairayz** [comment]
welcome to gacha games bitch

**Comment by nitrog0d** [comment]
this is honestly

**Comment by karvoeraso** [comment]
doesn't seem to know what client and server is lol
