### ISSUE TITLE
[Issue] Interactive Map filters

### ISSUE THREAD

**Issue by Taiga74164** [Akebi-Group/Akebi-GC#478]
Interactive Map filters doesn't seem to show up. The function still works if you manually add the [clear_name](https://raw.githubusercontent.com/Akebi-Group/Akebi-GC/master/cheat-library/res/map_teyvat.json) value to your ``cfg.json``

![image](https://user-images.githubusercontent.com/67109235/186354692-94d35990-eec9-494f-a7d2-254e56054e6e.png)

![image](https://user-images.githubusercontent.com/67109235/186355270-0c9909fe-9157-4d1c-9206-b979ebc172fa.png)

**Comment by shangshandashu** [comment]
Can you tell us more about how it works? Like what to replace and where to add the code.

**Comment by Marythore** [comment]
Why doesn't he work for me

**Comment by dvdela** [comment]
For me too

**Comment by LunarisFP** [comment]
You're not the only one

**Comment by dvdela** [comment]
If im  thinking right u need to add just those 3: CristalCore, Dendroculus and Dendrogranum to Filters and u will have icons on a minimap but not on map and i dont know how to fix it.

**Comment by killercc** [comment]
not work for me

**Comment by TokikiriNanaya** [comment]
I try it but none icon display on my map

**Comment by shangshandashu** [comment]
![image](https://user-images.githubusercontent.com/100282547/186432166-aaaf85d9-64ff-4dd2-bb84-3685d4111ac8.png)
maybe this.

**Comment by CPP-Callow** [comment]
`MoleMole_MapManager` have incorrect fields structure

**Comment by CPP-Callow** [comment]
![image](https://user-images.githubusercontent.com/105681690/186465667-7b377cad-e3b2-4e8b-b91a-a6b8858f040e.png)

**Comment by hellomykami** [comment]
![image](https://user-images.githubusercontent.com/23090639/186465837-e7d481f0-88f9-4267-be74-7b403cc9b667.png)
fields changed

**Comment by CPP-Callow** [comment]
Can you post the dump of field from the screenshot?

**Comment by hellomykami** [comment]
`struct __declspec(align(8)) MoleMole_MapManager__Fields {
    bool GCNMOPKPIMF;
    struct GameObject *PFODEBJOGMM;
    struct MonoLevelMapUI *KOEPKNOMAAD;
    uint32_t AHDEDGLIBBD;
    uint32_t OHIKKNAOPPK;
    uint32_t NDNBINKBHHO;
    struct SceneScriptData *FECMGJJGKOF;
    struct MapScriptData *GAODHFIFLJM;
    struct String *HGEOOBHOHPD;
    struct Nullable_1_MoleMole_AsyncJob_ BKMDLHJBOMF;
    bool AJOGBFJCCGF;
    uint32_t CMKKDMPLNBI;
    bool HEELDKEAIPD;
    struct String *HEPDDKIGBKI;
    struct RectTransform *MNGHBAAABLF;
    struct GameObject *FFFBHOONECE;
    uint32_t _mapImageHandle;
    struct MonoLevelMap *CKEDFAEDKHE;
    float KCFIIOILJKN;
    int32_t JICFIPFGLPL;
    bool GFKLFDNABME;
    struct Vector3 FHIEGOGFOLI;
    float ACCNGKAJMLM;
    uint32_t ECFILAEJJML;
    bool FLDAFADKOJI;
    struct GameObject *FPKDGCJHAGM;
    uint32_t LPOBPKLKGGK;
    struct List_1_OOMOGPMHEAO_ *HAEOLGFHPEN;
    struct List_1_System_String_ *EIJHGKFFDHO;
    struct Dictionary_2_System_String_PILLJDIDHIJ_ *LBDCDMEMJLD;
    bool ANAMKBGMKEC;
    bool EOLOGHEBMHA;
    struct Coroutine *HOCJGHAOAJN;
    float KJLNBKEIFCJ;
    struct Vector3 CIPDJNHBFPB;
    struct List_1_System_UInt32_ *OBMINJCEAJL;
    struct Dictionary_2_System_UInt32_List_1_LPKPLIFIBGA_ *JAKFLGOOBMP;
    bool OJNGNBKMMFI;
    struct List_1_System_String_ *OJBKAGDIEIK;
    struct List_1_System_String_ *NFGGLJBPIBO;
    struct Dictionary_2_System_String_System_UInt32_ *AIMGKHPHKMP;
    struct Dictionary_2_System_UInt32_System_UInt32_ *NCOMNKCALBL;
};`

**Comment by CPP-Callow** [comment]
Fixed

**Comment by CPP-Callow** [comment]
![image](https://user-images.githubusercontent.com/105681690/186467995-97c4c2b0-df85-40cd-b059-ea092470461e.png)

**Comment by hellomykami** [comment]
```c++
struct __declspec(align(8)) MoleMole_MapManager__Fields {
    bool GCNMOPKPIMF;
    struct GameObject *mapObj;
    struct MonoLevelMapUI *monoLevelMapUI;
    uint32_t _mapContainerHandle;
    uint32_t playerSceneID;
    uint32_t mapSceneID;
    struct SceneScriptData *_sceneDataInMap;
    struct MapScriptData *mapData;
    struct String *_currMapPrefabPath;
    struct Nullable_1_MoleMole_AsyncJob_ BKMDLHJBOMF;
    bool _forceCurrentScene;
    uint32_t _mapSceneIDSelected;
    bool DebugNewmap;
    struct String *currMapString;
    struct RectTransform *currParent;
    struct GameObject *mapGameObjectInst;
    uint32_t _mapImageHandle;
    struct MonoLevelMap *levelMap;
    float mainPageCheckDistance;
    int32_t _currState;
    bool _hasSignalv;
    struct Vector3 _signalPos;
    float _distanceThreshold;
    uint32_t _id;
    bool FLDAFADKOJI;
    struct GameObject *FPKDGCJHAGM;
    uint32_t LPOBPKLKGGK;
    struct List_1_OOMOGPMHEAO_ *HAEOLGFHPEN;
    struct List_1_System_String_ *EIJHGKFFDHO;
    struct Dictionary_2_System_String_PILLJDIDHIJ_ *_polygonLimitRegions;
    bool _isCurActivityLimitRegion;
    bool _isCurHomeworldLimitRegion;
    struct Coroutine *_curDestroyLimitRegionCoroutine;
    float KJLNBKEIFCJ;
    struct Vector3 CIPDJNHBFPB;
    struct List_1_System_UInt32_ *OBMINJCEAJL;
    struct Dictionary_2_System_UInt32_List_1_LPKPLIFIBGA_ *JAKFLGOOBMP;
    bool OJNGNBKMMFI;
    struct List_1_System_String_ *OJBKAGDIEIK;
    struct List_1_System_String_ *NFGGLJBPIBO;
    struct Dictionary_2_System_String_System_UInt32_ *AIMGKHPHKMP;
    struct Dictionary_2_System_UInt32_System_UInt32_ *NCOMNKCALBL;
};
```

with name translation
