### ISSUE TITLE
Are you use a modified Imgui

### ISSUE THREAD

**Issue by Ligture** [Akebi-Group/Akebi-GC#484]
my English is not good, so I want to translate this cheat for me and my friends
However, when I add imgui:: getio(). Fonts - > getglyphrangesichinesefull(), the game will crash
I want to ask if you have used some modified imgui to cause this problem

**Comment by Shichiha** [comment]
there was a discussion for localization over at #71

**Comment by Micah123321** [comment]
还有崩溃原因是因为字体载入方式为内存加载,你可以使用本地文件加载,具体参考官方imgui案例
The other reason for the crash is that fonts are loaded in memory, you can use local file loading, refer to the official IMGUI case

**Comment by restarteded** [comment]
笑死，翻译了让你去倒卖？这点英文水平都没有还是别再GitHub上找挂了

**Comment by restarteded** [comment]
我可以很负责的告诉你，可以汉化，但对于编程的程序猿来说完全没有必要

**Comment by SaigyoujiYusora** [comment]
> 

就...问下 泛滥翻译成proliferation是不是好点（）

**Comment by Micah123321** [comment]
> > 
> 
> 就...问下 泛滥翻译成proliferation是不是好点（）

快捷生成的 
![](https://btxo.cn/oss/2022-08-24/1e4a8f3d.png)

**Comment by Ligture** [comment]
我qq邮箱摆在这你盯着我qq看行不行，不懂英语怎么了招你惹你了



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 24, 2022 22:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Akebi-Group/Akebi-GC] Are you use a modified Imgui (Issue #484)




 
笑死，翻译了让你去倒卖？这点英文水平都没有还是别再GitHub上找挂了

**Comment by Ligture** [comment]
我都不是程序猿，自己爱好学了一点Python和c++



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 24, 2022 22:31 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Akebi-Group/Akebi-GC] Are you use a modified Imgui (Issue #484)




 
我可以很负责的告诉你，可以汉化，但对于编程的程序猿来说完全没有必要

**Comment by Ligture** [comment]
我倒卖我不去花钱找大神赶紧圈钱我来这发issue我是有病还是什么



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 24, 2022 22:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Akebi-Group/Akebi-GC] Are you use a modified Imgui (Issue #484)




 
笑死，翻译了让你去倒卖？这点英文水平都没有还是别再GitHub上找挂了

**Comment by Bilx-ZL** [comment]
这种英文真的很简单，没有必要去翻译，现在翻译默认当倒卖，毕竟某类人就擅长干这勾当。

**Comment by Ligture** [comment]
嗯我自己知道一种方法挺累的我也懒得弄了



---Original---
From: ***@***.***&gt;
Date: Thu, Aug 25, 2022 00:53 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Akebi-Group/Akebi-GC] Are you use a modified Imgui (Issue #484)




 
这种英文真的很简单，没有必要去翻译，现在翻译默认当倒卖，毕竟某类人就擅长干这勾当。
