### ISSUE TITLE
Genshin Impact Update 3.0

### ISSUE THREAD

**Issue by 123daga** [Akebi-Group/Akebi-GC#487]

**Comment by restarteded** [comment]
it's so funny that you join the github a month ago , just for this cheat ?

**Comment by Lunairayz** [comment]
DAAAAAAMNNNNN

**Comment by 123daga** [comment]
I'm sorry, it's my fault, I'm too impatient, please don't reply to me

**Comment by Lunairayz** [comment]
> I'm sorry, it's my fault, I'm too impatient, please don't reply to me

idk if you want the chinese or eng version, but go to "actions" at the top of the page
