### ISSUE TITLE
How to update to 3.0

### ISSUE THREAD

**Issue by Si-JiX** [Akebi-Group/Akebi-GC#489]
I have basically returned my "C + +" to the teacher   XD
(If you are Chinese, you can speak Chinese directly)

**Comment by Si-JiX** [comment]
The new map is too big. I explored it for six hours today. I've vomited

**Comment by Gsutab-M** [comment]
辛苦了

**Comment by chongWjing** [comment]
辛苦了

**Comment by YTTTR1** [comment]
when will you guys release 3.0 Akebi?

**Comment by code4cc** [comment]
新版本地图太大了，估计要等上一个月了

**Comment by Taiga74164** [comment]
[Actions](https://github.com/Akebi-Group/Akebi-GC/actions)
