### ISSUE TITLE
Need help with the cheat - F9 not working

### ISSUE THREAD

**Issue by xmgnew** [Akebi-Group/Akebi-GC#49]
![image](https://user-images.githubusercontent.com/95559022/171162141-7cff689d-ae86-40ad-99b5-c2bd047af9f0.png)
Is this error normal? Because although these errors shown up, the cheat still loaded.
In the game, there is only three things on screen:
![image](https://user-images.githubusercontent.com/95559022/171162417-e1c65e73-fd54-43e6-ba81-887982d0f310.png)
Pressing F9 does not work, I tried pressing every fn key, even the home, ins and del keys, the cheat menu doesn't show up.

**Comment by CNLouisLiu** [comment]
maybe you can press F1

**Comment by tedzify** [comment]
You can try deleting your `cfg.json` file on the cheat folder.

**Comment by G1DE30N** [comment]
Mentioned in #46 thats not normal but not critical just ignore it (c) Taiga
