### ISSUE TITLE
how to use Map Teleport (Teleport to mark on map)

### ISSUE THREAD

**Issue by ggvv9110j** [Akebi-Group/Akebi-GC#492]

**Comment by ruslkochnev** [comment]
need to activate this option in F1-key menu, then open the map, hold T key and left click on map, where you wanna go

**Comment by ggvv9110j** [comment]
done thank you:D

**Comment by Taiga74164** [comment]
literally on the menu 
![image](https://user-images.githubusercontent.com/67109235/186518488-4839b742-e2c8-4132-930b-74487bd7a985.png)
