### ISSUE TITLE
launching issue

### ISSUE THREAD

**Issue by Testingacc-now** [Akebi-Group/Akebi-GC#496]
when i run the injector it opens and before i can see the click to start it crushs any help?

**Comment by Taiga74164** [comment]
what does the console say?

**Comment by Testingacc-now** [comment]
its closes before i can look

**Comment by thelostabbey** [comment]
this is happening for me too, managed to grab a screen before close.  Using the latest commit.  It did boot into game a couple attempts after trying many times.  
![Untitled2](https://user-images.githubusercontent.com/48223004/186557312-4f1640a8-43a4-4c00-873f-e891bb22f6c0.png)

**Comment by Testingacc-now** [comment]
> this is happening for me too, managed to grab a screen before close. Using the latest commit. It did boot into game a couple attempts after trying many times. ![Untitled2](https://user-images.githubusercontent.com/48223004/186557312-4f1640a8-43a4-4c00-873f-e891bb22f6c0.png)
?

**Comment by thelostabbey** [comment]
> what

not sure what you are asking, @Taiga74164 asked what was the console message before crash and I assume it's the same one above for you.

**Comment by Testingacc-now** [comment]
what do you mean by 

> Using the latest commit. It did boot into game a couple attempts after trying many times.

**Comment by Phudzz** [comment]
> this is happening for me too, managed to grab a screen before close. Using the latest commit. It did boot into game a couple attempts after trying many times. ![Untitled2](https://user-images.githubusercontent.com/48223004/186557312-4f1640a8-43a4-4c00-873f-e891bb22f6c0.png)

ahh, i fixed it by reinstall genshin impact

**Comment by thelostabbey** [comment]
> you found a fix?

yes, you need to do a clean build of the latest commit .  Just save a backup of your cfg files clear out your existing repo and clone the repo again.  should do the trick.

**Comment by Taiga74164** [comment]
> this is happening for me too, managed to grab a screen before close. Using the latest commit. It did boot into game a couple attempts after trying many times. ![Untitled2](https://user-images.githubusercontent.com/48223004/186557312-4f1640a8-43a4-4c00-873f-e891bb22f6c0.png)

read what it says.. it says 2.8
