### ISSUE TITLE
Crash after hitting some entities

### ISSUE THREAD

**Issue by GarethOz** [Akebi-Group/Akebi-GC#5]
This mostly happens after you use the teleport feature so many times.
Tried 3 hours without using the teleport feature and there was no crash.

**Comment by Taiga74164** [comment]
So is the issue hitting entities or teleporting? 😵‍💫

**Comment by tedzify** [comment]
Try to recreate this and detail exactly what you did before the crash.

**Comment by GarethOz** [comment]
![image](https://user-images.githubusercontent.com/104610042/168885278-c5ce3e6d-956d-4be5-bbfb-00e03d1cc20e.png)
these are what I'm using. Last time I crashed was when attacking an electro abyss lector in Enkanomiya. I can't say for sure that it happens right when I hit the enemy, but it happens when I'm in combat after too much teleportation.

**Comment by GarethOz** [comment]
Someone else commented about this as well with a log in the previous one I opened. Hopefully they can provide that log again.

**Comment by Taiga74164** [comment]
> ![image](https://user-images.githubusercontent.com/104610042/168885278-c5ce3e6d-956d-4be5-bbfb-00e03d1cc20e.png) these are what I'm using. Last time I crashed was when attacking an electro abyss lector in Enkanomiya. I can't say for sure that it happens right when I hit the enemy, but it happens when I'm in combat after too much teleportation.

If this is a case with hitting enemies, it might be because of Multi Hit causing too much packet sent in short period of time(either your ping increases or you crash). If this is with Teleport, then we'll have to investigate more.

**Comment by G1DE30N** [comment]
I think is that multihit problem as directed above. Because rarely i crashed to when hitting monsters, but i not have any problems with teleporting, except for a small problem with it, which I thought was a bug, but later realized that this is its feature in terms of code.

**Comment by GarethOz** [comment]
I will set it to 2 and report the result.

**Comment by souvikpodder** [comment]
> If this is a case with hitting enemies, it might be because of Multi Hit causing too much packet sent in short period of time(either your ping increases or you crash). If this is with Teleport, then we'll have to investigate more.

@Taiga74164 So I noticed It happens when multi hit is on and I use E/Q. But this crash is too rare. Happened only 2 times with me after using E/Q with multi hit on while fighting some enemy.

I shared logs and positions where it happened in previous repo. But I don't think it will help with debugging because the log was from after the crash when I loaded the menu again.
And there was no debug log related to crash in the console or the log file the menu prints.

**Comment by WitchGod** [comment]
> > If this is a case with hitting enemies, it might be because of Multi Hit causing too much packet sent in short period of time(either your ping increases or you crash). If this is with Teleport, then we'll have to investigate more.
> 
> @Taiga74164 So I noticed It happens when multi hit is on and I use E/Q. But this crash is too rare. Happened only 2 times with me after using E/Q with multi hit on while fighting some enemy.
> 
> I shared logs and positions where it happened in previous repo. But I don't think it will help with debugging because the log was from after the crash when I loaded the menu again. And there was no debug log related to crash in the console or the log file the menu prints.

By any chance are you using an Anemo or Hydro skill when this happened? Because those two are very, very complex in terms of actual hits being made.

**Comment by souvikpodder** [comment]
> By any chance, were you using an Anemo or Hydro skill when this happened? Because those two are very, very complex in terms of actual hits being made.

@WitchGod One time I was using Xiangling's Pyronado (Her Q) other time It was Ayaka's E. The time I pressed Xiangling's and It hit any enemy it crashed. Same with ayaka's E.

**Comment by GarethOz** [comment]
Update: It's from ESP.  4 hours of playing with ESP turned off and no crash. 1 hour of playing with ESP turned on and 2 times crash. I'll open another issue and report this while keeping this one for those who have problem with multi hit.
