### ISSUE TITLE
How to "build it"?

### ISSUE THREAD

**Issue by ClickClack7531** [Akebi-Group/Akebi-GC#501]
I am new to github so Im unsure of how to download this mod in a useable format. People keep saying to "build it manually" yourself, and Im not really sure of what they're talking about. I dont exactly know how to tell Google this in an understandable manner, so for someone who understands what Im asking, can you help me? How to "build it" so that I can use the program?

**Comment by daofeng2015** [comment]
read readme.md

**Comment by ClickClack7531** [comment]
> read readme.md

oh okok. Is there any specific part I should read or is obvious already?

**Comment by harlanx** [comment]
> > read readme.md
> 
> oh okok. Is there any specific part I should read or is obvious already?

just head over to [Latest Release](https://github.com/Akebi-Group/Akebi-GC#latest-release) if you're not going to change anything from the source anyway.

**Comment by ClickClack7531** [comment]
> 

Sure but, referring to [this closed issue](https://github.com/Akebi-Group/Akebi-GC/pull/469), someone was able to update the modder before there was a release, I didnt know where to check for a download link so I scrolled down and saw this person [saying](https://github.com/Akebi-Group/Akebi-GC/pull/469#issuecomment-1225203869) to "build it", and I am confused of what he meant by that. There is this guy that [said](https://github.com/Akebi-Group/Akebi-GC/pull/469#issuecomment-1225799519) he was able to build it himself, but then he also started implying that a certain amount of trust is needed to use the software he built; basically saying that it could be a virus (as far as I know).

So is there anyway for me to build it myself? How do I go about doing that? I checked the notepad and the instructions are unclear.
The first one said to "clone the repository with (git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git)" and it didnt say where to excuse this, I assume to be a command. And from there I was just lost.

**Comment by harlanx** [comment]
> but then he also started implying that a certain amount of trust is needed to use the software he built; basically saying that it could be a virus (as far as I know).

The source is automatically compiled on the Actions tab whenever there's a new commit added so pulling the latest changes and compiling it yourself compare to following the instruction in [Latest Release](https://github.com/Akebi-Group/Akebi-GC#latest-release) section is no different. Downloading it on Actions tab is more convenient than before. However if you're going to make changes from the source code then you'll have to download [git](https://git-scm.com/downloads) and follow the instruction in [Building from source](https://github.com/Akebi-Group/Akebi-GC#building-from-source)

**Comment by ClickClack7531** [comment]
> 

Ohh okok. I see
