### ISSUE TITLE
[BUG]Turn on auto seelie at the location shown in the figure, then the Seelie Lamp will be vacuumed

### ISSUE THREAD

**Issue by pinkMint** [Akebi-Group/Akebi-GC#505]
Turn on auto seelie at the location shown in the figure, then the Seelie Lamp will be vacuumed
![1](https://user-images.githubusercontent.com/45327033/186575013-d7af46db-0d36-4971-8682-b2f4a12914f4.png)
![2](https://user-images.githubusercontent.com/45327033/186575040-f44ec65b-1adc-4d71-aff8-060c11b782bb.png)

**Comment by SummerOfIce** [comment]
I met it too.The Seelie Lamp lifted me up

**Comment by m0nkrel** [comment]
Can you give me info from debug section of menu? Go to debug->entity manager, put checkpoint on sort by distance->set sliders to 5-10 points, stay close to lamp -> If there's only one entity will be shown, click "C" button on the left side and send here

**Comment by pinkMint** [comment]
> 
Entity,RuntimeID,Name,PosX,PosY,PosZ
0x17825e03990,16777669,Avatar_Girl_Bow_Collei(Clone) authority :True,464.7992,155.54439,2340.2979

![image](https://user-images.githubusercontent.com/45327033/186602576-3604d6b4-00b7-489a-b437-3b945fa356ef.png)

**Comment by m0nkrel** [comment]
> > 
> Entity,RuntimeID,Name,PosX,PosY,PosZ
> 0x17825e03990,16777669,Avatar_Girl_Bow_Collei(Clone) authority :True,464.7992,155.54439,2340.2979
> 
> ![image](https://user-images.githubusercontent.com/45327033/186602576-3604d6b4-00b7-489a-b437-3b945fa356ef.png)
> 

Click "Field" tab, you just send me your avatar info

**Comment by pinkMint** [comment]
> > > 
> > 
> > 
> > Entity,RuntimeID,Name,PosX,PosY,PosZ
> > 0x17825e03990,16777669,Avatar_Girl_Bow_Collei(Clone) authority :True,464.7992,155.54439,2340.2979
> > ![image](https://user-images.githubusercontent.com/45327033/186602576-3604d6b4-00b7-489a-b437-3b945fa356ef.png)
> 
> ‎点击“字段”选项卡，‎‎你只是给我发送你的头像信息。您必须在名称中看到带有“Seelie”的内容‎

My English is not very good, I used the translation, I hope I understood what you mean and did it right

Entity,RuntimeID,Name,PosX,PosY,PosZ
0x17825e10890,67132999,SceneObj_Area_Xm_Property_Ani_Prop_LifeSeelieBase_01(Clone) authority :True,464.79333,154.49017,2340.2786
