### ISSUE TITLE
is there a risk now?

### ISSUE THREAD

**Issue by zxfr1x** [Akebi-Group/Akebi-GC#506]
Is there a huge risk to use now, because there was an update in the game, but not in the cheat?

**Comment by souvikpodder** [comment]
Download the latest version from github action page of this project choose the master branch.
![image](https://user-images.githubusercontent.com/11691954/186583580-f5c60bbc-9c0b-46c0-bb35-9382341623ab.png)
![image](https://user-images.githubusercontent.com/11691954/186583845-ec42197f-af92-4690-a507-a9b791b1a66d.png)


Cheat receives update very frequently. Don't use the version from release page. It's outdated.
