### ISSUE TITLE
[question] got this at cheat start, is this normal?

### ISSUE THREAD

**Issue by Lunairayz** [Akebi-Group/Akebi-GC#51]
`[Info] [debugger.cpp:5] You have no implementation for anti-debugger bypass.`
        `So if you try to attach VS debugger to process - game will crash.`
`[Debug] [main.cpp:42] Waiting 10sec for loading game library.`
`[libil2cpp] Failed to resolve 3441514353 at startup`
`[libil2cpp] Failed to resolve 2641773275 at startup`
`[libil2cpp] Failed to resolve 3753878500 at startup`
`[libil2cpp] Failed to resolve 1688788800 at startup`
`[libil2cpp] Failed to resolve 226400704 at startup`
`[libil2cpp] Failed to resolve 58785463 at startup`
`[libil2cpp] Failed to resolve 1939797683 at startup`
`[libil2cpp] Failed to resolve 2903149294 at startup`
`[libil2cpp] Failed to resolve 2562068797 at startup`
`[libil2cpp] Failed to resolve 3930322565 at startup`
`[libil2cpp] Failed to resolve 6384987 at startup`
`[libil2cpp] Failed to resolve 2575356080 at startup`
`[libil2cpp] Failed to resolve 1941095530 at startup`
`[libil2cpp] Failed to resolve 2865846701 at startup`
`[libil2cpp] Failed to resolve 1517977322 at startup`
`[libil2cpp] Failed to resolve 1693804983 at startup`
`[libil2cpp] Failed to resolve 2003222432 at startup`
`[libil2cpp] Failed to resolve 2712004091 at startup`
`[libil2cpp] Failed to resolve 1020683987 at startup`
`[libil2cpp] Failed to resolve 8816388 at startup`
`[libil2cpp] Failed to resolve 9536913 at startup`
`[libil2cpp] Failed to resolve 1027861516 at startup`
`[libil2cpp] Failed to resolve 4038734957 at startup`
`[libil2cpp] Failed to resolve 1818716327 at startup`
`[libil2cpp] Failed to resolve 3391394623 at startup`
`[libil2cpp] Failed to resolve 1557896493 at startup`
`[libil2cpp] Failed to resolve 3358258527 at startup`
`[libil2cpp] Failed to resolve 3785177232 at startup`
`[libil2cpp] Failed to resolve 3543963659 at startup`
`[libil2cpp] Failed to resolve 3481876687 at startup`
`[libil2cpp] Failed to resolve 450655222 at startup`
`[libil2cpp] Failed to resolve 4273534755 at startup`
`[libil2cpp] Failed to resolve 3461698614 at startup`
`[libil2cpp] Failed to resolve 942535243 at startup`
`[libil2cpp] Failed to resolve 151076345 at startup`
`[libil2cpp] Failed to resolve 1606371981 at startup`
`[libil2cpp] Failed to resolve 2851975487 at startup`
`[libil2cpp] Failed to resolve 522744461 at startup`
`[libil2cpp] Failed to resolve 2991550626 at startup`
`[libil2cpp] Failed to resolve 390404921 at startup`
`[libil2cpp] Failed to resolve 2872573901 at startup`
`[libil2cpp] Failed to resolve 3612831164 at startup`
`[libil2cpp] Failed to resolve 225035686 at startup`
`[libil2cpp] Failed to resolve 1906895388 at startup`
`[libil2cpp] Failed to resolve 3086644138 at startup`
`[libil2cpp] Failed to resolve 2210235184 at startup`
`[libil2cpp] Failed to resolve 3623449757 at startup`
`[libil2cpp] Failed to resolve 3441087336 at startup`
`[libil2cpp] Failed to resolve 2752994660 at startup`
`[libil2cpp] Failed to resolve 3744257337 at startup`
`[libil2cpp] Failed to resolve 947602199 at startup`
`[libil2cpp] Failed to resolve 276167041 at startup`
`[libil2cpp] Failed to resolve 4190152843 at startup`
`[libil2cpp] Failed to resolve 530248653 at startup`
`[libil2cpp] Failed to resolve 1422124196 at startup`
`[libil2cpp] Failed to resolve 3374364589 at startup`
`[libil2cpp] Failed to resolve 3985880929 at startup`
`[libil2cpp] Failed to resolve 3422047072 at startup`
`[libil2cpp] Failed to resolve 1535130118 at startup`
`[libil2cpp] Failed to resolve 1933204009 at startup`
`[libil2cpp] Failed to resolve 114730323 at startup`
`[libil2cpp] Failed to resolve 202303721 at startup`
`[libil2cpp] Failed to resolve 1563960715 at startup`
`[libil2cpp] Failed to resolve 1977215634 at startup`
`[libil2cpp] Failed to resolve 769493631 at startup`
`[libil2cpp] Failed to resolve 1826682931 at startup`
`[libil2cpp] Failed to resolve 1747467958 at startup`
`[libil2cpp] Failed to resolve 2056840321 at startup`
`[libil2cpp] Failed to resolve 321950413 at startup`
`[libil2cpp] Failed to resolve 2854572045 at startup`
`[libil2cpp] Failed to resolve 1033957300 at startup`
`[libil2cpp] Failed to resolve 2439655077 at startup`
`[libil2cpp] Failed to resolve 924655391 at startup`
`[libil2cpp] Failed to resolve 730661976 at startup`
`[libil2cpp] Failed to resolve 1300247700 at startup`
`[libil2cpp] Failed to resolve 1285467899 at startup`
`[libil2cpp] Failed to resolve 2435208031 at startup`
`[libil2cpp] Failed to resolve 614283954 at startup`
`[libil2cpp] Failed to resolve 1716575105 at startup`
`[libil2cpp] Failed to resolve 2612210777 at startup`
`[libil2cpp] Failed to resolve 1911644597 at startup`
`[libil2cpp] Failed to resolve 667966253 at startup`
`[libil2cpp] Failed to resolve 4130699544 at startup`
`[libil2cpp] Failed to resolve 3022671661 at startup`
`[libil2cpp] Failed to resolve 2598880730 at startup`
`[libil2cpp] Failed to resolve 3440846679 at startup`
`[libil2cpp] Failed to resolve 1367579839 at startup`
`[libil2cpp] Failed to resolve 3539771435 at startup`
`[libil2cpp] Failed to resolve 4224286087 at startup`
`[libil2cpp] Failed to resolve 3660518774 at startup`
`[libil2cpp] Failed to resolve 658583999 at startup`
`[libil2cpp] Failed to resolve 3975964956 at startup`
`[libil2cpp] Failed to resolve 2392512779 at startup`
`[libil2cpp] Failed to resolve 3614197336 at startup`
`[libil2cpp] Failed to resolve 4180248559 at startup`
`[libil2cpp] Failed to resolve 2670773338 at startup`
`[libil2cpp] Failed to resolve 2259881013 at startup`
`[libil2cpp] Failed to resolve 387612787 at startup`
`[libil2cpp] Failed to resolve 2537559454 at startup`
`[libil2cpp] Failed to resolve 2142178037 at startup`
`[libil2cpp] Failed to resolve 2101111630 at startup`
`[libil2cpp] Failed to resolve 3727464574 at startup`
`[libil2cpp] Failed to resolve 670802134 at startup`
`[libil2cpp] Failed to resolve 4117819129 at startup`
`[libil2cpp] Failed to resolve 2299208424 at startup`
`[Debug] [PatternScanner.cpp:248] Module C:\Program Files\Genshin Impact\Genshin Impact game\UnityPlayer.dll bound 0x00007FFF417A0000-0x00007FFF43989000.`
`[Warning] [il2cpp-init.cpp:148] Seems like assembly checksum don't match with version 2.7. It's normal only if you using Chinese version of genshin impact.`

**Comment by foxxy219** [comment]
"Seems like assembly checksum don't match with version 2.7. It's normal only if you using Chinese version of genshin impact."
Clearly written, Callow is working on it
