### ISSUE TITLE
[New Feature Request] Stats Multiplier option

### ISSUE THREAD

**Issue by Kazuki7877** [Akebi-Group/Akebi-GC#513]
Hello, Could you please add the Stats Multiplier option on injector ?
Here the code using in Cheat Engine Table and still working on 3.0 : 

[ENABLE]
{aobscanmodule(aostats,UserAssembly.dll,F3 0F ? ? ? F3 0F ? ? 48 8B ? ? ? ? ? ? F3 0F)
alloc(nstats,$1000,aostats)
alloc(set_stats,$4)
label(rstats)
label(resstats)
set_stats:
dd (float)50
nstats:
movss xmm0,[set_stats]
resstats:
readmem(aostats,5)
jmp rstats
aostats:
jmp nstats
rstats:
registersymbol(aostats resstats set_stats)
}
//SinGul4ritY
aobscanmodule(hookStats,UserAssembly.dll,f3xxxxxxxxf3xxxxxx48xxxxxxxxxxxxxxf3xxxxxxf3xxxxxxxxf3xxxxxxf3xxxxxx48) // +4DC5816
alloc(newmem,64,hookStats)
alloc(orgcode,5,hookStats)

label(return)
label(set_stats)

registersymbol(hookStats)
registersymbol(set_stats)
registersymbol(orgcode)

orgcode:
    readmem(hookStats, 5)

newmem:
    movss xmm0,[set_stats]
    jmp return

set_stats:
    dd (float)50

hookStats:
    jmp newmem

return:

[DISABLE]
hookStats:
    readmem(orgcode, 5)

unregistersymbol(*)
dealloc(*)

**Comment by Taiga74164** [comment]
what kinda signature is this shit. it doesnt even exist

**Comment by Taiga74164** [comment]
shit script

**Comment by Lunairayz** [comment]
rolled by taiga with 2 words <:KEKW:987140202231382056>

**Comment by Taiga74164** [comment]
im changing value of ``__this->fields._paramDelta`` and it doesnt do shit for all characters

**Comment by Taiga74164** [comment]
this script is half asssed

**Comment by Taiga74164** [comment]
dont see the point of adding this. youre better off with multi hit.. you might as well just string edit the string value of your character stats 💀 
![image](https://user-images.githubusercontent.com/67109235/186754601-3030f1db-1a71-410d-a2e2-1b703a7249f5.png)

![image](https://user-images.githubusercontent.com/67109235/186754627-1503e9ab-300d-4822-a217-ba5a9b299d72.png)

**Comment by Kazuki7877** [comment]
The interest of this feature is for some character having a stats change with Passive or Skills like these character : 
Shogun raiden Q with stacks
Hu TAO with her E
Rosalia give 300%+ crit rate for entire team after the Q
Dendro Traveler E+Q multplier with passive
Diluc Q

Also, this feature work for some weapons based on certain passive, like these : 
Redhorn Stonethresher
Wavebreaker’s Fin
Akuoumaru
Mouun’s Moon

Bennet buff not working since 2.7 update but all the others works

**Comment by Taiga74164** [comment]
im not gonna add it since i think it's useless coz the damage doesn't even actually increase despite what it says on the character's stats..
