### ISSUE TITLE
ERROR in build solution

### ISSUE THREAD

**Issue by ATF-zero** [Akebi-Group/Akebi-GC#52]
![image](https://user-images.githubusercontent.com/53086059/171198338-3adc52ef-614f-49a5-a1e2-dd6203b96998.png)

**Comment by ATF-zero** [comment]
I just download the src, click "akebi-gc.sln" and try to build solution in VS2022

**Comment by Lunairayz** [comment]
![image](https://user-images.githubusercontent.com/45308130/171198824-42891774-65ba-41f4-ae4e-659f131d5366.png)
![image](https://user-images.githubusercontent.com/45308130/171198898-c1db7bb0-f075-49e0-8a87-2b71b9203561.png)


_wait until vs clones it_

click akebi-gc.sln and build

**Comment by WitchGod** [comment]
Would it be so difficult to actually read through the README and find the answer there?

**Comment by Lunairayz** [comment]
> Would it be so difficult to actually read through the README and find the answer there?

nobody (only me probably) knows how to get `git` as a command lol

**Comment by thegodfatheroflove** [comment]
delete old repository and then download git to clone repository 
then follow tutorial from readme
