### ISSUE TITLE
game crash on start

### ISSUE THREAD

**Issue by NikoIkigai** [Akebi-Group/Akebi-GC#520]
whenever i'm trying to open the game it crash when hoyoverse logo shows up.

**Comment by gawgua** [comment]
- Check the version you are using
- Use the lastest build from Actions
![image](https://user-images.githubusercontent.com/104498646/186793984-ea1d7d7d-663d-4590-9e3a-182673315013.png)
- Provide image of the console

**Comment by Taiga74164** [comment]
> latest version, but suddenly it say I am using the chinese version of the game, but I am not
> 
> ![Capture](https://user-images.githubusercontent.com/112114742/186800035-58134c16-7d2f-4d35-b7a7-452cdfaef8fa.PNG)
> 


you downloaded the beta version. master branch is for global version.. read what it says on README
