### ISSUE TITLE
[bug] multi-target not work

### ISSUE THREAD

**Issue by jasonliaotw** [Akebi-Group/Akebi-GC#527]
as title

**Comment by Taiga74164** [comment]
how? it's literally working fine right now?

**Comment by jasonliaotw** [comment]
work with multi-hit
but not working standalong

**Comment by Taiga74164** [comment]
yes it was intended like that

**Comment by jasonliaotw** [comment]
In the last version can work standalone
![image](https://user-images.githubusercontent.com/34159592/187169421-7da33765-5004-4e7f-9a46-02d717a118ce.png)
