### ISSUE TITLE
v0.9 (Anime Game v.3.0) is crashing the game.

### ISSUE THREAD

**Issue by lineageosUs** [Akebi-Group/Akebi-GC#533]
Steps to reproduce:
++Unpack the release
++Double click the injector binary.
++The game is launching but then crashes immediately.

**Comment by 21009123** [comment]
try update your graphic driver

**Comment by Taiga74164** [comment]
your steps doesn't really help since it's working fine on my end 💀 . sounds more like an issue on your end
