### ISSUE TITLE
Add a skin changer

### ISSUE THREAD

**Issue by Samus0754** [Akebi-Group/Akebi-GC#535]
I was thinking if we could implement our own skins for our characters In game. It would be only client side so nobody would see our modified skin :))

**Comment by Kendu303** [comment]
Texture changer exists, Visual -> Texture Changer

**Comment by Taiga74164** [comment]
user our friends' [GI Assets](https://github.com/zeroruka/GI-Assets) and [3dmigoto](https://github.com/SilentNightSound/GI-Model-Importer)
