### ISSUE TITLE
Make it so custom weather and auto cook saves the user’s choice

### ISSUE THREAD

**Issue by Kendu303** [Akebi-Group/Akebi-GC#537]
afaik these 2 functions will reset its options after relaunching the game

**Comment by Lunairayz** [comment]
you're high then

**Comment by Kendu303** [comment]
As for custom weather, it’ll default to clearsky after relaunch, and for autocook, idk if its only me but the cooking quality will default to normal after relaunch

**Comment by Taiga74164** [comment]
Auto Cook saves, Custom Weather doesnt

**Comment by Kendu303** [comment]
> Auto Cook saves, Custom Weather doesnt

Weird, Auto Cook quality just doesn’t save for me, maybe you can try looking into it

**Comment by Taiga74164** [comment]
oh okay it doesnt. my bad

**Comment by Taiga74164** [comment]
fixed 1/2 #632
