### ISSUE TITLE
Building Solution gives off error vibes

### ISSUE THREAD

**Issue by Fractune** [Akebi-Group/Akebi-GC#54]
I downloaded this repo -> extracted the folder -> opened `akebi-gc.sln` -> Set `cheat-library` as startup project -> Build Solution, this is what I'm getting in the prompt:
![image](https://user-images.githubusercontent.com/74881934/171227689-b85b7819-725c-48a9-83e1-260fd911a1c0.png)

I'm trying to build this in order to use the latest version of this tool (though I've no exp about vs) lmk if I'm doing this right

**Comment by hattoya** [comment]
> I downloaded this repo -> extracted the folder -> opened `akebi-gc.sln` -> Set `cheat-library` as startup project -> Build Solution, this is what I'm getting in the prompt: ![image](https://user-images.githubusercontent.com/74881934/171227689-b85b7819-725c-48a9-83e1-260fd911a1c0.png)
> 
> I'm trying to build this in order to use the latest version of this tool (though I've no exp about vs) lmk if I'm doing this right


If you succeed, please give me a link

**Comment by Fractune** [comment]
@hattoya Slide me your discord
