### ISSUE TITLE
Running the game crashes

### ISSUE THREAD

**Issue by tao66688** [Akebi-Group/Akebi-GC#546]
![123](https://user-images.githubusercontent.com/112088430/187038526-3e136902-04b4-4fe5-924e-756929c95570.png)
The downloaded Chinese version, the game is also Chinese, the administrator runs, and the directory is also correct

**Comment by Taiga74164** [comment]
game not updated to 3.0

**Comment by tao66688** [comment]
I used it after the update. How can it not be 3.0

**Comment by tao66688** [comment]
> 游戏未更新到 3.0

![image](https://user-images.githubusercontent.com/112088430/187088898-7418be5c-58a9-487a-a154-b95ebe19b379.png)

**Comment by Taiga74164** [comment]
there's also global and Chinese version
