### ISSUE TITLE
Complete quest 

### ISSUE THREAD

**Issue by yupeii123** [Akebi-Group/Akebi-GC#549]
How to force complete quest? I cant complete one cuz Arama isnt here 
![image](https://user-images.githubusercontent.com/105081907/187043654-2198e6ae-d7f6-4e82-b231-78b79d2d1bea.png)
I would really appreciate if someone helps me

**Comment by Lunairayz** [comment]
you can't KEK

**Comment by Lunairayz** [comment]
you can't <:KEKW:987140202231382056>, enjoy suffering until you dm hyv support

**Comment by Lunairayz** [comment]
<:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056><:KEKW:987140202231382056>

**Comment by xMizuHix** [comment]
> How to force complete quest? I cant complete one cuz Arama isnt here ![image](https://user-images.githubusercontent.com/105081907/187043654-2198e6ae-d7f6-4e82-b231-78b79d2d1bea.png) I would really appreciate if someone helps me

get support , u will be get a one month ban , even if u were caught previously ,

**Comment by Emilia33** [comment]
> How to force complete quest? I cant complete one cuz Arama isnt here ![image](https://user-images.githubusercontent.com/105081907/187043654-2198e6ae-d7f6-4e82-b231-78b79d2d1bea.png) I would really appreciate if someone helps me

what did you do lol

**Comment by Taiga74164** [comment]
Can't force finish the quest on official server
