### ISSUE TITLE
auto talk gery screen issue new appearance scene

### ISSUE THREAD

**Issue by SunnySissi** [Akebi-Group/Akebi-GC#557]
![image](https://user-images.githubusercontent.com/92515662/187054174-d782937d-f1e0-4bdb-983a-ba72751ff437.png)
when unlock the tree of dream(?i dont know what name it is).
Need help to filing.

**Comment by harlanx** [comment]
> ![image](https://user-images.githubusercontent.com/92515662/187054174-d782937d-f1e0-4bdb-983a-ba72751ff437.png) when unlock the tree of dream(?i dont know what name it is). Need help to filing.

just restart the game. also don't use fast dialog with too much high value. usually 3-5 is enough
