### ISSUE TITLE
Publish #88 supposed to fix the warming seelie(red seelie in snow mountain area) but it broke the regular seelie(blue seelie) as well

### ISSUE THREAD

**Issue by TehChozinOne** [Akebi-Group/Akebi-GC#560]
As title. Now the blue seelie also won't move

**Comment by TehChozinOne** [comment]
I went back to publish #85 and blue seelie works as intended

**Comment by Taiga74164** [comment]
ya i noticed that. fixed on https://github.com/Akebi-Group/Akebi-GC/commit/5a09e9f61b4a9f88673703fba8c645db2fc330b9
