### ISSUE TITLE
[Question] Buried Chest removed from Chest ESP??

### ISSUE THREAD

**Issue by TehChozinOne** [Akebi-Group/Akebi-GC#562]
Is this on purpose? Will you add it back?

**Comment by Taiga74164** [comment]
Disabled for now until there's a better way. You can remove the comment on this [line](https://github.com/Akebi-Group/Akebi-GC/blob/e1eb574f10cd1848a6df79f636bed5ddeca176e6/cheat-library/src/user/cheat/esp/ESP.cpp#L584) if you want, but issue #447 still persist

**Comment by TehChozinOne** [comment]
Got it, thank you
