### ISSUE TITLE
weird runtime error

### ISSUE THREAD

**Issue by CriticalMomento** [Akebi-Group/Akebi-GC#565]
![image](https://user-images.githubusercontent.com/74601249/187066576-64375475-4d5d-40b2-a082-fedd6afb9f0d.png)
i never got this before
i just updated the game and downloaded the new version of akebi and this is what i get

**Comment by angry-orange** [comment]
Please, you try to delete your `cfg.*` files and you try again. (Make sure you make backup before this operation).

**Comment by Taiga74164** [comment]
cfg issue. refer to  https://github.com/Akebi-Group/Akebi-GC/issues/429#issuecomment-1208396833
