### ISSUE TITLE
auto seelie cant work

### ISSUE THREAD

**Issue by SunnySissi** [Akebi-Group/Akebi-GC#569]
using version：

[Merge pull request #561 from Akebi-Group/master](https://github.com/Akebi-Group/Akebi-GC/actions/runs/2941872952)
Publish #92: Commit [ecec0c3](https://github.com/Akebi-Group/Akebi-GC/commit/ecec0c3c68da72ca343d9f57958e6ea22c219d1a) pushed by [Taiga74164](https://github.com/Taiga74164)

**Comment by Taiga74164** [comment]
?
https://streamable.com/ng0jp9

**Comment by SunnySissi** [comment]
> ? https://streamable.com/ng0jp9

not work for me , i will upload my video

**Comment by SunnySissi** [comment]
https://streamable.com/4u5hkv

**Comment by SunnySissi** [comment]
version
[Merge pull request #551 from Akebi-Group/conflict](https://github.com/Akebi-Group/Akebi-GC/actions/runs/2940829175)
Publish #86: Commit [7e6b37f](https://github.com/Akebi-Group/Akebi-GC/commit/7e6b37fe29d5c5e56ab8a162156dc4b5d076bc40) pushed by [Taiga74164](https://github.com/Taiga74164)
this version working well,seems like some reason([Fixed #552, Added Dendro Seelie to ESP](https://github.com/Akebi-Group/Akebi-GC/actions/runs/2940908796),maybe this?) cause that.

**Comment by Taiga74164** [comment]
hmmm

**Comment by Taiga74164** [comment]
Can i have the approximate location of this seelie. i need to check if it has a different name

**Comment by SunnySissi** [comment]
> Can i have the approximate location of this seelie. i need to check if it has a different name
![image](https://user-images.githubusercontent.com/92515662/187320814-5d34beb8-7634-4240-bbec-afe9cb728c4c.png)
maybe this area？I forgot it

**Comment by Taiga74164** [comment]
@SunnySissi found the same seelie..
it works fine here with latest commit

https://streamable.com/wk2aqd

**Comment by SunnySissi** [comment]
> @SunnySissi found the same seelie.. it works fine here with latest commit
> 
> https://streamable.com/wk2aqd

thank u for u work,i am already using the lastest version.Thank so much.
