### ISSUE TITLE
Is it possible to remove completed time trial from ESP?

### ISSUE THREAD

**Issue by Kendu303** [Akebi-Group/Akebi-GC#571]
Whether it's completed or not, it still shows up in the esp so I came up with an idea
There's a red mark thingy above the time trial indicating if it's completed or not, would it be possible to use that to differentiate between completed and uncompleted ones?

**Comment by Taiga74164** [comment]
was working in this with @m0nkrel but there were some in issues

**Comment by Taiga74164** [comment]
also duplicate of #345
