### ISSUE TITLE
(BUG) Multi-target does not work without the multi-hit option

### ISSUE THREAD

**Issue by Sarvensky** [Akebi-Group/Akebi-GC#578]
Most likely after fixing the extra hits in multi-hit, the multi-target option stopped working as an independent choice.

**Comment by Sarvensky** [comment]
I am not a developer and do not know how to work with github, so I will write here, I hope it will be understandable.
File RapidFire.cpp (cheat-library\src\user\cheat\player)
Block (function?) static void LCBaseCombat_DoHitEntity_Hook
A piece of code at the end.

In version 0.9 it looks like this
> for (const auto& entity : validEntities) {
> if (rapidFire.f_MultiHit) {
> int attackCount = rapidFire.GetAttackCount(__this, entity->runtimeID(), attackResult);
> for (int i = 0; i < attackCount; i++)
> app::MoleMole_LCBaseCombat_FireBeingHitEvent(__this, entity->runtimeID(), attackResult, method);
> }
> }
> CALL_ORIGIN(LCBaseCombat_DoHitEntity_Hook, __this, targetID, attackResult, ignoreCheckCanBeHitInMP, method);
> 
Multitarget only works together with multihit

In version 0.8 it was
> for (const auto& entity : validEntities) {
> if (rapidFire.f_MultiHit) {
> int attackCount = rapidFire.GetAttackCount(__this, entity->runtimeID(), attackResult);
> for (int i = 0; i < attackCount; i++)
> CALL_ORIGIN(LCBaseCombat_DoHitEntity_Hook, __this, entity->runtimeID(), attackResult, ignoreCheckCanBeHitInMP, method);
> } else CALL_ORIGIN(LCBaseCombat_DoHitEntity_Hook, __this, entity->runtimeID(), attackResult, ignoreCheckCanBeHitInMP, method);
> }
Everything worked together and separately

I did the following in my local copy
> for (const auto& entity : validEntities) {
> 
> if (rapidFire.f_MultiHit) {
> int attackCount = rapidFire.GetAttackCount(__this, entity->runtimeID(), attackResult);
> for (int i = 0; i < attackCount; i++)
> app::MoleMole_LCBaseCombat_FireBeingHitEvent(__this, entity->runtimeID(), attackResult, method);
> } else app::MoleMole_LCBaseCombat_FireBeingHitEvent(__this, entity->runtimeID(), attackResult, method);
> }
> 
> //CALL_ORIGIN(LCBaseCombat_DoHitEntity_Hook, __this, targetID, attackResult, ignoreCheckCanBeHitInMP, method);

And the multitargeter worked separately from the mutil hit again. Simultaneous works too, didn't break)
I have no idea if this is correct or not, but who has a chance, please take a look and fix the option in the master branch :)

**Comment by Taiga74164** [comment]
i removed the else statement to fix #449 but i'll have a look

**Comment by Taiga74164** [comment]
ok

https://user-images.githubusercontent.com/67109235/187347280-c0da8adc-4c81-4bcc-bed4-d4975f591f3f.mp4
