### ISSUE TITLE
Yelan's breakthrough barb does no damage with multi-hit enabled

### ISSUE THREAD

**Issue by MuffinLightning** [Akebi-Group/Akebi-GC#58]
This is an issue with the new character Yelan, can be tested via the character trial by going to events ingame.

 > Yelan will enter a "Breakthrough" state after spending 5s out of combat, which will cause her next Charged Aimed Shot to have 80% decreased charge time, and once charged, she can fire a "Breakthrough Barb" that will deal AoE Hydro DMG based on Yelan's Max HP.

To reproduce, enable multi-hit (I tested with it set to 2), go to Yelan's trial under Events. When her bracelet is glowing, fire a charged shot.

Normal charged shot (not in breakthrough state) works fine.

**Comment by Taiga74164** [comment]
Known issue. Multi Hit doesn't work on some skills
