### ISSUE TITLE
[BUG]world—auto talk,After the dialogue ends, the screen will turn black. Then you can't operate the characters and can only exit the game

### ISSUE THREAD

**Issue by Si-JiX** [Akebi-Group/Akebi-GC#581]
The specific trigger mechanism of the bug is not clear. The most recent occurrence is the "forest book" task. The dialogue before and after the final boss will trigger this bug

**Comment by darkharrycracker** [comment]
This happens everytime in stormterror

**Comment by 1zhangtengfang** [comment]
It seems that it can be released after a while. It may be because the animation on the client is still playing. Wait for the animation to end

**Comment by Si-JiX** [comment]
> 好像过段时间就可以放出来了。可能是因为客户端上的动画还在播放。等待动画结束

i will try it

**Comment by Si-JiX** [comment]
> 老bug了，加速过场动画概率出现，，，目前只能做到把黑幕去掉，鼠标点击有效，但键盘输入依然被屏蔽了

你可以试试开no clip，这样变黑的时候也可以移动

**Comment by Taiga74164** [comment]
Happens when fast dialogue value is too high. Setting it around 5 is fine.
![image](https://user-images.githubusercontent.com/67109235/187327049-0c9bf597-ccca-4b89-b910-d46685d681a0.png)
