### ISSUE TITLE
[New Feature] Localize Akebi-GC for Chinese players.

### ISSUE THREAD

**Issue by Someone999** [Akebi-Group/Akebi-GC#585]
Many Chinese players who used Akebi-GC asked me for the translation of it, so could you localize it for Chinese players?

**Comment by Si-JiX** [comment]
会被用作贩卖的，算了吧，连查查英文翻译都懒得查的让他们懒死算了

**Comment by Bilx-ZL** [comment]
简单至极的英文，默认翻译=倒卖。

**Comment by NctimeAza** [comment]
然后方便拿去贩卖是吗？

**Comment by Someone999** [comment]
啊这，没考虑到这一点
