### ISSUE TITLE
[BUG]when auto elec seelie completed,ESP still displaying them 

### ISSUE THREAD

**Issue by SunnySissi** [Akebi-Group/Akebi-GC#587]
BUG pic:
![image](https://user-images.githubusercontent.com/92515662/187325269-156eae6e-43b9-4f83-bbd6-1d41c70dd99d.png)

location:
![image](https://user-images.githubusercontent.com/92515662/187325329-41ac77e1-c1ad-46fb-9f41-966804881429.png)

**Comment by m0nkrel** [comment]
it's been from the start. If @Taiga74164 wants - we can push "hide completed" for electroseelies, elemental monuments and bloatty floatty

**Comment by Taiga74164** [comment]
> it's been from the start. If @Taiga74164 wants - we can push "hide completed" for electroseelies, elemental monuments and bloatty floatty

can. i guess just gotta put a note that it doesnt work for all puzzles.. i already see someone opening an issue about it later :KEKW:

**Comment by Taiga74164** [comment]
#345
