### ISSUE TITLE
help, i can't use the mod :(

### ISSUE THREAD

**Issue by eldantee** [Akebi-Group/Akebi-GC#588]
![Captura de pantalla 2022-08-29 224045](https://user-images.githubusercontent.com/82115990/187340471-73bc51b9-4657-4ab3-a067-7f73104c9b0f.png)
this is what appear when i use the injector.
Can help me?
thank you all <3

**Comment by gawgua** [comment]
i dont see any problems

**Comment by Taiga74164** [comment]
If the menu doesn't show, close any active overlay such as MSI Afterburner, etc.

**Comment by eldantee** [comment]
> 

thank you! i'll try

**Comment by eldantee** [comment]
it was overlay, hahaha, thank u all <3<3<3
