### ISSUE TITLE
News tab wont work

### ISSUE THREAD

**Issue by G1DE30N** [Akebi-Group/Akebi-GC#59]
In latest commit news window simply wont load anything at all.
![image](https://user-images.githubusercontent.com/104440397/171302589-54712fb7-4e5a-4e05-a29e-30b182aa31fd.png)

**Comment by G1DE30N** [comment]
Upd: after at least 1 minute news loads, but categories buttons not clickable 
![image](https://user-images.githubusercontent.com/104440397/171302668-d0b045c2-5167-438f-b71d-50e76f63077d.png)

**Comment by G1DE30N** [comment]
Strange after at least another minute buttons can clikable. But after closing news menu cycle is repeats.

**Comment by Taiga74164** [comment]
theres nothing in the project that could be involved with this issue 😔

**Comment by G1DE30N** [comment]
> theres nothing in the project that could be involved with this issue 😔

Okay, game bug i got it. :(
