### ISSUE TITLE
The game crashes after warning screen in loading phase.

### ISSUE THREAD

**Issue by BackBenchDreamer** [Akebi-Group/Akebi-GC#590]
I run the hack and then after a while the game opens to only close soon afterwards. 
I tried this on my PC, it works marvellously but when I try it in my win10 lap it crashes quite a lot.

**Comment by blackpaper666** [comment]
Same problem here

**Comment by Taiga74164** [comment]
well if it works on your PC and not on your laptop then thats an issue on your end 💀

**Comment by Taiga74164** [comment]
can't really help you. try to capture what the console says
