### ISSUE TITLE
Some monsters is immune to damage with multi hit

### ISSUE THREAD

**Issue by Hy4ri** [Akebi-Group/Akebi-GC#593]
abyss mage is immune to damage with multi hit on

**Comment by Hy4ri** [comment]
mitachurl to

**Comment by WitchGod** [comment]
Currently investigating this, seems like a legit bug. For now, try reverting to a past commit and rebuilding while I have no updates.

**Comment by Sarvensky** [comment]
Today I noticed that the Stormterror Dvalin boss doesn't respond to multihit either

**Comment by Opokadai** [comment]
can i use older version?

**Comment by Sarvensky** [comment]
> can i use older version?

It seems to me the old version will not help, because in the code of these functions there is no change, at least such that EXACTLY break the damage on the monsters. More like a change within the game and already under them need to make changes in the code of cheats
