### ISSUE TITLE
cheat gui not showing

### ISSUE THREAD

**Issue by DLDRSB** [Akebi-Group/Akebi-GC#595]
when i press f1, nothing shows up

**Comment by DLDRSB** [comment]
it injects fine, and i dont have any sort of overlay going on

**Comment by DLDRSB** [comment]
![image](https://user-images.githubusercontent.com/112501322/187487002-1e523baa-daa9-4dfe-9847-ea50cb10f675.png)

**Comment by Taiga74164** [comment]
yea you must have an active overlay. thats the only possible reason

**Comment by DLDRSB** [comment]
how to remove overlay?

**Comment by DLDRSB** [comment]
i dont even know what an overlay is lol

**Comment by DLDRSB** [comment]
my laptop is brandnew and i didnt really do anything to it. i just downloaded genshin then waited for the cheat.
