### ISSUE TITLE
[Feature Request] Jump up 50 meters with a hotkey

### ISSUE THREAD

**Issue by ali-ee** [Akebi-Group/Akebi-GC#598]
Hello guys,

Tremendous app, thanks to all of you.

I like to explore the game on my own pace without using teleport.

This is all fine while going down but going up is sometimes a big chore.

Can you add a function that lets us teleport 50 meters (maybe editable?) on the Y axis immediately?

**Comment by Taiga74164** [comment]
just no clip?
