### ISSUE TITLE
[Feature Request] Differentiated distance for mobs, small, medium and large.

### ISSUE THREAD

**Issue by IgorBraga21** [Akebi-Group/Akebi-GC#608]
I was testing the mob puller here... Leaving the mobs at the same distance from us is sometimes bad to calibrate, because small mob has to be close while large mob when it gets close, it gets so close that it pushes us to bugat in a wall or in the water... anyway...
Dai was thinking, would it be possible to adjust the distance for small, medium and large mob?

Like the boss or the wolf... if you use a handle they push us...

**Comment by Taiga74164** [comment]
can just remove the collider on mobs instead so it doesn't push you

https://user-images.githubusercontent.com/67109235/187994284-5b8f84a6-1b39-40e6-946b-80ab130d880b.mp4

**Comment by lyc-ch** [comment]
When you turn on the attraction function, you will be "pushed back and forth" by some monsters
