### ISSUE TITLE
Build Error [ Cannot open include file ]

### ISSUE THREAD

**Issue by Viole403** [Akebi-Group/Akebi-GC#61]
So, while doing the process `build > Build Solution / Build injector`
Maybe, is there a mistake from myself when doing the process?

![image](https://user-images.githubusercontent.com/37041952/171309129-94498bfd-5fe5-44f6-bb26-7c0dd4416be9.png)

**Comment by Error-NaN** [comment]
Check out this thread [#48 ](url)

**Comment by Viole403** [comment]
> Check out this thread [#48 ](https://github.com/Akebi-Group/Akebi-GC/issues/48#issue-1253515606). It also had build error. Even @Legend-Recalls is putting prebuilt versions if it still exists. [Check it out](https://github.com/Legend-Recalls/genshin-cheat-releases/releases)

I've looked at the thread, but what I see is a different error.
But thanks for [this ](https://github.com/Legend-Recalls/genshin-cheat-releases/releases)link

**Comment by Fractune** [comment]
Try redoing everything from start by following this guide I just recorded for such situations,
https://youtu.be/vwMT5iwVe9g

**Comment by Shichiha** [comment]
are you sure you followed the [build instructions](https://github.com/Akebi-Group/Akebi-GC#building-from-source)?  

try checking the folders if these files do exist or not, if not, do a recursive clone  
`git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git`

**Comment by tayhm0817** [comment]
did you open akebi-gc.sln?

**Comment by Viole403** [comment]
> are you sure you followed the [build instructions](https://github.com/Akebi-Group/Akebi-GC#building-from-source)?
> 
> try checking the folders if these files do exist or not, if not, do a recursive clone `git clone --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git`

Thanks, i forgot to `--recurse-submodules`
