### ISSUE TITLE
[BUG (I assume)] Changing Display Mode (resolution) glitches the window

### ISSUE THREAD

**Issue by ClickClack7531** [Akebi-Group/Akebi-GC#611]
I am trying to play Genshin on Display Mode 848 x 480, but Genshin keeps reverting it back to 1024 x 768 after I close and reopen the game. This isnt a problem most of the time because I can just revert it back to (848x480) after, but if Im using Genshin with Akebi, if I were to change the resolution, the screen goes extremely weird, and then freezes.
![{3F22D390-2DA7-4B21-ADD6-3508E532D51B}](https://user-images.githubusercontent.com/93358773/188149238-6069691b-1b2a-42e4-bddb-58dcc8fc207f.png)

Is there a way to change Genshin's resolution with Akebi injected?

**Comment by Taiga74164** [comment]
known issue. even with other games.

> Is there a way to change Genshin's resolution with Akebi injected?

for now none

**Comment by ClickClack7531** [comment]
> known issue. even with other games.
> 
> > Is there a way to change Genshin's resolution with Akebi injected?
> 
> for now none

oh okok

**Comment by Taiga74164** [comment]
https://github.com/ocornut/imgui/issues/2170
