### ISSUE TITLE
crashing when starting

### ISSUE THREAD

**Issue by ronyhurtz** [Akebi-Group/Akebi-GC#615]
When I launch the injector the game launches up to the HOYOVERSE logo, When it fades it just stays on a white screen. Eventually it stops responding.
![image_2022-09-03_183513648](https://user-images.githubusercontent.com/103353122/188293376-e4150297-7387-40aa-817b-9e496b630161.png)
![image_2022-09-03_183533377](https://user-images.githubusercontent.com/103353122/188293385-71abee38-dbf9-4410-9faa-7095a53df425.png)

**Comment by Taiga74164** [comment]
https://github.com/Akebi-Group/Akebi-GC/issues/252#issuecomment-1183943663

**Comment by ronyhurtz** [comment]
> [#252 (comment)](https://github.com/Akebi-Group/Akebi-GC/issues/252#issuecomment-1183943663)

my drivers are updated and still does the same issue

**Comment by Taiga74164** [comment]
sounds like an issue on your end then

**Comment by Wujian6T-T** [comment]
I also have this problem
Just wait 2 minutes

I don't know the specific reason

**Comment by JSPiRiT1337** [comment]
had the same issue. it stuck for some time on warning screen or after "loading resources" and then loaded just fine
after updating nvidia drivers game boots as fast as without injector

**Comment by maxshelter** [comment]
same
