### ISSUE TITLE
Captcha GeeTest when entering an account

### ISSUE THREAD

**Issue by N3verLev** [Akebi-Group/Akebi-GC#617]
Is it possible to solve the captcha that appears when you log into an account using the service to solve the captcha? By api key for example? 

If it's possible, I'm ready to order it.

**Comment by qq857857** [comment]
打钱，我已经解决了实名验证跳过登录懂吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Akebi-Group/Akebi-GC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月4日(星期天) 晚上11:48
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Akebi-Group/Akebi-GC] Captcha GeeTest when entering an account (Issue #617)





 
Is it possible to solve the captcha that appears when you log into an account using the service to solve the captcha? By api key for example?
 
If it's possible, I'm ready to order it.

**Comment by N3verLev** [comment]
I don't understand you.(
> 打钱，我已经解决了实名验证跳过登录懂吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Akebi-Group/Akebi-GC" ***@***.***&gt;; 发送时间:&nbsp;2022年9月4日(星期天) 晚上11:48 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[Akebi-Group/Akebi-GC] Captcha GeeTest when entering an account (Issue #617) Is it possible to solve the captcha that appears when you log into an account using the service to solve the captcha? By api key for example? If it's possible, I'm ready to order it. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**Comment by Thafoxes** [comment]
那些杂种拿人家公开的项目来卖还叫你打钱的不需要理他们，这里是免费的。如果是付费跑到这里来的只能说你来交学费买教训而已。

No need to reply to these faggot cause this project is open source and free, if you guys paid u get scammed. Learn your lesson, do more research.

**Comment by N3verLev** [comment]
I haven't ordered anything yet, I just asked if it could be done and done for a small fee, and others started saying don't be fooled by people who cheat you(

But my question still stands

**Comment by Thafoxes** [comment]
My answer already clearly given, is up to you to decide you want to risk it or not. I don't want to repeat again.
