### ISSUE TITLE
About kill Aura

### ISSUE THREAD

**Issue by lyc-ch** [Akebi-Group/Akebi-GC#618]
Brothers, what is the configuration of the killing aura? Why do I set a small time interval, but the damage value still jumps very slowly

**Comment by lyc-ch** [comment]
About the abyss of challenge: how to configure more security

**Comment by Taiga74164** [comment]
> About the abyss of challenge: how to configure more security

clear it without the help of kill aura is the best security since it logs your character's max hit.
