### ISSUE TITLE
The interface of Chinese akebi is still in English, and the browser does not take effect

### ISSUE THREAD

**Issue by notnow1** [Akebi-Group/Akebi-GC#622]
The interface of Chinese akebi is still in English, and the browser does not take effect

**Comment by xuewuji** [comment]
"Chinese" means to support Chinese servers, not chinese mod menu.

**Comment by notnow1** [comment]
Ok, I understand! How to solve the problem that the browser does not display？

**Comment by notnow1** [comment]
thanks a lot for your answer
