### ISSUE TITLE
adding a function【recommend】

### ISSUE THREAD

**Issue by zxcgeorgy** [Akebi-Group/Akebi-GC#626]
add a countdown of the duration of the effects, for example, the action of the shield

**Comment by Taiga74164** [comment]
countdown of duration? just look at your talent skill duration.

**Comment by zxcgeorgy** [comment]
> countdown of duration? just look at your talent skill duration.

this is not convenient, if there was a countdown, it is much more convenient, for example, the freezing effect

**Comment by Taiga74164** [comment]
sounds useless. I don't see a point on adding it. I'd rather add the feature that extends the duration lol

**Comment by zxcgeorgy** [comment]
> sounds useless. I don't see a point on adding it. I'd rather add the feature that extends the duration lol

Is this a good idea, is it possible? if so, can you implement it? a grandfather with an infinite shield is cool

**Comment by Taiga74164** [comment]
> Is this a good idea, is it possible? if so, can you implement it? a grandfather with an infinite shield is cool

Yes. I found it but it's still a work in progress and requires more testing

**Comment by Taiga74164** [comment]
Also if thats what you want. A suggestion is already open on #135

**Comment by zxcgeorgy** [comment]
> > Is this a good idea, is it possible? if so, can you implement it? a grandfather with an infinite shield is cool
> 
> Yes. I found it but it's still a work in progress and requires more testing

I can test this function
