### ISSUE TITLE
【ask for help】

### ISSUE THREAD

**Issue by HikigayaKazuto** [Akebi-Group/Akebi-GC#629]
May i ask why both the ESP, and the tracking chests displayed in both info tab and in teleport sorting, not showing any "unknown" rare chests anymore? (aka the mora rock chest) It still displayed them perfectly about 4-5 days ago, but now the cheat never detect it anymore. Can you check it? I'm using the Global (master) cheat version.

**Comment by AkebiUser** [comment]
how to use, texture changer, send the manual pls

**Comment by Taiga74164** [comment]
well if it worked perfectly fine before then everything should be fine since nothing was changed there in the code since 4months ago
