### ISSUE TITLE
Force Close CC Genshin

### ISSUE THREAD

**Issue by ArthaVerx** [Akebi-Group/Akebi-GC#63]
![Screenshot 2022-06-01 113506](https://user-images.githubusercontent.com/104915027/171322516-92da2127-3be5-449f-b942-393c9b33ac10.png)
Does anyone know how to fix this? cc genshin keep getting closed everytime i open it.

**Comment by LEMON4D3** [comment]
I fix mine just by updating the game first in the launcher and in the main game

**Comment by CallowBlack** [comment]
Is the problem fixed? If not, give more information about.

**Comment by G1DE30N** [comment]
@CallowBlack you can close it. This thing appears on somebody who try launch cheat at 2.7 but not update game from 2.6 from launcher. I check what lemon described above and got same thing in result.

**Comment by ArthaVerx** [comment]
But i already updated the game to 2.7
i've tried many things
installing both vc redist 64x and 86x
installing direct X 11
deleting temp folder
flushing dns
repairing game files
restarting computer

**Comment by G1DE30N** [comment]
> But i already updated the game to 2.7
> i've tried many things
> installing both vc redist 64x and 86x
> installing direct X 11
> deleting temp folder
> flushing dns
> repairing game files
> restarting computer

Try reclone and rebuild cheat from latest commit.
