### ISSUE TITLE
How the risk is when there is no risk tips on the feature

### ISSUE THREAD

**Issue by Someone999** [Akebi-Group/Akebi-GC#635]

**Comment by Lunairayz** [comment]
just use common sense on that sounds dangerous and what isn't, ez

**Comment by Someone999** [comment]
But some features are marked "Extremely risky" at the last version but not marked in this version.

**Comment by Lunairayz** [comment]
yo taiga explain

**Comment by Lunairayz** [comment]
yo taiga explain

**Comment by Taiga74164** [comment]
I actually removed the Extremely risky on a few of them

**Comment by Lunairayz** [comment]
> I actually removed the Extremely risky on a few of them

why tho, more risk for people
