### ISSUE TITLE
Warning and crash

### ISSUE THREAD

**Issue by Abjornn** [Akebi-Group/Akebi-GC#636]
Hello,

When I want to inject I have a message telling me that the checksum does not correspond to version 3.3 and that it is normal if I use the Chinese version but I use the European version (see images)

![image](https://user-images.githubusercontent.com/113095243/189072044-60ee9df1-93c5-44eb-941e-0d3478502e2c.png)

Version :

![image](https://user-images.githubusercontent.com/113095243/189072409-4b1bf399-d600-434c-92e0-b25b4f8214e1.png)

Windows Version : 21H2 (19044.1889)

**Comment by Taiga74164** [comment]
You downloaded the wrong version of Akebi. Use global from release or download the one from [master](https://github.com/Akebi-Group/Akebi-GC/actions?query=branch%3Amaster)

**Comment by Abjornn** [comment]
No i have download master version

**Comment by Taiga74164** [comment]
Well Error only prompts when that happens so

**Comment by Abjornn** [comment]
I'm reinstall al my game and fixed it, Thanks you.
