### ISSUE TITLE
[Bug] Fish will escape after recasting.

### ISSUE THREAD

**Issue by Asayu233** [Akebi-Group/Akebi-GC#637]
When auto recasting the rod, the caught fish will escape.
I think this feature is actually useless, maybe you can make it auto retract the rod after it catches a fish.

https://user-images.githubusercontent.com/76391894/189110142-0880ab37-0439-42e0-b6b4-e0fb46b9577d.mp4

**Comment by Taiga74164** [comment]
escape? but isnt the fish in your inventory already. also #206

**Comment by chirinu** [comment]
> > escape? but isnt the fish in your inventory already.
> 
> Fish caught by re-cast rod will indeed escape, it took two baits and only one fish got into my bag. :(

After you get the fish, immediately pull back your fishing rod and then throw it back manually so as not to consume 2 baits because it fails.
