### ISSUE TITLE
Multi-hit doesn't work on Ores

### ISSUE THREAD

**Issue by boteomap2** [Akebi-Group/Akebi-GC#64]
![image](https://user-images.githubusercontent.com/87257421/171324009-5d84de58-0b54-46ee-b353-f8f60cdb29fe.png)
Like the title, i can't fast mining with multi-hit.

**Comment by foxxy219** [comment]
i thought this only works with mobs, tried in 2.6
you can use destroy ores in range

**Comment by Shichiha** [comment]
It's set to only work for mobs because it is glitchy when used on ores and other stuff (according to reports) :/

**Comment by tedzify** [comment]
This is removed because of people using `One-Punch Mode` crashing when hitting indestructible entities like torches. @WitchGod mentioned that he will reimplement it with more options.
