### ISSUE TITLE
[Suggestion] Add auto claim to Expedition 

### ISSUE THREAD

**Issue by gawgua** [Akebi-Group/Akebi-GC#642]
## Describe the suggestion

Procedural claim each character 
or
Claim all at once

## How does this suggestion work

Work steps:
idk =)))

## Related technologies

Game auto select claimable spot if you switch to tab
![image](https://user-images.githubusercontent.com/104498646/189470015-774ca0b6-4e24-47ce-95ec-3da22993258d.png)
 that have one

## Screenshot/Video

![image](https://user-images.githubusercontent.com/104498646/189469784-ca650766-dd2c-4017-ae5b-1305ecb36dac.png)

**Comment by Taiga74164** [comment]
you lazy mofos #424

**Comment by gawgua** [comment]
ehe~~

**Comment by LunarisFP** [comment]
:P
