### ISSUE TITLE
[Help]I need some help with the cheater

### ISSUE THREAD

**Issue by zhongmof** [Akebi-Group/Akebi-GC#646]
Today, I tried to package the cheater and translate it into Chinese. I simply modified some English prompts in the injector. Later, when I tested it, the game gave me such prompts. How can I solve it？
Thank you for reading my question

**Comment by Taiga74164** [comment]
What does the prompt say?

**Comment by zhongmof** [comment]
It said:you have no implentation for anti-debugger bypass
So if you try to attash VS debugger to process -game will crach

**Comment by Taiga74164** [comment]
> It said:you have no implentation for anti-debugger bypass So if you try to attash VS debugger to process -game will crach

you can ignore that warning.

**Comment by zhongmof** [comment]
But if I ignore this warning, the game will crash

**Comment by Taiga74164** [comment]
It will only crash if you're using the wrong branch

**Comment by zhongmof** [comment]
What do I need to do to solve this problem

**Comment by Taiga74164** [comment]
![image](https://user-images.githubusercontent.com/67109235/189483512-965e2319-8a64-4103-8247-a86711569ce8.png)

**Comment by zhongmof** [comment]
I am a repository cloned from the official link

**Comment by zhongmof** [comment]
I use windows 11 and play the ChinaGenshin

**Comment by Taiga74164** [comment]
> I use windows 11 and play the ChinaGenshin

``git clone -b chinese --recurse-submodules https://github.com/Akebi-Group/Akebi-GC.git``

**Comment by zhongmof** [comment]
I use windows. How do I execute this command

**Comment by zhongmof** [comment]
Thank you very much for your help. My problem has been solved
