### ISSUE TITLE
[Bug] Runtime error

### ISSUE THREAD

**Issue by Kukuru97** [Akebi-Group/Akebi-GC#649]
i got runtime error
already set the QualityField to Normal but still got error
i'm using latest ver from salem injector

the injector work fine after deleting cfg.json, but my profil gone.

![runtime](https://user-images.githubusercontent.com/100615360/189513661-e670d0d1-8858-4cd1-83c8-a9a8a5f5cd81.png)

**Comment by Taiga74164** [comment]
looks like you edited you cfg wrong and you forgot your curly brackets on qualityfield ``{ }``

config should look like this or just remove the whole auto cook field

``            "AutoCook": {
                "Enabled": {
                    "toggled": true,
                    "value": null
                },
                "FastProficiency": {
                    "toggled": true,
                    "value": null
                },
                "QualityField": {
                    "name": "Delicious",
                    "value": 0
                }```

**Comment by Kukuru97** [comment]
thank's now it worked, but the profile still gone.

**Comment by Huiaei** [comment]
I have the same problem
I tried to modify the configuration file, but found that there was a problem in the "profiles" section. After deletion, it can be loaded normally.

**Comment by Huiaei** [comment]
> I have the same problem I tried to modify the configuration file, but found that there was a problem in the "profiles" section. After deletion, it can be loaded normally.

I tried to delete "autocook" directly and it worked normally.
