### ISSUE TITLE
[Bug] Auto Destroy Object Plants doesn't work

### ISSUE THREAD

**Issue by Kukuru97** [Akebi-Group/Akebi-GC#650]
Tittle

Only works on Dandelion Seeds but not work on Sakura Bloom

![image](https://user-images.githubusercontent.com/100615360/189515448-d27fa467-1791-4da5-87b8-4f6c2bfeb8bc.png)

**Comment by Taiga74164** [comment]
read 
https://github.com/Akebi-Group/Akebi-GC/issues/256#issuecomment-1200095390
