### ISSUE TITLE
[Suggestion] Divide the interactive map for each region to manage it easily

### ISSUE THREAD

**Issue by ArthaVerx** [Akebi-Group/Akebi-GC#652]
Basically just make regions have their own mark, so if you want to find the seelie in liyue, the mark will be in liyue only. 
also easier for us who somewhat joined to an account who had already done the region and instead of trying to make it transparent one by one, by dividing the region, you can just go (Mark all as done in Mondstat)

**Comment by Taiga74164** [comment]
the whole map is categorized by sceneID.
