### ISSUE TITLE
Unknown names detected

### ISSUE THREAD

**Issue by nana-qilin** [Akebi-Group/Akebi-GC#655]
New object detected :)
Unknown Names:
SceneObj_Area_Dq_Property_Prop_ReginFeather_01(Clone) authority :True; Position: { x = 0.433105, y = 231.632004, z = 158.343750 }; Scene: 3
SceneObj_Area_Dq_Property_Prop_ReginFeather_01(Clone) authority :True; Position: { x = -60.941895, y = 247.255005, z = 134.948730 }; Scene: 3

These are the feathers that you need to offer to the perchs in sumida's quest in inazuma
(the f*ck off Tsurumi fog quest)

I believe it's a bug that they're being detected as chests since they're more like seelies (they move around when you get near and don't actually have an interact button)

**Comment by Taiga74164** [comment]
its probably a Chest by type that's why
