### ISSUE TITLE
[Suggestion] Export Inventory and Characters data to "GOOD" format .json

### ISSUE THREAD

**Issue by llsf88** [Akebi-Group/Akebi-GC#659]
-->Describe the suggestion
Export all details about the account, like characters with levels and constellations and skill levels. And all Inventory data. In GOOD format to use with Genshin Optimizer.

-->How does this suggestion work
It must be exported to a .json file in GOOD format. Like the app "Invenroty_Kamera" does, but much faster because no image recognition would be needed.

**Comment by gawgua** [comment]
[InventoryKamera](https://github.com/Andrewthe13th/Inventory_Kamera)

**Comment by Shichiha** [comment]
such software exists for this already, it's already quite quick too, and there are alternatives to this InventoryKamera that is more quick maybe (depends on how it use OCR), try use that instead.

**Comment by Taiga74164** [comment]
you must be a masochist to implement this feature in this project💀
