### ISSUE TITLE
UI Bug after enter the chasm underground

### ISSUE THREAD

**Issue by heinzrommel** [Akebi-Group/Akebi-GC#66]
![Screenshot_91](https://user-images.githubusercontent.com/93069552/171326607-02de12be-40f1-4e38-a4b0-f4b2f77e7fdf.png)
![Screenshot_92](https://user-images.githubusercontent.com/93069552/171326616-6a9de2e2-eaf5-48f3-9e02-8254f712c6e9.png)

**Comment by Shichiha** [comment]
duplicate of #15
