### ISSUE TITLE
[Help]Random crashes 

### ISSUE THREAD

**Issue by icercat** [Akebi-Group/Akebi-GC#660]
## Describe the problem

Please fill in here a clear and accurate description of the problem you are experiencing.

## How to reproduce this problem

Steps to reproduce this issue:
1. when map tp failed or 
2. using noclip (happens pretty random (more common in towns))

## Help you need

Please fill in the help you need here.
I hope this info can help it break less often?
## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.

## Your device information
 
 - System information:windows 11 21H2 22000.918
 
 - Version:main Publish # 162 

## Additional information

Here you can enter additional information about the help you need.
do these help?
[mihoyocrash I found in temp.zip](https://github.com/Akebi-Group/Akebi-GC/files/9548485/mihoyocrash.I.found.in.temp.zip)

**Comment by Taiga74164** [comment]
crashlogs doesnt tell us anything

**Comment by Taiga74164** [comment]
never experience any crash with those features you mentioned

**Comment by icercat** [comment]
Ok then I guess it's problem on my end

**Comment by zhongmof** [comment]
> 好吧，那么我想这是我这边的问题

This kind of situation does happen, but it basically happens only after you have done the wrong operation
