### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Mr-Lan1725** [Akebi-Group/Akebi-GC#661]
## Describe the problem
Thank you for the project, it was very useful, but I had a problem. I wanted to use this program Chinese, tried it in the ESP .cpp, but there was garbled code when it was actually running, and it was all "??? ", how do I solve this problem? I look forward to your reply, thank you.
![6a541413c41f2ed1](https://user-images.githubusercontent.com/113295138/189696029-d9b45424-535d-45a7-850d-624e8e3d4089.png)

**Comment by Taiga74164** [comment]
so you changed the font to chinese font?

**Comment by Taiga74164** [comment]
What else did you change lol. It can't just say "???" without changing something

**Comment by Mr-Lan1725** [comment]
I changed the string in the image to Chinese, but it was "? ”

**Comment by zhongmof** [comment]
...

**Comment by zhongmof** [comment]
不是

**Comment by Taiga74164** [comment]
use a Chinese font. change string to u8"透视". figure out the rest

**Comment by Mr-Lan1725** [comment]
Why Can't I display Chinese using u8"透视"?
![捕获](https://user-images.githubusercontent.com/113295138/189819519-d23037bc-9a12-4a56-ac1a-3c45edf45fc7.PNG)
Here's the code I modified
![捕获](https://user-images.githubusercontent.com/113295138/189819640-464f7a73-60a5-414e-aa10-fcfaab9b7477.PNG)

**Comment by Mr-Lan1725** [comment]
![Yuan Shen 原神 Screenshot 2022 09 13 - 13 35 50 67](https://user-images.githubusercontent.com/113295138/189820112-7089db2d-1bd2-4cd7-bd12-8c9f7d69ba5a.png)

**Comment by Taiga74164** [comment]
I told you already
