### ISSUE TITLE
[Suggestion]A suggestion about cameras

### ISSUE THREAD

**Issue by zhongmof** [Akebi-Group/Akebi-GC#663]
I would like to suggest adding the camera filter function in the game, because in China Genshin Impact and Pizza Hut have launched a linkage prop about the camera. He added a filter for the camera, which seems to be called "exquisite camera" in the international service name

**Comment by Taiga74164** [comment]
I don't understand what you want. There's no filter on the exquisite camera that you mention of

**Comment by Thafoxes** [comment]
你用回汉语看看让我们知道你在说什么，我们看不懂

**Comment by zhongmof** [comment]
嘶，就是必胜客那个联动道具，那个智障一样的滤镜我寻思能不能改出来

**Comment by zhongmof** [comment]
> 你用回汉语看看让我们知道你在说什么，我们看不懂

嘶，就是必胜客那个联动道具，那个智障一样的滤镜我寻思能不能改出来

**Comment by zhongmof** [comment]
> 我不明白你想要什么。你提到的精致相机上没有滤镜


That item has not been officially enabled in global At present, the global version can only be found in private servers
