### ISSUE TITLE
[Help] Error-6

### ISSUE THREAD

**Issue by EnderMaster1010** [Akebi-Group/Akebi-GC#664]
Whenever I open the client, comes up with the following error message. This immediatly appears after I give a path. I am using latest version and I the path I give is the correct location

![image](https://user-images.githubusercontent.com/113416723/189825910-44d43b33-90ca-4943-9ecc-89e722c0d6c8.png)

**Comment by Taiga74164** [comment]
I suggest you look at previous issues before opening one.
https://github.com/Akebi-Group/Akebi-GC/issues/614#issuecomment-1236190491_
