### ISSUE TITLE
GOD MODE activation to be based on the number of times....

### ISSUE THREAD

**Issue by AK-Rezina** [Akebi-Group/Akebi-GC#671]
### Bebased on the number of times....
Each time it returns false, the count increases, and when it reaches a certain value, it will be ture next time.

If the value is 3.

> 1st
> ⚪ 
> 2nd 
> ⚪⚪ 
> 3rd
> ⚪⚪⚪

  **Reset the count and return Ture**

> 1st
> ⚪ .......

**Comment by harlanx** [comment]
hoyoverse gacha mechanics on god mode? 😄

**Comment by AK-Rezina** [comment]
\Akebi-Group\Akebi-GC\cheat-library\src\user\cheat\player\GodMode.cpp

```
bool GodMode::Miscs_CheckTargetAttackable_Hook(app::BaseEntity* attacker, app::BaseEntity* target, MethodInfo* method)
	{
        auto& gm = GodMode::GetInstance();
        auto& manager = game::EntityManager::instance();
        auto entity = manager.entity(target);
        if (gm.f_Enabled && entity->isAvatar())
            return false;

		return CALL_ORIGIN(Miscs_CheckTargetAttackable_Hook, attacker, target, method);
	}
	
```
Can you add this to the above process?
I saw an idea earlier that you wanted GODMODE to be triggered only once every few times, so I made this suggestion.

**Comment by Taiga74164** [comment]
eh
