### ISSUE TITLE
[Bug] Cmd Prompt Closes before Genshin opens

### ISSUE THREAD

**Issue by ClickClack7531** [Akebi-Group/Akebi-GC#673]
*The template is Chinese. I aint Chinese*

Ayo, why is Akebi refusing to load Genshin? Whenever I run Akebi (as admin) and wait, the cmd prompt opens, then closes after a while and Genshin doesnt start.
Why?

This is what shows up before it closes
![image](https://user-images.githubusercontent.com/93358773/190021134-815abdb0-c4b3-409c-94d7-c1eee69ade74.png)

**Comment by ClickClack7531** [comment]
> _The template is Chinese. I aint Chinese_
> 
> Ayo, why is Akebi refusing to load Genshin? Whenever I run Akebi (as admin) and wait, the cmd prompt opens, then closes after a while and Genshin doesnt start. Why?
> 
> This is what shows up before it closes ![image](https://user-images.githubusercontent.com/93358773/190021134-815abdb0-c4b3-409c-94d7-c1eee69ade74.png)

Ok, I was able to fix the glitch by deleting all my config files. For those who are unaware, the config files save Akebi's settings. So only delete if you know you can set them back up.

After I deleted the files, I got this message and will sort it out accordingly.
![image](https://user-images.githubusercontent.com/93358773/190026274-76614404-a59d-4ce1-aaa8-9240e3649fc8.png)

**Comment by Taiga74164** [comment]
idk if it's pretty clear but ``Either your game isn't updated or you downloaded the wrong version of Akebi``

if the game version matches with Akebi's branch and you're using a patched UserAssembly, then ``press any key to continue`` (usually if you're using grasscutter or other PS).

**Comment by Taiga74164** [comment]
also the Chinese on the template is commented :skull:
