### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by ztmaev** [Akebi-Group/Akebi-GC#677]
## Manual teleport and teleport to chest/oculus is kinda broken in the chasm

When selecting a manual teleport point on the map, you get teleported on top of the chasm out of the map.
When teleporting to oculi/chest ,you get teleported to a teleport waypoint. (Its also kinda random since you dont get teleported to the closest one)

Steps to reproduce this bug:

**Manual teleport**
1. Go to the chasm underground map.
2. Open map and teleport to an area. (not a waypoint)

**Chest/Oculi teleport**
1. Go to the chasm underground map.
4. go to a place near a chest/oculi.
5. Teleport to chest/oculi.

## Expectation

When teleporting to a place on the map (using manual teleport), you should be teleported to an area in the caves not on the roof.
When teleporting to a chest/oculi you should be teleported to the chest/oculi or close to it.

## Your device information
 
 - System information: Windows 11
 
 - Version: 3.0

**Comment by Taiga74164** [comment]
3.1 ?

**Comment by zhongli0409** [comment]
1 st u teleported very far from initial position second i dont have problem in chasm maybe update ?

**Comment by m0nkrel** [comment]
Teleport on the map is because the altitude coordinate is different than in the open world. Look at your coordinates in the debug menu and set a custom height in the teleport settings
