### ISSUE TITLE
[Suggestion] No gadget CD

### ISSUE THREAD

**Issue by WhisperingTelamonster** [Akebi-Group/Akebi-GC#678]
Hello, like title states. Specifically having no cooldown on The Boon of the Elder Tree would help a lot in collecting wood.

**Comment by zhongli0409** [comment]
not a option ig u got the tree farmer in akebi also with much more setting using the gadget with no cd contant maybe considered as abuse and u can get ban.

**Comment by WhisperingTelamonster** [comment]
Isn't the tree farmer also risky?
