### ISSUE TITLE
Can't sprint when open game with inf stamina is activated

### ISSUE THREAD

**Issue by boteomap2** [Akebi-Group/Akebi-GC#68]
To reproduce this bug, active inf stamina first, do not turn off it and re-open the game, sprint function can't be used even turn the inf stamina off.
-----------
commit: e8f97ef3a57c42c636ad3172bf2759aa99075f69
version: 0.7.5

**Comment by souvikpodder** [comment]
duplicate of #43

**Comment by G1DE30N** [comment]
I have not turned off stamina once (I start the game with it turned on everytime) since the 0.6 release, I have never encountered such a thing.

**Comment by souvikpodder** [comment]
> I have not turned off stamina once (I start the game with it turned on everytime) since the 0.6 release, I have never encountered such a thing.

He is talking about inf stamina normal mode. The bug we discussed in issue #43

**Comment by G1DE30N** [comment]
> > I have not turned off stamina once (I start the game with it turned on everytime) since the 0.6 release, I have never encountered such a thing.
> 
> He is talking about inf stamina normal mode. The bug we discussed in issue #43

ahhh okay
