### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by Vision-996** [Akebi-Group/Akebi-GC#680]
## Describe the problem

Please fill in here a clear and accurate description of the problem you are experiencing.
Hi,Bro,How to translate esp  filters to Chinese?
## How to reproduce this problem

Steps to reproduce this issue:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## Help you need

Please fill in the help you need here.

## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.

## Your device information
 
 - System information:
 
 - Version:

## Additional information

Here you can enter additional information about the help you need.

**Comment by Taiga74164** [comment]
change to Chinese font, rename the strings.
