### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by tangtangebusi** [Akebi-Group/Akebi-GC#683]
## Describe the problem

Please fill in here a clear and accurate description of the problem you are experiencing.
使用最新版本的Akebi时报错（包括我用之前3.0版本编译的也是同样错误）
## How to reproduce this problem

Steps to reproduce this issue:
1. 双击injector.exe
2. 选择路径启动游戏
3. 无法使用Akebi  报错详情请看下方截图

## Help you need

Please fill in the help you need here.
想要使用Akebi
## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.
![image](https://user-images.githubusercontent.com/67052443/190425407-230e7536-8daf-4d91-931f-1eea858c36ed.png)

## Your device information
 
 - System information:
 - 版本	Windows 11 专业版 Insider Preview
版本	22H2
安装日期	‎2022/‎9/‎13
操作系统版本	25197.1000
体验	Windows Feature Experience Pack 1000.25197.1000.0
 
 - Version:
![fd6883785cc7e77cd3947a72fd2207ec](https://user-images.githubusercontent.com/67052443/190426946-a586f25b-5c31-43f1-9a74-98d11a563145.png)
## Additional information

Here you can enter additional information about the help you need.

**Comment by daofeng2015** [comment]
你游戏没画面吗?这控制台显示没问题啊

**Comment by tangtangebusi** [comment]
> 你游戏没画面吗？这画面没问题啊

没有喔  如果正常的话我就不会来提交issue了

**Comment by Taiga74164** [comment]
I don't see anything wrong. Does the GUI show at all?

**Comment by tangtangebusi** [comment]
> I don't see anything wrong with the console. Does the GUI show at all?

没有显示  调不出来GUI

**Comment by Taiga74164** [comment]
Make sure you don't have any active overlay running such as MSI Afterburner, Rivatuner, etc.
