### ISSUE TITLE
[Bug] ESP and Interactive map offset 

### ISSUE THREAD

**Issue by WhisperingTelamonster** [Akebi-Group/Akebi-GC#684]
When running Genshin on lower resolution (windowed) + fullscreen, the items in the interactive map and ESP get offset.
![Captura de pantalla 2022-09-15 184801](https://user-images.githubusercontent.com/58700537/190464749-e3608ce9-11d4-4fa8-ae84-fb04b3991e69.png)
![Captura de pantalla 2022-09-15 184900](https://user-images.githubusercontent.com/58700537/190464763-8987ab51-b38d-494c-9fb3-16736ddf9bd4.png)
![Captura de pantalla 2022-09-15 185600](https://user-images.githubusercontent.com/58700537/190464771-c1e4b3ee-aa90-4d7c-9965-72db6e73de67.png)
![Captura de pantalla 2022-09-15 185610](https://user-images.githubusercontent.com/58700537/190464778-79ac4831-2917-4581-bf9c-1bef9a965936.png)
The reason why I'm playing in lower resolution windowed is because I get more frames. 
On fullscreen it works fine, but I really would like to use the cheat with lower resolution, thanks.

**Comment by lunaticwhat** [comment]
just open the game without akebi, set your wanted resolution & windowed mode and quit your game, re-launch with akebi. Its a known issue that the overlay doesnt like the game when changing resolutions

**Comment by WhisperingTelamonster** [comment]
@lunaticwhat  I did what you said, but if I want to play on lower res on fullscreen I have to press alt + enter, which still causes the ESP and interactive map to get offset. Maybe I didn't understand something, could you help please?

**Comment by FawazTakhji** [comment]
put this in your config file and change the height and width the the ones you want
![Notepad_rJ0542zNHf](https://user-images.githubusercontent.com/56781705/190656973-3487430f-ceda-4e36-9fd6-f05410029aaa.png)

**Comment by WhisperingTelamonster** [comment]
> put this in your config file and change the height and width the the ones you want ![Notepad_rJ0542zNHf](https://user-images.githubusercontent.com/56781705/190656973-3487430f-ceda-4e36-9fd6-f05410029aaa.png)

Hi, thanks for the help. But it didn't fix the ESP and interactive maps being offset, it just put me in lower resolution fullscreen mode 
@FawazTakhji

**Comment by FawazTakhji** [comment]
someone said that changing the display resolution from windows settings and making it the same as the game fixed this issue for him
![image](https://user-images.githubusercontent.com/56781705/190664024-1cc5368a-f160-4ccc-8b90-6318ccfaeaa7.png)

**Comment by WhisperingTelamonster** [comment]
> someone said that changing the display resolution from windows settings and making it the same as the game fixed this issue for him ![image](https://user-images.githubusercontent.com/56781705/190664024-1cc5368a-f160-4ccc-8b90-6318ccfaeaa7.png)

Thank you so much, this actually fixed the offset problem. It's a bit inconvenient though since everything is so small, but atleast it works. Again, thanks
