### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by restarteded** [Akebi-Group/Akebi-GC#686]
## Bug

Please enter a clear and accurate description of this bug here.
No Fog Need to Reopen when enter a Domain
##  How to reproduce this bug

Steps to reproduce this bug:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx
Need do nothing but enter Domains
## Expectation

Give a brief description of what you expect.
If no need to reopen it is the best hh
## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.

## Your device information
 
 - System information:
 
 - Version:

## Additional information

You can enter additional information about this bug here.

**Comment by Taiga74164** [comment]
Changed due to visual bug:
![image](https://user-images.githubusercontent.com/67109235/190659363-488152df-1eb4-4458-9d59-13e686ec5751.png)
