### ISSUE TITLE
teleport position

### ISSUE THREAD

**Issue by Jackzxy123** [Akebi-Group/Akebi-GC#69]
map ID：6
{"name":"111","position":[723.32861328125,926.1394653320313,1000.3558349609375]}

How do you write it?

**Comment by tedzify** [comment]
Are you using it for `Custom Teleports`? If so go to `Debug` > `Position` > `Locate and press "Copy as JSON"` and add it to the JSON input on `Custom Teleports`

**Comment by Jackzxy123** [comment]
Cannot teleport other area maps.

**Comment by G1DE30N** [comment]
If you mean Different locations like - enkanomia and underground chasm - You CANT teleporting Crossdimensionaly. Before you can teleporting across specific map you NEED to be in that map in legal way (vanilla tp to that location)
