### ISSUE TITLE
Where is the ShootingAnimation?

### ISSUE THREAD

**Issue by crave6948** [Akebi-Group/Akebi-GC#690]
I can't find the Animation that can shooting arrow when using a charged attack.

**Comment by Taiga74164** [comment]
// Holding
``[Debug] [AnimationChanger.cpp:110] ShootStandbyBS``
``[Debug] [AnimationChanger.cpp:110] FastAimLoop``

// Toggle R
``[Debug] [AnimationChanger.cpp:110] AimLoop``

Seems there's none for the actually shooting the charge shot :(

**Comment by Taiga74164** [comment]
https://github.com/Akebi-Group/Akebi-GC/commit/9c91ab3dfed1305ac1ab21fe781ca391f485723e

**Comment by crave6948** [comment]
Thx, It must be useful.
