### ISSUE TITLE
Json fetch request failed[Help]

### ISSUE THREAD

**Issue by silverfrui** [Akebi-Group/Akebi-GC#691]
## Describe the problem

Please fill in here a clear and accurate description of the problem you are experiencing.

I can't use any features when I open the game，

[telemetry:0916/225858.724:ERROR:mihoyo_url_fetch_delegate.cc(22)] Json fetch request failed with error code: -1
[telemetry:0916/225858.724:ERROR:mihoyo_report_service_base.cc(345)] TelemetryServiceplat_explog_sdk_v2 : Http request failed. Response body:

## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.

![image](https://user-images.githubusercontent.com/105756505/190670129-be1086a6-3447-4c67-a173-8c2f33ef259b.png)

## Your device information
 
 - System information:
 
 - Version:

**Comment by Taiga74164** [comment]
Akebi has nothing to do with those logs tho.

> I can't use any features when I open the game，

I assume Akebi injected fine but you can't see the gui in-game. Make sure you don't have any active overlay such as MSI Afterburner, Rivatuner, etc.

**Comment by silverfrui** [comment]
谢谢，我关闭了MSI后可以使用了
