### ISSUE TITLE
[Suggestion]

### ISSUE THREAD

**Issue by SteffenTAN** [Akebi-Group/Akebi-GC#692]
##  Mark for Dangerous feature or make a Safe Mod Menu

as What I write above, I sugest for Marked Dangerous Feature or a version of Safe Mod Menu That might be decreased the Dangerous Feature because I get banned previously because of That I thought the Feature I used is Safe because of the Description. but, I still got banned even I already make sure by reading feature info about "dangerous or safe" and didn't use any dangerous mod.

so, maybe I need some detailed information about Safe/Dangerous or maybe just remove it or make a safe version of the Mod or a filter for Safe/Unsafe/Dangerous Mod.

##  How does the suggestion work?

Simply step:
1. Player searching for Safe Mod
2. Player use the Mod
3. Done

Thank You for Reading
Best Regard,
Steffen

**Comment by Taiga74164** [comment]
Well what if I tell you almost everything in World and Player are on the list of detections. Only visual features doesn't have detection.

**Comment by SteffenTAN** [comment]
it's almost everything, right?
not "everything" :v
