### ISSUE TITLE
[Help] Runtime error

### ISSUE THREAD

**Issue by Kolya62** [Akebi-Group/Akebi-GC#693]
Hello everyone, I have a problem. All the details are in the screenshot:
![screenshot (3)](https://user-images.githubusercontent.com/106597499/190687671-335ae026-4ed8-448f-aeaa-c3a833c4e907.png)
![screenshot (4)](https://user-images.githubusercontent.com/106597499/190687674-ceb63d76-1491-46ba-8142-1ebfcab6d2cd.png)
![screenshot (5)](https://user-images.githubusercontent.com/106597499/190687677-81fe5b08-b3d8-4784-83a1-668e7ade518e.png)

**Comment by FawazTakhji** [comment]
open cfg.json and delete the autocook section
