### ISSUE TITLE
[Help]深渊和活动使用会被封号吗

### ISSUE THREAD

**Issue by Needdaima** [Akebi-Group/Akebi-GC#695]
## Describe the problem

Please fill in here a clear and accurate description of the problem you are experiencing.

## How to reproduce this problem

Steps to reproduce this issue:
1. xx
2. xxxx
3. xxxxxx
4. xxxxxxxx

## Help you need

Please fill in the help you need here.

## Screenshot/Video

If possible, please attach your screenshot or video here. You can use Ctrl + V to paste the picture directly.

## Your device information
 
 - System information:
 
 - Version:

## Additional information

Here you can enter additional information about the help you need.

**Comment by gawgua** [comment]
anything can be ban
if you got banned, get lucky next time
