### ISSUE TITLE
Can a Chinese version be published later?

### ISSUE THREAD

**Issue by djjsns** [Akebi-Group/Akebi-GC#699]
I'm not very proficient in English, and I can't understand many of them.
Or set some settings to default.
For example, uid modification, role drop-down transparency

**Comment by Taiga74164** [comment]
Translation support is already planned. There is a lot of work to do for it so for now it's not being worked on.

For the mean time, you can find people who manually changed all the strings in the project. There are few people on our discord who worked on Chinesization already.
