### ISSUE TITLE
[Help] Does Genshin store any personal info on my computer?

### ISSUE THREAD

**Issue by ClickClack7531** [Akebi-Group/Akebi-GC#701]
My account got banned for a month and I want to create and use a new one, but Im paranoid that Genshin maybe have put my IP on watch list or have some registry entry that tells Genshin's servers to keep an eye on me or something like that. Does mihoyo store anything like this either on their servers or on my local machine? And if on my local machine, where? And can I remove it, or reset it?

**Comment by ztmaev** [comment]
I don't think there's any way to know that. just create a new account and run it for some time.
Also if they do hardware bans you can use hardware spoofers.
If you discover something new, post here

**Comment by Taiga74164** [comment]
server bans only, you can still switch server on that same account if you ever get banned. stop being paranoid

**Comment by ClickClack7531** [comment]
> server bans only, you can still switch server on that same account if you ever get banned. stop being paranoid

lol sorry. But you aint deny that I was paranoid for a good reason. Thx for telling me tho

**Comment by bayudewan** [comment]
what feature did you use before getting ban?
