### ISSUE TITLE
Can we build an Artifact prediction function

### ISSUE THREAD

**Issue by 1zhangtengfang** [Akebi-Group/Akebi-GC#705]
Some cheating plug-ins in China can already support the prediction of Artifacts

I don't know if this is feasible

（My English is not very good This is machine translation）

**Comment by zhongli0409** [comment]
are u some magic influencer for genshin server

**Comment by harlanx** [comment]
Can you show an example from CN plugin you mention?

**Comment by 1zhangtengfang** [comment]
> Can you show an example from CN plugin you mention?

Is this possible?
