### ISSUE TITLE
[Help]Custom Resolution cause Interactive map and ESP offset

### ISSUE THREAD

**Issue by HYBBWuXiDiXi** [Akebi-Group/Akebi-GC#709]
When i use custom resolution by change genshin's resolution regedit,interactive map and esp will be offset

Steps to reproduce this issue:
1. change genshin's resolution by regedit

## Help I need

Can Let the Interactive map and ESP function adapt to the custom resolution?

![无标题](https://user-images.githubusercontent.com/87941132/191033492-9a2cd4be-361c-446a-b528-6cf695d30726.png)
![无标题1](https://user-images.githubusercontent.com/87941132/191033583-9b6a3708-73ff-4f37-9b20-c00af3d87122.png)

## Device information
 
 - System information:Windows 11 22H2
 
 - Version:22622.598

**Comment by harlanx** [comment]
You can try setting the resolution via config also check if the solution found in #684 will fix it for you

**Comment by HYBBWuXiDiXi** [comment]
> You can try setting the resolution via config also check if the solution found in #684 will fix it for you

thx for reply,I just looked at the solution in #684 , this need to modify the system resolution, can provide some method to make the ESP back to normal without changing the system resolution and maintaining the custom resolution of genshin
