### ISSUE TITLE
Hope to get translation support

### ISSUE THREAD

**Issue by Gktwo** [Akebi-Group/Akebi-GC#71]
Your credit is great. It is the most perfect Genshin cheat I know. I want to make an excessive request. Can you add a translation option? I don't know much about programming, that is, loading a document and displaying it in other countries' languages. Sorry, I'm using translation software

**Comment by Gasteium** [comment]
yo but english is the language of the world.. you need to know this yes or yes and just clarify that my native language is spanish uwu

**Comment by Gktwo** [comment]
我知道，我能够看懂英语，我并不是要求作者给出翻译结果，我是说支持让其他语言使用者提交支持翻译的文档

> 哟，但英语是世界语言..你需要知道这个是或是，并澄清我的母语是西班牙语uwu

**Comment by Gktwo** [comment]
> yo but english is the language of the world.. you need to know this yes or yes and just clarify that my native language is spanish uwu

I know that I can understand English. I don't ask the author to provide translation results. I mean that users of other languages can submit documents that support translation

**Comment by G1DE30N** [comment]
Yep i can translate cheat to Rus for example.

**Comment by Emilia33** [comment]
i can translate the hack to indonesian

**Comment by Leiiiiii159** [comment]
Also hope to support Bilibili Server

**Comment by CNLouisLiu** [comment]
My native language is Chinese, but if there is a translation, there will be many Chinese people selling it publicly on Tieba or Taobao and even many QQ groups.This is what none of us want to see.

**Comment by CNLouisLiu** [comment]
> Also hope to support Bilibili Server

BiliBili should be supported

**Comment by Leiiiiii159** [comment]
> > 也希望能支持B站服务器
> 
> 哔哩哔哩应该支持

  
No, I'm using the Bilibili client, but starting the game with this cheat will turn into a Mihoyo login screen

**Comment by WitchGod** [comment]
There has been some discussion about translations. There will be support for that eventually, but it is extremely low priority. Take note that Callow actually knows very little English but he tries as much as possible without translating. His expectation of the user base is kinda on-point: have the brains to use or abuse the product, because we don't really care--after all, this is all free.

If you really want translations, either you fork the repo and translate it or contribute to the development. It's not that difficult, really. The core dev team right now doesn't even care about you guys selling it and we know some of you are. Heck, I've even seen one dev change the GUI to a shittier design just to sell it, lmao.

**Comment by G1DE30N** [comment]
> There has been some discussion about translations. There will be support for that eventually, but it is extremely low priority. Take note that Callow actually knows very little English but he tries as much as possible without translating. His expectation of the user base is kinda on-point at the same level: have the brains to use or abuse the product, because we don't really care--after all, this is all free.
> 
> If you really want translations, either you fork the repo and translate it or contribute to the development. It's not that difficult, really. The core dev team right now doesn't even care about you guys selling it and we know some of you are. Heck, I've even seen one dev change the GUI to a shittier design just to sell it, lmao.

In today state translation of cheat a bit difficult for people like me who absolute zero at code, and the problem lies in the lack of a system that allows you to load the necessary lines from an external localization file. Of course, you can easily translate the code, but again, without knowing it, you can translate the wrong thing and break everything to hell.

**Comment by G1DE30N** [comment]
Alright i forked repo and try translate to Rus, but ofcourse that method didn't work. Why? Because this.
![image](https://user-images.githubusercontent.com/104440397/171602396-f137dcc4-1de7-4ecf-b1d7-6905e655ec10.png)

**Comment by Gktwo** [comment]
> My native language is Chinese, but if there is a translation, there will be many Chinese people selling it publicly on Tieba or Taobao and even many QQ groups.This is what none of us want to see.

倒狗圈狗杀不完的，开源的东西肯定早偷过去了

**Comment by WitchGod** [comment]
> Alright i forked repo and try translate to Rus, but of course that method didn't work. Why? Because this. ![image](https://user-images.githubusercontent.com/104440397/171602396-f137dcc4-1de7-4ecf-b1d7-6905e655ec10.png)

Seems like you didn't read my reply well. There's very little to gain by translating it _now_. Obviously we know that supporting multiple languages is not as easy as simply using Cyrillic or Chinese characters in ImGui. It requires some Unicode wrangling and all the works to make it happen.

When the time comes it's implemented, it will be as easy as a JSON file that corresponds to the sections in the GUI and simple `{"en": "Rapid Fire", "ru": "Rapid Fire in RU, "cn": "Rapid Fire in CN", ...}` etc. Contributors can come in and edit the file and distribute it or whatever.

Currently, the priority is the core of the code plus more feature research, not the language. The agreement is that v3.0 if not a later version will tackle this, not in the current version (v2.x).

Obviously if you guys want to _really_ add it, **again**, nothing is stopping you from contributing or forking and adding whatever framework is needed to address the missing support.

**Comment by G1DE30N** [comment]
If someone, like me, decides to fork and translate the cheat through the code itself, I figured out how to add support for the necessary characters (the test showed that it works) an example for Cyrillic, I understand that other languages will need their own set of characters.

![image](https://user-images.githubusercontent.com/104440397/171633231-ca9f918c-4e04-451a-ae92-6322401c9b98.png)

**Comment by ScatteredSnow** [comment]
When I use getglyphrangeschinesefull(), it will crash after the game starts

> 如果像我这样的人决定通过代码本身分叉和翻译作弊，我想出了如何添加对必要字符的支持（测试表明它有效）西里尔文的一个例子，我知道其他语言将需要他们的自己的字形范围。 ![图片](https://user-images.githubusercontent.com/104440397/171633231-ca9f918c-4e04-451a-ae92-6322401c9b98.png)
> 
> 对于像中文这样的大多数语言，您需要为 ImGui 找到合适的字体。将其放在“cheat-library/res/”中并更改同一文件夹中 res.rc 文件中的值 ![图片](https://user-images.githubusercontent.com/104440397/171635376-9f36f286-33ba-46b7-bd3f-f6ad18316306.png)
> 
> 概念证明： ![图片](https://user-images.githubusercontent.com/104440397/171642113-c780a6cf-1767-4a2f-bcc0-4898e57fdf5e.png)

When I use getglyphrangeschinesefull(), it will crash after the game starts

**Comment by ScatteredSnow** [comment]
> > > 如果像我这样的人决定通过代码本身分叉和翻译作弊，我想出了如何添加对必要字符的支持（测试表明它有效）西里尔文的一个例子，我知道其他语言将需要他们的自己的字形范围。 ![图片](https://user-images.githubusercontent.com/104440397/171633231-ca9f918c-4e04-451a-ae92-6322401c9b98.png)
> > > 对于像中文这样的大多数语言，您需要为 ImGui 找到合适的字体。将其放在“cheat-library/res/”中并更改同一文件夹中 res.rc 文件中的值 ![图片](https://user-images.githubusercontent.com/104440397/171635376-9f36f286-33ba-46b7-bd3f-f6ad18316306.png)
> > > 概念证明： ![图片](https://user-images.githubusercontent.com/104440397/171642113-c780a6cf-1767-4a2f-bcc0-4898e57fdf5e.png)
> > 
> > 
> > When I use getglyphrangeschinesefull(), it will crash after the game starts
> 
> Try use 'GetGlyphRangesChinese()' instead. And dont forget to change font.
> 
> And remember: trying to localise cheat code in my experience is a pain in the ass, because you can simply broke anything just by translation because some strings what looks like interface text - in fact, it is not, but is something like an anchor for some other piece of code, and when you try to translate such an anchor as a result, you get either a completely broken cheat or a broken part of its functions and then sit and guess what exactly causes the failure. Sometimes the cheat itself will hint to you where the problem place is, and sometimes it is completely unclear.
> 
> I just showed you how to do it for those who can't wait for official localization support, it's not a panacea and I don't encourage anyone to do it.
> 
> Simple example: Green - What you CAN translate, and Red - What you cant. Whats difference? Only Callow may know. And this ignorance of what you can translate and what you can't, forces you to study the whole code, which is the main problem for anyone who decides to start doing it. ![image](https://user-images.githubusercontent.com/104440397/171737106-50cb227c-73b9-4c69-8fad-98e1f42b9595.png) ![image](https://user-images.githubusercontent.com/104440397/171737172-e5d69929-086c-4d02-acdb-973f7483c7b3.png)
> 
> And of cource dont forget about merging new commits from original repo to your fork, because as i know every new commit simply ovveride all your translation work and revert anything back to eng.
> 
> In general, this method is suitable only for those who want to make a translation here and now, and all these subtleties and nuances are not a hindrance for him.
I modified the font, but when I added "GetGlyphRangesChinese()", it will crash when starting the game

**Comment by ScatteredSnow** [comment]
To be exact, crash after thread creation

**Comment by G1DE30N** [comment]
> If I do not add 'ImGui::GetIO().Fonts->GetGlyphRangesChineseFull()' can run normally

I can't help you with that, maybe Callow used some sort of modified ImGui because any guides i saw on internet slightly different code structure than in this cheat. Maybe imgui in this cheat doesn't support non latinic/cyrillic characters. And Maybe because in cheat callow dont implemented the system of definition of glyph ranges, or maybe implemented it in another way, i fortunately doesn't know his code well to understand it.
But in ideal in code font needed to be defined like this:
'io.Fonts->AddFontFromFileTTF("fontawesome-webfont.ttf", 16.0f, &config, ranges);'
And glyph ranges be defined like this:
'const ImWchar*  ImFontAtlas::GetGlyphRangesChinese()
{
    static const ImWchar ranges[] =
    {
        0x0020, 0x00FF, // Basic Latin + Latin Supplement
        0x3000, 0x30FF, // Punctuations, Hiragana, Katakana
        0x31F0, 0x31FF, // Katakana Phonetic Extensions
        0xFF00, 0xFFEF, // Half-width characters
        0x4e00, 0x9FAF, // CJK Ideograms
        0,
    };
    return &ranges[0];
}'

But in cheat code i not find anything like that structure.

Any i can help:
Try https://github.com/kaienfr/Font/blob/master/font/ARIALUNI.TTF this font instead.

**Comment by Jackzxy123** [comment]
> Your credit is great. It is the most perfect Genshin cheat I know. I want to make an excessive request. Can you add a translation option? I don't know much about programming, that is, loading a document and displaying it in other countries' languages. Sorry, I'm using translation software

你自己用的话习惯后中文和英文没太大区别，如果你打算汉化再卖的话，那么只能说自己慢慢研究吧，估计也没人会告诉你怎么做了，只能从英文开始自己慢慢学习了。毕竟有很多人修改这个代码后拿来贩卖，比如说“可乐”的XM。。。
要是直接改源代码的话，我只能说工作量太大，逐条修改后遇到源代码更新后，又需要修改一次，所以个人用户的话我想不出有什么动力去做这么一件事情。
![QQ截图20220604200618](https://user-images.githubusercontent.com/104795888/171998557-397207d0-ee50-403b-838b-5bee129be94a.png)

**Comment by Yunzh1337** [comment]
> My native language is Chinese, but if there is a translation, there will be many Chinese people selling it publicly on Tieba or Taobao and even many QQ groups.This is what none of us want to see.

已经有国人借鉴源码做挂了，不过目前还没有收费

**Comment by assBuk** [comment]
Я бы не буду против если просто вывести в следующем обновлении софта,  ini файл для перевода. Некоторых пояснений-описаний _(?)_

我不介意你在下一次软件更新中拿出一个ini文件来翻译。一些解释-描述_(?)_

I would not mind if you just put in the next software update, ini file to translate. Some explanations-descriptions _(?)_
This is much easier for anyone who would like to add their own language. Literally everyone would be able to modify this file on your github by adding their own language.) Also, if the file has a broken translation, the interface should use English by default.

**Comment by Sergiy3013** [comment]
> Я бы не буду против если просто вывести в следующем обновлении софта, ini файл для перевода. Некоторых пояснений-описаний _(?)_
> 
> 我不介意你在下一次软件更新中拿出一个ini文件来翻译。一些解释-描述_(?)_
> 
> I would not mind if you just put in the next software update, ini file to translate. Some explanations-descriptions _(?)_ This is much easier for anyone who would like to add their own language. Literally everyone would be able to modify this file on your github by adding their own language.) Also, if the file has a broken translation, the interface should use English by default.

Думаю будет проблема с кодировкой, вы могли встретить это при создании нового профиля или собственной точки телепортации если использовали кириллицу.

I think there will be a problem with the encoding, you could meet this when creating a new profile or your own teleportation point if you used Cyrillic.

**Comment by assBuk** [comment]
Ты не там меня понял, проблема кодировки, это проблема шрифтов.
Я пытаюсь донести другое, не перевод кода из исходника, а выводить для перевода в конфигурацию json или ini
к примеру, просто считывать файл перевода, как он считывает файл профиля)

english.json
russian.json
chinese.json и т.д

А тело файла довольно банальна.
Вот тело
к примеру китайского
**chinese.json**
```
{
  0, "General": "一般",
  1, "CreateProfile": "新的配置文件"
  2, "No-Clip": "NoClip"
  3, "NoClip is a feature that allows you to fly through walls and other obstacles":"NoClip功能，允许你穿过墙壁和其他障碍物飞行"
}
```

Думаю моя мысль была донесена.


---
Не думал что - кто-то забросит просто из за того что кодировка другая, тогда какой из него кодопис если он банальный кодировки поленился исправить :)
---

> You got me wrong, the encoding problem is a font problem.
> I'm trying to make a different point, not to translate code from source, but to output for translation in the json or ini configuration
> for example, just read the translation file as it reads the profile file)
> 
> english.json
> russian.json
> chinese.json, etc.

**Comment by Sergiy3013** [comment]
> Ты не там меня понял, проблема кодировки, это проблема шрифтов. Я пытаюсь донести другое, не перевод кода из исходника, а выводить для перевода в конфигурацию json или ini к примеру, просто считывать файл перевода, как он считывает файл профиля)
> 
> english.json russian.json chinese.json и т.д
> 
> А тело файла довольно банальна. Вот тело к примеру китайского **chinese.json**
> 
> ```
> {
>   0, "General": "一般",
>   1, "CreateProfile": "新的配置文件"
>   2, "No-Clip": "NoClip"
>   3, "NoClip is a feature that allows you to fly through walls and other obstacles":"NoClip功能，允许你穿过墙壁和其他障碍物飞行"
> }
> ```
> 
> Думаю моя мысль была донесена.
> 
> Не думал что - кто-то забросит просто из-за того что кодировка ломает там координаты, значит не то переводишь, или переводишь то что не нужно переводить, тогда какой из него программист если он банальный кодировки поленился исправить, тогда зачем вообще начинать писать на cpp если есть csharp. Не тогда зачем вообще открывать JetBrains или VS22 ? :)
> 
> > I did not think that - someone will give up just because the coding breaks the coordinates there, then translate wrong or translate what does not need to be translated, then what a programmer if he lazy to fix the banal encoding, then why even begin to write in cpp if there is csharp. Not then why even open JetBrains or VS22?)
> 
> > You got me wrong, the encoding problem is a font problem.
> > I'm trying to make a different point, not to translate code from source, but to output for translation in the json or ini configuration
> > for example, just read the translation file as it reads the profile file)
> > english.json
> > russian.json
> > chinese.json, etc.
> 
> А ну в принципе я этого и хотел написать, только не нужно пихать язык перевода в один json
> 
> > That's basically what I wanted to write, just don't cram the translation language into one json
> 
> [Message WitchGod](https://github.com/Akebi-Group/Akebi-GC/issues/71#issuecomment-1144705396)

Если дело обстоит так, то несомненно, это было бы чрезвычайно удобно, и да ваша мысль была донесена, спасибо :)
If this is the case, then surely it would be extremely convenient, and yes your point was conveyed, thanks :)
