### ISSUE TITLE
[Help] My account was banned for a month

### ISSUE THREAD

**Issue by xia0ji233** [Akebi-Group/Akebi-GC#718]
I just want to know how mihoyo detect that I use this cheat.here is my cfg.json
[cfg.txt](https://github.com/Akebi-Group/Akebi-GC/files/9632109/cfg.txt)

**Comment by Lunairayz** [comment]
autoloot lmfao

**Comment by DIXLOR15** [comment]
Noclip speed 188, Fast Dialog True, infinity Staminna, NO CD, Teleports. And you seriously want to know why the ban? 
This is a very bad cfg, very fast ban

**Comment by xia0ji233** [comment]
> Noclip speed 188, Fast Dialog True, infinity Staminna, NO CD, Teleports. And you seriously want to know why the ban? This is a very bad cfg, very fast ban

Thanks for your reply and I have known about it.

**Comment by Lunairayz** [comment]
> Noclip speed 188, Fast Dialog True, infinity Staminna, NO CD, Teleports. And you seriously want to know why the ban? This is a very bad cfg, very fast ban

fast dialog is fine
no cd is fine
teleports is fine
for me tho

**Comment by zhongli0409** [comment]
no cd gib u ban in low ar also if u spam nd wtf is no clip speed 188u will fly the map in a sc and will get ban
also autoloot with low ms and over 30m gib u ban

**Comment by Hexafluorine** [comment]
> > Noclip speed 188, Fast Dialog True, infinity Staminna, NO CD, Teleports. And you seriously want to know why the ban? This is a very bad cfg, very fast ban
> 
> fast dialog is fine no cd is fine teleports is fine for me tho

Fast dialog is a bit dangerous

**Comment by Julienraptor01** [comment]
> > > Noclip speed 188, Fast Dialog True, infinity Staminna, NO CD, Teleports. And you seriously want to know why the ban? This is a very bad cfg, very fast ban
> > 
> > fast dialog is fine no cd is fine teleports is fine for me tho
> 
> Fast dialog is a bit dangerous

Fast dialog is sussy since it's speed up game when talking to an NPC
