### ISSUE TITLE
Multi-hit does not work on previous character's elemental burst after switching character

### ISSUE THREAD

**Issue by mooneternal99** [Akebi-Group/Akebi-GC#73]
When using a character's elemental burst that stays on the field for a while, then you switch to another character, the multi-hit does not work anymore for that particular elemental burst. It goes back to single value.

For example, when I'm using Venti's burst, Multi-hit works as normal on his burst when he is still on the field. Though when I switched to another character, his burst damage revert back to single value. This bug applies to any character's elemental burst that stays on the field to deal damage, whether it is Ayaka, Ayato or Venti.

Date Occured: Multiple times and it is always
Is it reproducible: Yes, just use any character's elemental burst that stays on the field, and then switch to another character, then the multi-hit damage does not work anymore.
Release Version: 0.75

**Comment by mooneternal99** [comment]
Further note: Multi-hit does not work on Mona's burst damage (her bubble burst) too after switching character. Though if you stay as Mona and attack the enemies to burst the bubble, the multi-hit works. The multi-hit burst damage stops working after switching to another character.

**Comment by tedzify** [comment]
`Multi-hit` only works for on field characters.
