### ISSUE TITLE
[Info/Bug] About ESP for Callow.

### ISSUE THREAD

**Issue by G1DE30N** [Akebi-Group/Akebi-GC#74]
Hi @CallowBlack, remember all my teories about Ui Screwing? 
I run some stress tests for two days played about 8-10 hours continuesly session each day, and found interesting discovery. 
Personally for me, if i simply absolutely not use ESP, UI won't screw at all.
Of cource this is not 100% info about issue, but now you know where to dig to fix that problem.

P.S.
Heh, of course, I initially had suspicions about ESP, but for some reason it seemed more that the interactive map was to blame. 
It is possible that the problem lies in the fact that the interface goes on the ass at times when there are too many boxes or tracers on the screen and maybe it is incorrectly refreshed or something. 
I'll try to test a couple more days with ESP and minimal settings - without tracers and with 2d boxes, and see if the interface will also break or not.

**Comment by Legend-Recalls** [comment]
okay i know this is a bit different to talk abt but recently I was using 16 gb laptop now I am using 16 + 4 and surprisingly I never came around this bug again (been weeks). So maybe its memory issue or sth?

**Comment by G1DE30N** [comment]
> okay i know this is a bit different to talk abt but recently I was using 16 gb laptop now I am using 16 + 4 and surprisingly I never came around this bug again (been weeks). So maybe its memory issue or sth?

Really idk but my laptop have 16 gb too, and i always catch this bug when use interactive map and esp, if i turn off both bug never occurs. I really not sure about memory issue.

**Comment by CallowBlack** [comment]
> Hi @CallowBlack, remember all my teories about Ui Screwing? I run some stress tests for two days played about 8-10 hours continuesly session each day, and found interesting discovery. Personally for me, if i simply absolutely not use ESP, UI won't screw at all. Of cource this is not 100% info about issue, but now you know where to dig to fix that problem.
> 
> P.S. Heh, of course, I initially had suspicions about ESP, but for some reason it seemed more that the interactive map was to blame. It is possible that the problem lies in the fact that the interface goes on the ass at times when there are too many boxes or tracers on the screen and maybe it is incorrectly refreshed or something. I'll try to test a couple more days with ESP and minimal settings - without tracers and with 2d boxes, and see if the interface will also break or not.

Hmm, interesting. Maybe some calls inside `game::EntityManager` occur race condition or something. I don't think that RAM has any direct relation to this problem. Possibly just decrease chance due to reduced Page-Memory transporting. But I'm almost positive that issue is in some function call. And it can be `game::EntityManager` because it used very often, and with enabled `ESP` every frame.

**Comment by CallowBlack** [comment]
I link this issue to the main issue with this bug, and close it to prevent spamming.

**Comment by CallowBlack** [comment]
Information for #15
