### ISSUE TITLE
Mouse side button hotkey doesn't work

### ISSUE THREAD

**Issue by DarkXonline** [Akebi-Group/Akebi-GC#75]
It detects the side button as hotkey, but not working when pressed
![06_03_22 1654260029 (08-40-29-980 PM) - GenshinImpact](https://user-images.githubusercontent.com/22949719/171855974-f7e99f83-633e-40f4-ba6a-c85723c536fa.png)

**Comment by G1DE30N** [comment]
As far as I remember Callow mentioned this and yes, the side mouse buttons don't work in cheat yet, but maybe they will be implemented in future updates.

**Comment by DarkXonline** [comment]
> As far as I remember Callow mentioned this and yes, the side mouse buttons don't work in cheat yet, but maybe they will be implemented in future updates.

Damn, that is a bummer, as I always use it in xyz. Thanks for the answer!

**Comment by DarkXonline** [comment]
I'll reopen the issue because the actual problem is not fixed yet lol.
