### ISSUE TITLE
Game crash at cheat start up

### ISSUE THREAD

**Issue by hxm0313** [Akebi-Group/Akebi-GC#76]
upload_crash release upload:722494

**Comment by Taiga74164** [comment]
upload crash doesn't help us figure out what caused it lol

**Comment by thegodfatheroflove** [comment]
> upload crash doesn't help us figure out what caused it lol. tell us more about what you did and what features you had on

@Taiga74164 what about this ? 
![image](https://user-images.githubusercontent.com/69887271/171910162-260002bd-7b96-4173-a2c7-313dd158bd4a.png)

**Comment by Taiga74164** [comment]
> > upload crash doesn't help us figure out what caused it lol. tell us more about what you did and what features you had on
> 
> @Taiga74164 what about this ? ![image](https://user-images.githubusercontent.com/69887271/171910162-260002bd-7b96-4173-a2c7-313dd158bd4a.png)

you can ignore this. this is due to an encryption they added but it doesn't really affect the project

**Comment by CallowBlack** [comment]
Any updates about the crash? Fixed or not?

**Comment by Taiga74164** [comment]
closed this as it was from last patch and no info provided by author
