### ISSUE TITLE
Releases name

### ISSUE THREAD

**Issue by pokemc32ryan** [Akebi-Group/Akebi-GC#8]
You forgot to change the releases name

**Comment by xlisov** [comment]
Callow, why don't you make a discord server specifically for the cheat?

**Comment by WitchGod** [comment]
> Callow, why don't you make a discord server specifically for the cheat?

Callow doesn't want a Discord server. It's more maintenance with no upside or benefit: GitHub serves the development goal far better. There is an invite-only server where nothing but dev talk and research is happening but that's about it.

**Comment by CallowBlack** [comment]
I maybe will create server in discord, but for now it's not a priority task, because, like @WitchGod said, it needs more maintenance.

**Comment by CallowBlack** [comment]
About release name it's okay, if you about version, I just put the version v0.7 (not the last commit), if you about the cheat name, I'll change it later.
