### ISSUE TITLE
Error InteractiveMap

### ISSUE THREAD

**Issue by Viole403** [Akebi-Group/Akebi-GC#81]
`[Debug] [InteractiveMap.cpp:1717] Not found filter for item 'StarSilver'`

So after I run it came out this kind of problem. 
Should it be ignored or can it be fixed for this?

**Comment by G1DE30N** [comment]
At the current stage, you can score because it doesn't affect anything. I've already written about it a couple of times, but it was stupidly missed, it seems no one cares about it now, since this is not a very critical problem to rush to fix it

**Comment by Viole403** [comment]
> At the current stage, you can ignore this because it doesn't affect anything. I've already written about it a couple of times, but they missed it, it seems no one cares about it now, since this is not a very critical problem to rush to fix it

Okay, thank you for your answer
