### ISSUE TITLE
`Multi-hit`→`Random` crash

### ISSUE THREAD

**Issue by Thafoxes** [Akebi-Group/Akebi-GC#82]
Multi-hit random crash when min and max at the same multiplier.
First video is the demo crashed.
Second is the crash reproduced in game.
Currently running on v0.7.5 - 2.7version anime games
https://gofile.io/d/tdpk5O

**Comment by CallowBlack** [comment]
Hmm, maybe we just didn't add the check for user input. But when you use random, the `min` have to be lower than `max`.

**Comment by assBuk** [comment]
This happens even if the random mode is not set and the value is fixed.
