### ISSUE TITLE
Can you help me?

### ISSUE THREAD

**Issue by flary0** [Akebi-Group/Akebi-GC#83]
Hi, I only want to make an interactive map, my knowledge of Visual c++ is very poor, can you help me with this? If you specify where in the project you can find the data responsible for the map, I will be grateful.

**Comment by G1DE30N** [comment]
https://github.com/theBowja/genshin-db - Here :D

**Comment by CNLouisLiu** [comment]
Maybe you want to rewrite it in e language and sell it?

**Comment by DzXAnt22** [comment]
> Maybe you want to rewrite it in e language and sell it?

some people just want the map without the rest of the mods.. He doesn't have to be selling it

**Comment by flary0** [comment]
> > Maybe you want to rewrite it in e language and sell it?
> 
> some people just want the map without the rest of the mods.. He doesn't have to be selling it

yes, for example, my friend scare of using cheats, but need map, because it will improve the gameplay

**Comment by RyujinZX** [comment]
This will in any case be considered a cheat, and in the case of blocking you will get a ban for cheating.So there is no difference.

**Comment by flary0** [comment]
> This will in any case be considered a cheat, and in the case of blocking you will get a ban for cheating.So there is no difference.

but by the way, you dont have that cheat options(но, ты так то не сможешь использовать чит опции, да я русский.)

**Comment by RyujinZX** [comment]
> > This will in any case be considered a cheat, and in the case of blocking you will get a ban for cheating.So there is no difference.
> 
> but by the way, you dont have that cheat options(но, ты так то не сможешь использовать чит опции, да я русский.)

Карта реализована таким же методом как и другие чит функции.

**Comment by skycon8** [comment]
> but by the way, you dont have that cheat options(но, ты так то не сможешь использовать чит опции, да я русский.)

U can turn of all the options and not using any.  By the way, as long as u injecting anything or open any layer in game will be consider of using cheat.  

If u r worry why dont just use the official interactive map:  https://act.hoyolab.com/ys/app/interactive-map/index.html

**Comment by CallowBlack** [comment]
If you want to use just `Interactive map` just disable other features. Or, the same if you. Or just delete all not needed features here:
https://github.com/Akebi-Group/Akebi-GC/blob/e8f97ef3a57c42c636ad3172bf2759aa99075f69/cheat-library/src/user/cheat/cheat.cpp#L62-L100
