### ISSUE TITLE
Request：“Paimon follow”

### ISSUE THREAD

**Issue by milkboy77** [Akebi-Group/Akebi-GC#85]
Just because I really like Paimon XD.
This is my little request.

**Comment by RyujinZX** [comment]
Okay, I'll try to do that :)

**Comment by ArthaVerx** [comment]
Imagine having paimon always appeared in your screen whenever you go. Must be so amazing v:

**Comment by RyujinZX** [comment]
@milkboy77 @ArthaVerx  I implemented it :)

https://youtu.be/MAQ12BGcEHc

**Comment by milkboy77** [comment]
Cool!!!!

**Comment by RyujinZX** [comment]
> Cool!!!!

I'll try to make it more beautiful with animation as in the quests

**Comment by milkboy77** [comment]
![paimon](https://user-images.githubusercontent.com/106000834/173111107-e35ef880-ded6-43ec-ae96-58c2aeec1998.png)
HEY!!!

**Comment by Taiga74164** [comment]
:eyes:
