### ISSUE TITLE
Backup completed point

### ISSUE THREAD

**Issue by kaninayut** [Akebi-Group/Akebi-GC#91]
Hi!
The funtion "save completed points" in your cheat, It has 3 options global, profile and account. So i wonder where it was saved, does it saved on mihoyo website or anywhere in my machine. Because any time i changed my acc it will keep my previous acc progress. Is there any way to backup it because i have to mark my completed point again every time if the cheat has an update. Or maybe i dont know how to use :v.
English is not my main language so if there is any mistake, please omit it
Thank for reading !

**Comment by tedzify** [comment]
It's saved in your `cfg.json` file.

**Comment by tedzify** [comment]
> So as long as i keep cfg.json file in the cheat folder my progress will be saved, even have a new update or i have to load cfg file :vv

As long as the cheat still supports the format of the `cfg.json` file it will automatically load it.

**Comment by kaninayut** [comment]
oke thank you guys
