### ISSUE TITLE
`Instant bow` not working with Yelan

### ISSUE THREAD

**Issue by itvhot1** [Akebi-Group/Akebi-GC#92]
fix Yelan intants bow charge ?

**Comment by G1DE30N** [comment]
> fix Yelan intants bow charge ?

Yelan not only one character with same bug especialy most characters don't do any damage with charged attack.
For worked instant bow charge you need disable multihit.
Maybe will be fixed maybe not, because one of old bugs which still not fixed.

**Comment by CallowBlack** [comment]
Can you give the copy of cast names after bow charged attack?
![image](https://user-images.githubusercontent.com/37184274/172968196-9b69fc95-0ef9-4938-8b8a-9a728f149638.png)

**Comment by G1DE30N** [comment]
![image](https://user-images.githubusercontent.com/104440397/172970728-cea2ef9b-86ec-43e4-8f80-99ed2185195f.png)

Ability Log:
04:15:37 | Key: _ABILITY_Yelan_Sneak_TickCount value 1. 'Instant Bow Charge Skill - When Arrow Shooted'
04:15:35 | Key: _Enchanted_Time value 5. ''Instant Bow Charge Skill - While Aiming''
04:15:35 | Key: _ABILITY_Yelan_TeamElementNum value 1. '''Instant Bow Charge Skill - Charged Bracelet'''
