### ISSUE TITLE
can't teleport to lumenspar and chest in underground chasm

### ISSUE THREAD

**Issue by xmalz** [Akebi-Group/Akebi-GC#94]
![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/107164688/172758825-36b1c397-5129-48e4-a990-c15a84a22da9.gif)

i can't teleport to lumenspar and chest in underground chasm but when in mondstad and liyue you can

**Comment by kaninayut** [comment]
yeah look like tp in here havent supported yet

**Comment by Micah123321** [comment]
Here, you need to click TP first, and then transfer it to the nearby anchor point. In this way, you can successfully transfer it

**Comment by CallowBlack** [comment]
Just case of #6
