### ISSUE TITLE
Add options to `ESP`

### ISSUE THREAD

**Issue by GodKratos** [Akebi-Group/Akebi-GC#95]
Is it possible to add the following items to be able to be shown in ESP mode:

- ~~Wooden Crates (the floating mora boxes)~~
- ~~Geo Sigils~~
- ~~Relay Stone (from the Electric conductor puzzles in Inazuma)~~
- Dig spots

Additionally, is it possible to tell the difference between a Time Trial Challenge that has been completed, and one that hasn't been completed? If so, it would be nice to be able to separate them so you could disable showing the ones that are complete. Same for other puzzles such as Elemental Monuments, Cube Devices, Electro Seelies and Bloaty Floatys.

**Comment by biswop** [comment]
I know the Wooden Crates and the Geo Sigils are under search points.

I agree that it would be nice if the esp stopped showing completed things such as Time Trials, Elemental Monuments, Bloaty Floatys and torch puzzles.

**Comment by WitchGod** [comment]
First three: just need to add entity name to the ESP. And yes, they are search points.

Completion state of entities cannot be determined for now. Some entities don't disappear when they reach the completed state, nor do their names change. This is why the normal Seelies disappear from ESP but Electro Seelies don't, for example. Same logic applies to Bloaty Floatys, etc.

**Comment by biswop** [comment]
what if you linked it to the interactive map so when someone sets it as found it doesn't show with the esp?

**Comment by GodKratos** [comment]
> Completion state of entities cannot be determined for now. Some entities don't disappear when they reach the completed state, nor do their names change. 

Oh, does this mean you only identify them from the entity name? I thought you might be doing some kind of packet sniffing that would have extra data to use from the network packets.

**Comment by biswop** [comment]
> What does this mean? Is there an option currently to see them or this is just a comment about how to get them added?

under chests there is an option for search points it shows all the searchable things, that includes Wooden Crates and the Geo Sigils

**Comment by GodKratos** [comment]
Also, seeing how investigate spots are added for search points, shouldn't dig spots be able to be added in the same way?
