### ISSUE TITLE
can't start game with Bilibili server

### ISSUE THREAD

**Issue by CR4Player** [Akebi-Group/Akebi-GC#96]
I'm trying to run this on bilibili server client.

As long as i start the game by injector, the game will turn into china mainland offical server like this:
<img width="800" alt="china mainland offical server" src="https://user-images.githubusercontent.com/12210261/172875245-8e21c77c-aa91-48d0-9e7a-aea16c4e4536.png">

It's still bilibili server if  i start game by it's launcher or just run yuanshen.exe, really confusing.
<img width="800" alt="bilibili server" src="https://user-images.githubusercontent.com/12210261/172875662-d4abe9e7-0711-4747-954b-912a9a81e440.png">

**Comment by Oniii0** [comment]
This might be unrelated to your problem, but may I ask how you got "Skip Cutscenes"?
I'm at the latest commit.

**Comment by RyujinZX** [comment]
> This might be unrelated to your problem, but may I ask how you got "Skip Cutscenes"? I'm at the latest commit.

It's in my repository, I'll send it to this one soon

**Comment by CNLouisLiu** [comment]
I will look into this issue.

**Comment by CNLouisLiu** [comment]
#208
